### ISSUE TITLE
Calculated import pane is not updated

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1009]
I copied a component, changed the code to not import A but B and the calculated imports pane of its bnd.bnd file still showed A instead of B. Removing its generated directory to force a rebuild had no effect. I had to do a full workspace clean/rebuild cycle to force the pane to update

**Comment by bjhargrave** [comment]
Same class of problem as #1010.

**Comment by pkriens** [comment]
Should be fixed in 1010

General refreshing when the bnd structure changes is not done perfectly

**Comment by pkriens** [comment]
I will handle this in 1010
