### ISSUE TITLE
New builder not working with javax.ws.rs

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1024]
I installed the latest build and I'm having problems getting it to work with javax.ws.rs.  I downloaded javax.ws.rs-api 2.0.1 from Maven central, added it to my Local repository, and added it to the bnd.bnd.  I get error messages that says ```The import javax.ws cannot be resolved```.

**Comment by bjhargrave** [comment]
Can you provide some details? Like a link to your repo? Step to reproduce? Thanks.

**Comment by BryanHunt** [comment]
Deleting the code and re-cloning the repo fixed the problem ... mostly.  The projects came up with errors, but when I opened the files with errors, the errors went away.  The project now builds cleanly.  I wonder if this is related to the issue I have seen where adding a new bundle to the bnd.bnd to fix a compile error does not make the error go away until you force a clean?

**Comment by bjhargrave** [comment]
We are continuing to improve/fix bugs in the new builder implementation. @pkriens just released some fixes to bndtools earlier today.

**Comment by bjhargrave** [comment]
Can we close this issue?
