### ISSUE TITLE
new builder breaks code completion method parameter names

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1028]
Method parameter names are no longer shown, now just generic names like 'arg0' , 'arg1' , etc are shown.
It doesn't matter if 'version=project' or 'version=latest' is used.

Confirmed that before the new builder it worked just fine, both for 'version=project' and 'version=latest'.

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bndtools/pull/1029
