### ISSUE TITLE
Running individual tests from the JUnit view will rerun all tests

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bndtools#1042]
![image](https://cloud.githubusercontent.com/assets/456666/6416684/d6633134-be75-11e4-8116-77bccd518e3b.png)

With unit tests, you can rerun an individual test method or test class, say because if fails, by right clicking on the test and selecting run. However, with the Bnd test launcher, it will run the desired test method, then proceed to run all tests again.

**Comment by timothyjward** [comment]
Note that this problem does not occur when the user right clicks on a single test method in the outline view of the test class and selects "Run As..." -> "Bnd JUnit Test". I have no idea why launching the test this way produces a different result, but it may help to find a solution.

Tim

**Comment by bjhargrave** [comment]
Are you using Junit4 or Junit3? I know I can run an individual test method using Junit3.

**Comment by dhumeniuk** [comment]
I'm using Junit3 (I started with Junit4, but ran into this issue: https://github.com/bndtools/bnd/issues/683).

@timothyjward fortunately your way does work. I just like to be able to quickly rerun tests sometimes.

**Comment by brampouwelse** [comment]
I've seen this behaviour and it seems to depend on how you start the initial test. 

If you run the initial test by right clicking the __test class__ and then select "Run As -> Bnd OSGi Test Launcher (JUnit)" re-running a single test will result in running the selected test followed by all tests. 

But if you run the initial test by right clicking the __bnd.bnd file__ and then select "Run As -> Bnd OSGi Test Launcher (JUnit)" re-running a single test will result in running only the selected test

**Comment by bjhargrave** [comment]
Any progress @timothyjward ?
