### ISSUE TITLE
builder: exceptions after upgrading to latest Luna SR

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1055]
bndtools: 

```
 Bndtools	2.5.0.DEV-20150115-102349-gc6c3540	bndtools.main.feature.feature.group	Bndtools

Errors running builder 'Bndtools Builder' on project ....

java.lang.NoClassDefFoundError: bndtools/preferences/EclipseClasspathPreference
	at org.bndtools.builder.NewBuilder.rebuild(NewBuilder.java:637)
	at org.bndtools.builder.NewBuilder.rebuildIfLocalChanges(NewBuilder.java:545)
	at org.bndtools.builder.NewBuilder.build(NewBuilder.java:199)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Framework arguments:  -showLocation -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -showLocation -product org.eclipse.epp.package.standard.product
```

**Comment by bjhargrave** [comment]
2.5.0 was renamed to 3.0.0 in the development stream and NewBuilder has been replaced. Please reopen if this problem still exists on the latest builds.

**Comment by fhuberts** [comment]
This occurs on the released version!

**Comment by bjhargrave** [comment]
> Bndtools 2.5.0.DEV-20150115-102349-gc6c3540 bndtools.main.feature.feature.group Bndtools

We never released a 2.5.0-DEV version. It is obviously a DEV build. And in any case, NewBuilder is replaced, so we would need to be able to reproduce on the latest builder as there is no NewBuilder class to fix any more.

**Comment by fhuberts** [comment]
FYI
Did a clean eclipse download and bndtools install and it doesn't occur on 2.4.1.REL.

**Comment by marcdejonge** [comment]
I've just hit this exact same issue on a Ubuntu 14.04 machine with Eclipse 4.4.2 and bndtools 2.4.1.REL-20150116-150145-g75d944b. Clean install and added bndtools from the marketplace. Any idea how this could happen?

Furthermore, when I look at the plug-in details I do see a lot of bundles with version 3.0.0.20150320???? (mainly bndlib and api).

Is the release being updated by the build server? I've not added the cloudbees link on this machine.

**Comment by bjhargrave** [comment]
You must have a strange system :-) I just installed eclipse 4.4.2 in a new folder, then the eclipse marketplace client, then bndtools 2.4.1 from the marketplace client. 

bndtools 2.4.1 bundles are served from bintray.com and the cloudbees build system does not interact with the bintray repo.

    biz.aQute.bndlib (2.4.1.201501161923) "bndlib" [Resolved]
    biz.aQute.repository (2.2.0.201501161931) "biz.aQute.repository" [Resolved]
    biz.aQute.resolve (0.2.1.201501161931) "biz.aQute.resolve" [Resolved]
    bndtools.api (2.0.0.201501162002) "bndtools.api" [Resolved]
    bndtools.builder (2.3.1.201501162005) "bndtools.builder" [Active]
    bndtools.core (3.0.0.201501162004) "bndtools.core" [Active]
    bndtools.jareditor (2.4.0.201501162005) "bndtools.jareditor" [Resolved]
    bndtools.release (2.3.1.201501162005) "bndtools.release" [Starting]
    bndtools.repository.base (2.3.1.201501162002) "bndtools.repository.base" [Resolved]
    org.bndtools.embeddedrepo (2.3.1.201501162005) "org.bndtools.embeddedrepo" [Resolved]
    org.bndtools.headless.build.manager (1.0.0.201501162002) "org.bndtools.headless.build.manager" [Active]
    org.bndtools.headless.build.plugin.ant (1.0.0.201501162005) "org.bndtools.headless.build.plugin.ant" [Active]
    org.bndtools.headless.build.plugin.gradle (1.0.0.201501162005) "org.bndtools.headless.build.plugin.gradle" [Active]
    org.bndtools.versioncontrol.ignores.manager (1.0.0.201501162002) "org.bndtools.versioncontrol.ignores.manager" [Active]
    org.bndtools.versioncontrol.ignores.plugin.git (1.0.0.201501162005) "org.bndtools.versioncontrol.ignores.plugin.git" [Active]

**Comment by fhuberts** [comment]
@bjhargrave did you guys change the location from where Marketplace gets the bundles?
If so, would have been nice to your downstream (me) if you'd notified it/them...
What is the new location please?
