### ISSUE TITLE
Invalid warning when project does not have a test folder

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bndtools#1076]
See https://groups.google.com/forum/#!starred/bndtools-users/P2dNquzjwdY for original conversation.

I see a "No test folder test found" warning for projects that don't have any unit tests (no test folder). How do I tell Bnd there are no tests? I would figure not having a test folder would be enough.

Also, I get the message "No entry on the build path uses the bnd bin_test directory test-bin" that seems related, except that the message is created multiple times to the point I have 100's of them. Seems like something is not being cleared out or updated correctly.

**Comment by dhumeniuk** [comment]
Same issue happens with the source folder.

I have some project that only build a bundle from a JAR. I also have some projects that only contain bndrun configurations and do not build bundles (application project). Therefore, they don't have a source folder.

**Comment by bjhargrave** [comment]
Well, in that case you need to create a `src` folder and put an empty `.gitignore` in it. This is done in the bnd projects and the OSGi Alliance's projects. For example: <https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.embedded-repo/src>.
