### ISSUE TITLE
Incorrect "discouraged access" warning (new builder)

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1078]
See example project: https://github.com/njbartlett/bndtools-issue-visibility

In this project, the "Consumer" class in project `org.example.consumer` shows a Discouraged Access warning on its use of `org.example.lib1.Lib1`. However the consumer project has a direct dependency on lib1 and the `org.example.lib1` package is exported.

The reason for the error is that `consumer` also depends on lib2, which has a private-package copy of org.example.lib1, and lib2 comes first on the buildpath. It's possible to make the warning go away by reordering the buildpath but this shouldn't be necessary.

**Comment by bjhargrave** [comment]
This seems expected to me. I think you do need to set the proper order in -buildpath because in an offline build, consumer _will_ compile against the private version of the package is may cause problems.
