### ISSUE TITLE
RFE: improve bnd file error detection / detect trailing backslash

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1083]
It would be nice to detect the following situation and generate an error:
```
-buildpath: \
 	some.package;version=latest,\
 	${junit},\
 -sub: *.bnd
```

IOW: detect the trailing backslash on the line before an instruction/header

**Comment by bjhargrave** [comment]
This is in the wrong repo. Please create the issue on the https://github.com/bndtools/bnd repo.
