### ISSUE TITLE
Markers on included bnd files in other projects are never cleared

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bndtools#1087]
If a project's bnd.bnd includes a file from another project, for example

    -include: ${workspace}/cnf/eclipse/jdt.bnd

and the model marks a warning/error on the included bnd file, the marker appears in the other project. `cnf` in this case. When the problem is corrected, bndtools only clears the markers from the project and not the included bnd file in the other project.

In fact, until the problem is resolved, bndtools keeps adding more markers to the included bnd file each time it builds a project which includes the bnd file. Until I manually deleted the markers on the included bnd file, I was up to 118 markers!

**Comment by njbartlett** [comment]
Given the behaviour I saw in #1099, I'm very nervous about making changes at all in other projects, even if it's only a problem marker. These still create resource deltas that could trigger a rebuild on the other project, and potentially create a loop.
