### ISSUE TITLE
[remote] launcher CommandRedirector output can be slow

### ISSUE THREAD

**Issue by gamerson** [bndtools/bndtools#1091]
When using -runremote and specifying the shell to use "CommandRedirector" if I send a command in the eclipse console like "lb" it will return the output line by line, where it takes maybe 15-20 seconds to output a standard "lb" command with maybe 100 bundles.

**Comment by pkriens** [comment]
Please move this bnd. Can you open it on bnd?

**Comment by gamerson** [comment]
done moved here: https://github.com/bndtools/bnd/issues/933
