### ISSUE TITLE
Tutorial on enroute.osgi.org does not work

### ISSUE THREAD

**Issue by amiga23** [bndtools/bndtools#1093]
When following the tutorial at enroute.osgi.org I get stuck at the run requirements:
http://enroute.osgi.org/tutorial_base/400-run.html

```java
Unable to resolve <<INITIAL>> version=null:
   missing requirement Require[osgi.identity]{}{filter=(osgi.identity=es.scheller.enroute.test1.eval.provider)} [caused by:
   Unable to resolve es.scheller.enroute.test1.eval.provider version=1.0.0.201504032001:
   missing requirement Require[osgi.extender]{}{filter=(&(osgi.extender=osgi.ds)(version>=1.0.0)(!(version>=2.0.0))), effective=active}]
```

If I do not export the api from the provider I do get the following message:

```java
Unable to resolve <<INITIAL>> version=null:
   missing requirement Require[osgi.identity]{}{filter=(osgi.identity=es.scheller.enroute.test1.eval.provider)} [caused by:
   Unable to resolve es.scheller.enroute.test1.eval.provider version=1.0.0.201504031953:
   missing requirement Require[osgi.wiring.package]{}{filter=(&(osgi.wiring.package=es.scheller.enroute.test1.eval.api)(version>=1.0.0)(!(version>=2.0.0)))} [caused by:
   Unable to resolve es.scheller.enroute.test1.eval.api version=1.0.0.201504031950:
   missing requirement Require[compile-only]{}{}]]
```
Tested on Eclipse Luna SR2 (Mac OS X 10.10.2 64 bit) with bndtools 2.4.1
Some issue on Eclipse Mars M6 (Mac OS X 10.10.2 64 bit) with bndtools 2.4.1
Works in Eclipse Mars M6 (Mac OS X 10.10.2 64 bit) with bndtools 3.0 latest build

**Comment by pkriens** [comment]
The tutorial does work on 3.0. enRoute requires 3.0

**Comment by radvieira** [comment]
Sadly I'm experiencing the same problem with the tut.  I can't seem to install version 3.0 of bnd tools.  I'm getting the following on OS X 10.10.3 using Eclipse Luna.  Any help is appreciated.

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.emf,2.6.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.ant,2.8.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.codegen,2.11.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.codegen.ecore,2.11.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.codegen.ecore.ui,2.11.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.codegen.ui,2.6.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.common,2.11.0.v20150512-0501
No repository found containing: osgi.bundle,org.eclipse.emf.common.ui,2.10.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.converter,2.7.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.databinding,1.3.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.databinding.edit,1.3.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.ecore,2.11.0.v20150512-0501
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.change,2.11.0.v20150512-0501
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.change.edit,2.6.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.edit,2.9.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.editor,2.11.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.xmi,2.11.0.v20150512-0501
No repository found containing: osgi.bundle,org.eclipse.emf.edit,2.11.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.edit.ui,2.11.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.exporter,2.7.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.importer,2.9.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.importer.ecore,2.8.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.importer.java,2.7.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.importer.rose,2.8.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.mapping,2.9.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.mapping.ecore,2.6.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.mapping.ecore.editor,2.6.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.mapping.ecore2ecore,2.9.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.mapping.ecore2ecore.editor,2.7.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.mapping.ecore2xml,2.9.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.mapping.ecore2xml.ui,2.8.0.v20150601-0402
No repository found containing: osgi.bundle,org.eclipse.emf.mapping.ui,2.7.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.codegen.ecore,2.11.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.codegen.ecore.ui,2.11.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.codegen,2.11.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.codegen.ui,2.8.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.common,2.11.0.v20150512-0501
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.common.ui,2.10.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.converter,2.11.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.databinding.edit,1.4.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.databinding,1.4.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.ecore.edit,2.9.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.ecore.editor,2.11.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.ecore,2.11.0.v20150512-0501
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.edit,2.11.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.edit.ui,2.11.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf,2.11.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.mapping.ecore.editor,2.10.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.mapping.ecore,2.9.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.mapping,2.9.0.v20150601-0402
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.mapping.ui,2.9.0.v20150601-0402

**Comment by amiga23** [comment]
For me it works fine now in Eclipse Mars. I do use the RCP/RAP Version as base. You have to install the bndtools from the repository provided in the tutorial. bndtools from Eclipse Marketplace are toooooo old. Also I am using Java 8, did not test with older versions. If you are behind a proxy that may also be a problem.

**Comment by pkriens** [comment]
The errors indicate Eclipse problems, bndtools has nothing to do with EMF etc. You might want to try a freshly downloaded Eclipse?

Kind regards,

    Peter Kriens

**Comment by radvieira** [comment]
Thanks I'll have a closer look.

**Comment by lkluge** [comment]
I get the same Problem.
Unable to resolve <<INITIAL>> version=null:
   missing requirement Require[osgi.identity]{}{filter=(osgi.identity=com.acme.prime.eval.provider)} [caused by:
   Unable to resolve com.acme.prime.eval.provider version=1.0.0.201507151037:
   missing requirement Require[osgi.extender]{}{filter=(&(osgi.extender=osgi.ds)(version>=1.0.0)(!(version>=2.0.0))), effective=active}]

i don't find the BND Bundle Path any hind that the "*.ds" bundle is available ?

Is that the Problem ??

**Comment by pkriens** [comment]
I assume this is a different problem?

In your case it sounds like you got hit by a bug with the change in extender name. I am pretty sure that the latest workspace on https://github.com/osgi/workspace <https://github.com/osgi/workspace> is set up correctly. You might want to delete your cnf/cache directory, restart Eclipse, and then try again. I think you’re probably using an old indexer.

Kind regards,

	Peter Kriens

**Comment by lkluge** [comment]
Sorry Peter,
i have create the Example from scratch.
New checkout from git and new workspace.
And i get the same Error above.
*************************************
Unable to resolve <<INITIAL>> version=null:
   missing requirement Require[osgi.identity]{}{filter=(osgi.identity=com.acme.prime.eval.provider)} [caused by:
   Unable to resolve com.acme.prime.eval.provider version=1.0.0.201507152000:
   missing requirement Require[osgi.extender]{}{filter=(&(osgi.extender=osgi.ds)(version>=1.0.0)(!(version>=2.0.0))), effective=active}]
***************************************

**Comment by lkluge** [comment]
Now i little Step forward.
I can start the the application BUT i don't get the console

**Comment by pkriens** [comment]
If you share your workspace on github then I can take a look. Please also specify what your environment is.

Kind regards,

	Peter Kriens

**Comment by lkluge** [comment]
Hi Peter,
to prove the Workspace must i create a new Branch from your Git Repository or must i create a new Git Repository, what is the best solution for you ?


my Environment is
Mac OS X 10.10.4 (14E46)

Eclipse IDE for Java Developers
Version: Mars Release (4.5.0)
Build id: 20150621-1200

Bndtools	2.4.1.REL-20150116-150145-g75d944b

Oracle Java SE 8 [1.8.0_51]


I have check and test also with WIndows 7.1

here i have the Problem that the Resolve Button in Run Requirements (before run the OSGI Shell)
http://enroute.osgi.org/tutorial_base/400-run.html <http://enroute.osgi.org/tutorial_base/400-run.html>
the Message Box Resolving is popup but it will never close.

Eclipse IDE for Java Developers
Version: Mars Release (4.5.0)
Build id: 20150621-1200

Bndtools	3.0.0.DEV-20150722-1703122-gf6e9c01

Oracle Java SE 8 [1.8.0_51]


Mit freundlichen Grüßen

Lothar Kluge

Sie können verschlüsselte Mail zusenden.
Abfrage mit UserId Lothar Kluge bei dem Keyserver
http://pgp.mit.edu

Mobile 0177 3402118

WICHTIGER HINWEIS:
Diese Email ist vertraulich und nur für den beabsichtigten Empfänger bestimmt. Der unberechtigte Zugriff, die Freigabe, Kopie oder Verteilung ist strikt untersagt und kann gegen bestehende Gesetze verstoßen. Wenn sie diese Nachricht irrtümlich erhalten oder sonstige Probleme damit haben, bitten wir um sofortige Benachrichtigung des Absenders.

IMPORTANT NOTICE:
This email is confidential and is for the intended recipient only. The unauthorized access, disclosure, copying or distribution is strictly prohibited and may be a criminal offence. If you have received this message in error or if there are any problems please notify the originator immediately.










> Am 21.07.2015 um 08:52 schrieb Peter Kriens <notifications@github.com>:
> 
> If you share your workspace on github then I can take a look. Please also specify what your environment is.
> 
> Kind regards,
> 
> Peter Kriens
> 
>

**Comment by lkluge** [comment]
Hi Peter,
for the Mac Problem i have create a Public Git

https://github.com/lkluge/enrouteErrorWorkspace.git <https://github.com/lkluge/enrouteErrorWorkspace.git>


Mit freundlichen Grüßen

Lothar Kluge

Sie können verschlüsselte Mail zusenden.
Abfrage mit UserId Lothar Kluge bei dem Keyserver
http://pgp.mit.edu

Mobile 0177 3402118

WICHTIGER HINWEIS:
Diese Email ist vertraulich und nur für den beabsichtigten Empfänger bestimmt. Der unberechtigte Zugriff, die Freigabe, Kopie oder Verteilung ist strikt untersagt und kann gegen bestehende Gesetze verstoßen. Wenn sie diese Nachricht irrtümlich erhalten oder sonstige Probleme damit haben, bitten wir um sofortige Benachrichtigung des Absenders.

IMPORTANT NOTICE:
This email is confidential and is for the intended recipient only. The unauthorized access, disclosure, copying or distribution is strictly prohibited and may be a criminal offence. If you have received this message in error or if there are any problems please notify the originator immediately.










> Am 21.07.2015 um 08:52 schrieb Peter Kriens <notifications@github.com>:
> 
> If you share your workspace on github then I can take a look. Please also specify what your environment is.
> 
> Kind regards,
> 
> Peter Kriens
> 
>

**Comment by lkluge** [comment]
Hi Peter,
today i have update the Windows System Eclipse System.
Now i have the BNDTools 3.0.0. DEV-20150731-131340-g0880747.
But it does not help, the Resolve Button oben the Message Box and then the Message Box will never close.

Do you working on this Problem ?

Do you need more Information ?

I have make git repository for you with the Mac Problem.
Did you work on it ?



Eclipse IDE for Java Developers
Version: Mars Release (4.5.0)
Build id: 20150621-1200

Bndtools	DEV-20150731-131340-g0880747

Oracle Java SE 8 [1.8.0_51]




Mit freundlichen Grüßen

Lothar Kluge

Sie können verschlüsselte Mail zusenden.
Abfrage mit UserId Lothar Kluge bei dem Keyserver
http://pgp.mit.edu

Mobile 0177 3402118

WICHTIGER HINWEIS:
Diese Email ist vertraulich und nur für den beabsichtigten Empfänger bestimmt. Der unberechtigte Zugriff, die Freigabe, Kopie oder Verteilung ist strikt untersagt und kann gegen bestehende Gesetze verstoßen. Wenn sie diese Nachricht irrtümlich erhalten oder sonstige Probleme damit haben, bitten wir um sofortige Benachrichtigung des Absenders.

IMPORTANT NOTICE:
This email is confidential and is for the intended recipient only. The unauthorized access, disclosure, copying or distribution is strictly prohibited and may be a criminal offence. If you have received this message in error or if there are any problems please notify the originator immediately.
