### ISSUE TITLE
Dragging the JPM4J to Build tab is not working

### ISSUE THREAD

**Issue by daghanacay** [bndtools/bndtools#1095]
1- in a clear repository view (or one without Parsii initilly available) 
2- drag the Psrsii 1.1.0 to Build Path (from external browser imp4j web site
3- Screenshot 1 appears
4- drag the 1.1.0 to Repository View under JPM4J (from external browser)
- you will see the jar under repo view with an ! (means it is not a bundle but may be a better symbol can be used since this looks like an error)

5- Later drag the 1.1.0 FROM external browser TO Build path
6- screenshot 2 appears

![screenshot1directlydraggingtobuildpath](https://cloud.githubusercontent.com/assets/7053998/7043235/76281aa2-de2b-11e4-9ca3-217db3a26d30.png)
![screenshot2afteraddingtorepositoriesseconddrag](https://cloud.githubusercontent.com/assets/7053998/7043236/762dc1a0-de2b-11e4-9051-81fd80fbc092.png)

**Comment by amiga23** [comment]
Does also not work for me. Neither on Linux nor an Mac OS

**Comment by pkriens** [comment]
Could you verify that in the first case, it actually works if you select the popup window?

**Comment by daghanacay** [comment]
I have clicked on the pop up window, it disabled and showed "querying dependencies" at the bottom and after the process finished the pop up was still empty.

I think to problem is that if the library is not already under JPM4J Repository, dragging from the browser does not work.

Please try this,

1-delete Parsii from all the repositories under "Repositories" view in your 
2- drag the Parsii form JPM4J web site to "Build Path" section of bnd.bnd view
3- Click on the pop up

the pop up is empty

if you do the steps 2 and 3 while Parsii is in the "Repositories" view then dragging from JPM4J web site to "Build Path" section of bnd.bnd works as expected.

**Comment by pkriens** [comment]
This should be fixed in bnd by https://github.com/pkriens/bnd/commit/66a71ed6dcfe29ca1051c65434a3183e78ecf676
