### ISSUE TITLE
New builder breaks annotation processor plugin

### ISSUE THREAD

**Issue by paulbakker** [bndtools/bndtools#1097]
The new builder seems to have some differences in reporting to bnd plugins.

The Felix Dependency Manager annotation processor parses the following type of annotations:
```
@Component(provides = { java.lang.Object.class })
```

In previous versions of Bndtools, the value of the "provides" property would be ```Ljava/lang/Object;```. In the latest master it's ```java.lang.Object```.

This is not necessarily wrong, but it's clearly different. It breaks the Dependency Manager plugin, and might break other plugins as well. Is this a known API change, that plugins should change to?

**Comment by bjhargrave** [comment]
This is due to a bnd (not bndtools builder) change by David Jenkcs.

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/pull/877

**Comment by paulbakker** [comment]
Thanks @bjhargrave. I guess this is a change that we want, and not considered a bug? 
In that case it's at least something for the release notes.

**Comment by bjhargrave** [comment]
> I guess this is a change that we want, and not considered a bug? 

Yes. 

> In that case it's at least something for the release notes.

@pkriens started them here https://github.com/bndtools/bndtools/wiki/Changes-in-3.0.0

**Comment by paulbakker** [comment]
Added a note to the page, and closing this issue.
