### ISSUE TITLE
Deleting a bnd project does not remove it from the Workspace index

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1100]
1. Resolve a bndrun such that a workspace bundle is included in the resolution result.
2. Delete the project for that workspace bundle, making sure that the physical files are deleted as well.
3. Resolve the bndrun again... the resolution result still references the deleted bundle. It will have the path <project name>/generated/bundle.jar.

**Comment by pkriens** [comment]
What is your time frame? Would be nice to get this fixed on 3.0

**Comment by pkriens** [comment]
Neil?

**Comment by JFingerle** [comment]
This can be fixed by refreshing the repositories (especially the WorkspaceR5Repository) before the resolution starts. See my commit dca93c2.

**Comment by njbartlett** [comment]
Fixed in 5cb1b9e8629b20fa3fb9cedc6826001de0cd0f4a
