### ISSUE TITLE
Warning marker when using Bndtools with m2e

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1102]
If you use bndtools and m2e together, you get the following warning marker:

`
The .classpath contains an unknown container: org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER
`

This prevents me from creating warning-free projects.

**Comment by bjhargrave** [comment]
How does your offline build work and keep in sync with Eclipse? bndtools assumes the bnd workspace model (all projects are peers and there is a cnf project) while maven does not. bndtools is trying to ensure off-line builds work. And the bnd offline build (e.g. bnd's gradle plugin) has no idea how to set up the class path for compilations when classpath containers other than bndtools' container is used. 

Perhaps this warning needs to be configurable in some way.

**Comment by BryanHunt** [comment]
We are using the bbd-maven-plugin for Jenkins builds:

```xml
<!-- Enable building OSGi bundle -->

<plugin>
	<artifactId>maven-jar-plugin</artifactId>
	<configuration>
		<archive>
			<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
		</archive>
	</configuration>
</plugin>

<plugin>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>bnd-maven-plugin</artifactId>
</plugin>
```

**Comment by bjhargrave** [comment]
So maven is in charge of the build and you use m2e to provide Eclipse fidelity. 

So what do you use bndtools for? Just the bnd file editor?

Do you have the bndtools nature and builder configured in your .project files? I must assume you do not have both m2e and bndtools builders attempting to build each project in eclipse.

Perhaps the answer here is for bndtools to check these warnings only when the project has the bndtools nature. Then if you are not using bndtools to build the project, then we don't check for fidelity with off line build.

**Comment by BryanHunt** [comment]
Right now, I'm letting Bndtools do the local Eclipse build.  We do have both the Bndtools and Maven natures enabled on the project.  I believe m2e will only build when you run one of the launchers and just let's Eclipse do the local build.  I suppose we could get into trouble here, but I need to test the maven build, and I'd like to use Bndtools once we get the integration tests moved to a bundle.  If there is a better way to set this up, I'm open to trying something different.  I'd like to switch to gradle, but we have too much legacy code using Maven and other priorities.

**Comment by bjhargrave** [comment]
Your setup sounds like a fidelity nightmare :-) bnd-maven-plugin uses a Builder that is not aware of the bnd workspace model while bndtools uses a ProjectBuilder that is dependent on the bnd workspace model (and cnf project). You are using a different build model in eclipse than in the offline maven build.

bndtools only checks the build fidelity issues on projects using the bndtools builder (the validator runs as part of the builder). So I don't see that bndtools is wrong in reporting the warning here. Your setup deserves a warning! :-)

**Comment by pkriens** [comment]
We could add a peference to ignore those warnings

**Comment by bjhargrave** [comment]
Bndtools now has an m2e feature for using certain Bndtools capabilities with m2e projects.
