### ISSUE TITLE
Missing/Empty Bnd Bundle Path

### ISSUE THREAD

**Issue by JSlain** [bndtools/bndtools#1106]
Don't know what happened, but my "Bnd Bundle Path" appears empty when i look at my project's "Java Build Path", doesn't appears at all in the Project or Package views, and finally, since my build path is incomplete, my code doesn't compile...

I tried refresh, clean projects, i even deleted all eclipse files and recreate the eclipse project, in a new workspace. Same result. There's no errors in the Error view.

Here's my bnd.bnd
Any idea of what's wrong?

    -buildpath:  \
    osgi.core,\
    osgi.cmpn,\
    biz.aQute.bnd.annotation,\
    ${junit},\
    org.mockito.mockito-all
    Bundle-Version: 0.0.0.${tstamp}
    Private-Package:  \
    org.test.feedbacks.impl
    Service-Component:  \
    *

**Comment by JSlain** [comment]
I realized it happens when I checkout my project from scratch. Eclipse files aren't versionned (.project, .classpath, .settings/) and there's no way of importing an existing Bndtools project (like importing an existing Maven project works).

Creating a new project in the existing sources folder causes this problem.
The only way i've been able to work on my project again is by creating a new bndtools project, copy my src and test, and modifying the generated bnd.bnd file.

Eclipse Luna 64bits
Kubuntu 64bits

**Comment by bjhargrave** [comment]
Normally people put the eclipse project metadata (.project, .classpath, .settings/) under version control.

https://github.com/bndtools/bndtools/issues/916 has requested the ability for bndtools to generate these files when importing a bnd project that does not have them.

I am closing this issue since #916 already covers this.
