### ISSUE TITLE
Canout resolve whiteboard

### ISSUE THREAD

**Issue by TFreitasmic** [bndtools/bndtools#1107]
Hello,
i'm devoloping an application to work with the whiteboard, but when I try to resolve on the eclipse I get a error resolving message sayng that "org.osgi.bundle.repoindex.lib 1.0.4.201310201020 requires Import-Package org.osgi.service.log [1.3.0, 2.0.0)"
I'm i've tryed with *felix.whiteboard" 2.2.2, 2.3.0 and 2.3.2.
Best Regards,
Tiago Freitas

**Comment by bjhargrave** [comment]
What is the problem in bndtools that you wish to raise? Your description sound like a problem in your application that you developed rather than a problem in bndtools.

**Comment by TFreitasmic** [comment]
My app is not runing, I'm just running felix's bundles:
	osgi.identity;filter:='(osgi.identity=org.apache.felix.bundlerepository)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.command)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.runtime)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.shell)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.http.jetty)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.log)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.scr)'
when I add the whiteboard bundle, I recieved the error i've described above.
I'm not saying that is a bndtools problem, And probably It's some wrong bundle\version, i'm just asking for some help.
Best Regards,
Tiago Freitas

**Comment by bjhargrave** [comment]
You should probably ask your question then in the bndtools-users mail list, see https://github.com/bndtools/bndtools#feedback, rather than open an issue which is for bugs in bndtools.

**Comment by TFreitasmic** [comment]
Oh ok.. I'm very sorry!
Thanks for the help.
Tiago
