### ISSUE TITLE
Eclipse throws ArrayIndexOutOfBoundsException due to invalid AccessRules

### ISSUE THREAD

**Issue by marcdejonge** [bndtools/bndtools#1108]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=465640

See this piece of code: https://github.com/bndtools/bndtools/blob/master/bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java#L529

I've found out that when I use a project dependency (version=project) that it adds an AccessRule to the JDT with an empty path. This causes exceptions in eclipse, so it is very annoying. Since I've no idea what this code should do, I've got no idea how it should be fixed.

What I do see when debugging to that line that oldAccessPattern is empty and thus it will translate into a list of a single empty string, which will be added as an AccessRule.

**Comment by bjhargrave** [comment]
BTW, Thanks for debugging this down to the root problem! That really made is easy for me to fix.
