### ISSUE TITLE
Bndtools error markers

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bndtools#1113]
Some of the DS error markers aren't working properly e.g.

* Using the standard @Activate on an invalid method such as void start(URL url)
* Using the standard @Reference inside a bnd annotated component

These should both appear in the DS component source as red error markers, but instead appear against the bnd file. Other markers are working fine - it seems as though bnd is losing the location details for some of the errors.

**Comment by pkriens** [comment]
The problem was that these annotations never had the proper details to be properly located.

I've done a number of them but it could use a proper vetting. Is in commit 8d34f68e00 ([error] Bndtools error markers #1113) of the bnd project
