### ISSUE TITLE
templates: ${junit} should be placed on -testpath

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1117]

**Comment by pkriens** [comment]
The Junit launcher needs to be reworked since it binds people to a specific JUnit version. In the new architecture, the JUnit runner must run as a bundle while it gets the JUnit classes from imports.

**Comment by fhuberts** [comment]
${junit} has nothing to do with the junit launcher, it's for regular junit tests.
please re-open

**Comment by fhuberts** [comment]
please re-open
