### ISSUE TITLE
Custom Run Configuration Template

### ISSUE THREAD

**Issue by alexweirig** [bndtools/bndtools#1122]
Hello,

I couldn't find anything about this topic. I'm trying to work on an OSGi project with bndtools (latest version) in Eclipse (latest version).

Currently I'm aiming to use Apache Karaf 4 as target runtime. Unfortunately, in bndtools I can't find a way to specify a Run Configuration that matches the bundle versions available in Karaf 4, e.g. Felix 5, Jetty 9 etc.
There is only felix 4, jetty 7 available from the standard configurations.

I must probably be missing something obvious but how can I create a Run Configuration Template that gets close to my target runtime environment. The documentation doesn't have anything on this topic either. But since there is an "Empty" option I guess that it must be possible to create a custom configuration?

Many thanks in advance for your help

Alex

**Comment by bjhargrave** [comment]
I don't see a bug reported here. This seems more like a usage question that should be in the <bndtools-users@googlegroups.com> mail list.

**Comment by alexweirig** [comment]
Hello,

you're right. Sorry for this.

Alex
