### ISSUE TITLE
"New Bnd OSGi Project" wizard doesn't behave correctly

### ISSUE THREAD

**Issue by nport** [bndtools/bndtools#1123]
Bnd Tools provide a wizard for creating new Bnd Projects. This wizard seems to correctly handle modifications issued after pressing the "Back" button.

In particular:

1. File -> New ... -> Bndtools OSGi Project, the new project wizard appears
2. set the Project Name and press "Next"
3. Select "Empty Project" and press "Next"
4. Press "Back"
5. Press "Back"
6. Select "maven" project layout
7. Press "Next"
8. Press "Next"

You could see that the project layout shown is still bnd-like and not "maven-like".

**Comment by bjhargrave** [comment]
#960 proposes removing the project layout from the project wizard

**Comment by nport** [comment]
Sorry, I did a mistake in the second sentence. My intention was to say:

"This wizard *doesn't* seem to correctly handle modifications issued after pressing the "Back" button."

**Comment by nport** [comment]
BJ, sorry but this is a more general issue of the wizard (I used a generic title), since it happens also on the "Use Execution Environment JRE" field. Basically the bug relates to te fact that  the wizard doesn't remember the changes issued using the back button, as described above.
