### ISSUE TITLE
"New Bnd OSGi Project" wizard creates projects that don't compile.

### ISSUE THREAD

**Issue by nport** [bndtools/bndtools#1128]
This is *just an example of the overall issue*. We suppose to have a cnf project already created in the workspace.

1. Put the following lines in the build.bnd files located in the cnf directory to avoid each project to specify the same configurations to change the default settings (this is because you wants a maven project layout):

   src:                   src/main/java 
   bin:                   target/classes
   testsrc:               src/test/java
   testbin:               target/test-classes

2. I open the "New Bnd OSGi Project" wizard.
3. Put a project name and press "Next".
4. Select a template project and press "Next"
5 Press "Finish".

The newly created project does not compile. This could be a little bit confusing to bndtools newbies (including me :-)).

The flaw comes by the fact that the wizard doesn't create the correct project layout and .classpath file content. The wizard  should take into account the build.bnd file when it creates the  layout or override the build.bnd file settings by putting the proper directives (for overriding the others) in the newly created project bnd.bnd file.

OS: Windows 7
BndTools version: 2.4.1-REL 
Eclipse Luna

**Comment by pkriens** [comment]
I do agree ... matter of time

**Comment by pkriens** [comment]
Likely fixed ... can you test and reopen if not?

**Comment by nport** [comment]
Sorry Peter for the delay. Tried right now. I tried to create an .api project. The specified directories are created in the filesystem, but not used at all. I would say that now the project is created and compiles, but it is not using those folders for the source files and the .class files!

**Comment by pkriens** [comment]
Can you send a zip of the workspace because this sounds extremely unlikely ... And which template did you use?
