### ISSUE TITLE
Simplify developping Eclipse Plugin?

### ISSUE THREAD

**Issue by JSlain** [bndtools/bndtools#1130]
This is not a bug, but rather a question.

An Eclipse plugin is (almost) simply a bundle with an additional plugin.xml file.

How can we launch a new Eclipse application from a .bndrun file?
I checkoutted bndtools sources, and it works out-of-the-box! My project is currently using enRoute, and i'm not able to adapt its /cnf folder, and bndrun file so it starts Eclipse.

Is there a documentation about how the /cnf folder really works? I see an folder called 'eclipse' and another one 'eclipse-3.5.2', but i can't find where it's being linked.

Any hint?

**Comment by bjhargrave** [comment]
Issues are for defects, not usage questions. Please direct your usage question to <bndtools-users@googlegroups.com>. Thanks.
