### ISSUE TITLE
Drag and drop not working from external JPM4J browser

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bndtools#1135]
With the latest release version (2.4.1.REL-20150116-150145-g75d944b) *and* the latest development version (3.0.0.DEV-20150727-182211-gb1d2af4) of bndtools, no drag and drop functionality is available for adding bundles to the repository from JPM4J using Windows and Eclipse Mars. The icon simply stays as the little "forbidden" symbol, whether over the build path or repositories view, and then nothing happens on release. (This differentiates the issue from #1095, where at least the UI would recognise that a drag and drop capability exists at the drop point.)

This happens for both Firefox and Chrome. Unfortunately neither version of the internal JPM tab is working for me either so I can't test whether drag and drop is working from them - in both cases the tab is empty white.

Is the only work around to this to add entries manually to distro.json?

**Comment by eliasvasylenko** [comment]
The exact same project setup works in Ubuntu/Luna (though eclipse JPM views are still missing). I could try the combinations Windows/Luna and Ubuntu/Mars too if that would be helpful.

**Comment by gamerson** [comment]
Hello @eliasvasylenko for Ubuntu the JPM views don't work because of problems with embedded SWT browsers are finicky.  If you could try combinations of Windows/Luna that would be helpful to find out if it is a SWT/DND problem on Windows.

**Comment by seanbright** [comment]
Oddly, I'm on Windows 10 with Mars and I do not experience this issue.

**Comment by gamerson** [comment]
Thanks @seanbright  for the note, @eliasvasylenko  what version of windows are you running?

**Comment by eliasvasylenko** [comment]
Hi, sorry for the late response, I've been out of the office for a few days. Also, this was a false alarm as it turns out, the issue was with Eclipse and not with Bndtools specifically. Thanks for the help, apologies for the the time wasted.

**Comment by gamerson** [comment]
Glad its working thanks for following up @eliasvasylenko
