### ISSUE TITLE
export: lots of \\\n in launch.properties

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1144]
Press the 'Export' button on a bndrun file, export to a folder.
The launch.properties files has lots of ```\\\n```.
Seem some wrong escaping is done.
The file is also quite different from what is produced by a ```gradle export```.
Exporting to a jar seems to work ok.

This is on latest bndtools

**Comment by pkriens** [comment]
Are there problems with launching?

**Comment by pkriens** [comment]
We now use the identical code that is used for the executable JAR. We just expand it.

Fixed in RC2
