### ISSUE TITLE
Kepler 4.3.2 Update: Missing bundle org.eclipse.ui.win32

### ISSUE THREAD

**Issue by seanbright** [bndtools/bndtools#1151]
The ``.bndrun`` files for Windows in the ``bndtools.core`` project reference ``org.eclipse.ui.win32`` in ``-runbundles``, but that bundle isn't indexed in the eclipse-repo here: https://dl.bintray.com/bndtools/eclipse-repo/4.3.2/index.xml.gz

**Comment by bjhargrave** [comment]
I uploaded the ui.win32 file and an updated index to bintray.

**Comment by seanbright** [comment]
What took so long?

(Thanks!)
