### ISSUE TITLE
Refreshing of repositories can take time but its done in the foreground

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1160]
We should refresh repos in the background

**Comment by njbartlett** [comment]
Are you talking about the Refresh Repositories menu entry available from the main menu bar? Or the refresh button in the Repositories view?

**Comment by pkriens** [comment]
Is there a difference? Currently when you refresh repos you get a beach ball, it would be nice if this was hidden and visible in the progress view.

**Comment by njbartlett** [comment]
I don't get a beachball... and checking the code, both operations are already done off the UI thread.

**Comment by pkriens** [comment]
Ok, then I will check again when it happens. So we can close this?

**Comment by njbartlett** [comment]
If there's a real problem I want it fixed, it's just that looking at the code I don't see how we can be locking up the UI. Do I need a particularly big & remote repo?

**Comment by lostiniceland** [comment]
Not sure if this is the right issue, but when working with a JPM4J repository, there is no feedback about background-tasks and my UI looks for a couple of seconds when triggering "Download All" or "Delete Cache".

Should I open a separate issue for JPM4J? I would be willing to work on a PR.

**Comment by lostiniceland** [comment]
When triggering a possible long running task in a JPM-Repository (for example, "Delete Cache" or "Download All") there is no visible indication about the job (wether completed or not).

After having a look at Actionable, the reason seems that the map with actions is causing this behaviour: the execution is wrapped within a runnable wich is just executed within an Action (see RepositoriesView line 615ff)

I dont recall the Eclipse API at the moment, but as far as I remember Actions are not added to the ProgressMonitor/Job-API. A solution for this probably forces a change in the Actionable-interface (passing a callback to handle progress or at least running/done state).

**Comment by pkriens** [comment]
The JPM repository is agnostic of Eclipse (it also needs to run outside Eclipse) so it does not use any of its API. However, you are fully right that it should act as a better citizen. Just looking for someone to spent some cycles on :-( I've no time at the moment to work on this though I could help on the bnd side if this is necessary

**Comment by lostiniceland** [comment]
Iwas actually thinking of spending some time on this issue. So if nobody from the experts has time I will try my best

**Comment by pkriens** [comment]
Great!

**Comment by lostiniceland** [comment]
Created [PR 1222](https://github.com/bndtools/bndtools/pull/1222)

I think there is not much more we can do on Eclipse/Bndtools side. I just wrapped the Runnable in a Eclipse-Job and made sure that it doesnt conflict with the UI-Thread when dealing with JFace/SWT.
If we need more visual feedback, like a updating progressbar, the interface on bnd-side must be changed.

**Comment by pkriens** [comment]
Looks good to me, will merge when others have had a look.

There is a aQute.bnd.service.RepositoryListenerPlugin that you might want to take advantage of. Repositories are supposed to update this plugin when adding entries.

**Comment by lostiniceland** [comment]
I will have a look at the RepositoryListenerPlugin and update the code accordingly.
