### ISSUE TITLE
can't Add bundles to "Local" repository.

### ISSUE THREAD

**Issue by pderop** [bndtools/bndtools#1164]
I'm trying out the just released BndTools 3.0.0.RC2, and while playing with it, I saw that I can't add and drag and drop anymore some bundles to the "Local" repository.

In the previous 2.4.1 release, there was a button in the Repositories window which was called "Add Bundles to Repository". Now, withe the 3.0.0 RC2 (and also with the previous RC1), I don't see anymore this button.

I'm using latest Eclipse Mars.

Is this a regression ? or is there now another way to add bundles to the local repository ?

thanks

with regards;
/Pierre

**Comment by pkriens** [comment]
Hmm, not good. You can of course always drop JAR urls on the repo

**Comment by pkriens** [comment]
Can you send the configuration of your "Local" repo?

**Comment by bjhargrave** [comment]
@gamerson to restore Add button removed by https://github.com/bndtools/bndtools/commit/ca30dc6a872b6d44d9c24dbc44f58f485d0e62d8.

**Comment by pderop** [comment]
thanks, it works.

/Pierre
