### ISSUE TITLE
Cannot open Eclipse preferences in bndtools debug

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1167]
When debugging bndtools from itself, the Eclipse Preferences dialog refuses to open.

**Comment by gamerson** [comment]
stacktraces or errors in error log?  Wondering if we are starting enough bundles in the bndrun?

**Comment by njbartlett** [comment]
No stacktraces or errors that I could see. I agree the problem is probably a missing bundle... just need to find which one to add.
