### ISSUE TITLE
Built-version of feature.xml doesn't contain correct version numbers

### ISSUE THREAD

**Issue by gamerson** [bndtools/bndtools#1170]
See here: https://bndtools.ci.cloudbees.com/job/bndtools.master/lastSuccessfulBuild/artifact/build/generated/p2/features/

download the feature.jar, extract it, open the feature.xml and look at the <plugin> elements, they have versions that look like "0.0.0"

```
<plugin
         id="biz.aQute.bndlib"
         download-size="0"
         install-size="0"
         version="0.0.0"
         unpack="false"/>
   
   <plugin
         id="biz.aQute.repository"
         download-size="0"
         install-size="0"
         version="0.0.0"
         unpack="false"/>

   <plugin
         id="biz.aQute.resolve"
         download-size="0"
         install-size="0"
         version="0.0.0"
         unpack="false"/>

...etc...
```

These incorrect versions will break for people that are using the bndtools repo as a p2 repository for downstream plugins (like Liferay IDE) who also want to include some of the plugins referenced by that feature in their own repositories.

**Comment by bjhargrave** [comment]
I looked back at older releases of bndtools and the versions are 0.0.0 also. 0.0.0 is interpreted to mean latest version. I am not sure what the issue you refer to is, but it would be a significant change to the build to use PDE to build the feature rather than our hand-crafted feature.

If you are interested in doing this for 3.1, please have a go!

**Comment by bjhargrave** [comment]
FYI, you probably should not use the cloudbees URL for any production use. You can use https://dl.bintray.com/bndtools/bndtools/3.0.0/ as the official p2 update site for 3.0.

**Comment by bjhargrave** [comment]
Closing. Submit a PR if you have a solution. Thanks.
