### ISSUE TITLE
bndtools 3: error resolving  execution environment capalities like javax.xml.parsers 

### ISSUE THREAD

**Issue by hfranz-gebit** [bndtools/bndtools#1177]
Try this:

Create an empty OSGi project( Eclipe 4.4SR2, BNDTools 3) .

Create a new run descriptor.

Get the bundle com.springsource.org.apache.tools.ant (1.8.1) from springsource.com into your local repo somehow.

Add it to the run requirements.
Klick Resolve

=>
org.osgi.service.resolver.ResolutionException: Unable to resolve <<INITIAL>> version=null: missing requirement com.springsource.org.apache.tools.ant
->  Unable to resolve com.springsource.org.apache.tools.ant version=1.8.1: missing requirement javax.xml.parsers; version=0.0.0]

This is provided by Java1.7.

Note: Resolve works fine with bndtools 2.4.

**Comment by njbartlett** [comment]
I can reproduce this. The resolution *does* work if you add:

	-runsystempackages: \
		javax.xml.parsers;version=0,\
		javax.xml.transform;version=0,\
		javax.xml.transform.sax;version=0,\
		org.w3c.dom; version=0,\
		org.xml.sax; version=0,\
		org.xml.sax.helpers; version=0

But of course this shouldn't be necessary. It doesn't work if the "version=0" is left out.

I'd like to fix this as a priority for 3.0.1. It seems like something has gone seriously wrong in the resolver...  we can't see any of the packages from the Execution Environment??

**Comment by pkriens** [comment]
What framework is this resolved against? I.e. what is the full setup?

**Comment by njbartlett** [comment]
@pkriens I used Felix 5.0.1.

I have a standalone dir that reproduces the issue (requires the new standalone work in 3.1). Trying to work out how to upload to this issue... in the meantime I'll Skype it to you.

**Comment by njbartlett** [comment]
Gist that reproduces the error: https://gist.github.com/njbartlett/51652c98d2b84eccbaee

(requires 3.1 master)

**Comment by njbartlett** [comment]
In `aQute.bnd.deployer.repository.CapabilityIndex#appendMatchingCapabilities`...  line 49, we find the capability from the EE but it doesn't have a version attribute. The filter from the requirement is `((&(osgi.wiring.package=javax.xml.parsers)(version>=0.0.0))` and this does not match an empty version attribute.

It seems to me we should be creating the EE capabilities with a version of 0 implicitly. Also the contents of -runsystempackages. I suspect we used to do this in 2.4 since the resolution worked, so I'm not sure when or why it changed.

**Comment by pkriens** [comment]
This code was changed because it had become very hard to understand the logic of what is going on. The division between the base class and the sub class had become unclear over time and it was not clear who owned what instance variable. It also suffered from doing functions inline instead of factoring them out to one place in bndlib. When adding the -distro instruction it became clear that it was long overdue for refactoring; I actually think it still did not go nearly far enough.

The only way to not end in a mess is to take the constant pain of refactoring.

**Comment by pkriens** [comment]
# Workaround for 1.7
-runsystempackages.bugfix = \
 javax.accessibility;version=0,\
 javax.activation;version=0,\
 javax.activity;version=0,\
 javax.annotation;version=0,\
 javax.annotation.processing;version=0,\
 javax.crypto;version=0,\
 javax.crypto.interfaces;version=0,\
 javax.crypto.spec;version=0,\
 javax.imageio;version=0,\
 javax.imageio.event;version=0,\
 javax.imageio.metadata;version=0,\
 javax.imageio.plugins.bmp;version=0,\
 javax.imageio.plugins.jpeg;version=0,\
 javax.imageio.spi;version=0,\
 javax.imageio.stream;version=0,\
 javax.jws;version=0,\
 javax.jws.soap;version=0,\
 javax.lang.model;version=0,\
 javax.lang.model.element;version=0,\
 javax.lang.model.type;version=0,\
 javax.lang.model.util;version=0,\
 javax.management;version=0,\
 javax.management.loading;version=0,\
 javax.management.modelmbean;version=0,\
 javax.management.monitor;version=0,\
 javax.management.openmbean;version=0,\
 javax.management.relation;version=0,\
 javax.management.remote;version=0,\
 javax.management.remote.rmi;version=0,\
 javax.management.timer;version=0,\
 javax.naming;version=0,\
 javax.naming.directory;version=0,\
 javax.naming.event;version=0,\
 javax.naming.ldap;version=0,\
 javax.naming.spi;version=0,\
 javax.net;version=0,\
 javax.net.ssl;version=0,\
 javax.print;version=0,\
 javax.print.attribute;version=0,\
 javax.print.attribute.standard;version=0,\
 javax.print.event;version=0,\
 javax.rmi;version=0,\
 javax.rmi.CORBA;version=0,\
 javax.rmi.ssl;version=0,\
 javax.script;version=0,\
 javax.security.auth;version=0,\
 javax.security.auth.callback;version=0,\
 javax.security.auth.kerberos;version=0,\
 javax.security.auth.login;version=0,\
 javax.security.auth.spi;version=0,\
 javax.security.auth.x500;version=0,\
 javax.security.cert;version=0,\
 javax.security.sasl;version=0,\
 javax.sound.midi;version=0,\
 javax.sound.midi.spi;version=0,\
 javax.sound.sampled;version=0,\
 javax.sound.sampled.spi;version=0,\
 javax.sql;version=0,\
 javax.sql.rowset;version=0,\
 javax.sql.rowset.serial;version=0,\
 javax.sql.rowset.spi;version=0,\
 javax.swing;version=0,\
 javax.swing.border;version=0,\
 javax.swing.colorchooser;version=0,\
 javax.swing.event;version=0,\
 javax.swing.filechooser;version=0,\
 javax.swing.plaf;version=0,\
 javax.swing.plaf.basic;version=0,\
 javax.swing.plaf.metal;version=0,\
 javax.swing.plaf.multi;version=0,\
 javax.swing.plaf.nimbus;version=0,\
 javax.swing.plaf.synth;version=0,\
 javax.swing.table;version=0,\
 javax.swing.text;version=0,\
 javax.swing.text.html;version=0,\
 javax.swing.text.html.parser;version=0,\
 javax.swing.text.rtf;version=0,\
 javax.swing.tree;version=0,\
 javax.swing.undo;version=0,\
 javax.tools;version=0,\
 javax.transaction;version=0,\
 javax.transaction.xa;version=0,\
 javax.xml;version=0,\
 javax.xml.bind;version=0,\
 javax.xml.bind.annotation;version=0,\
 javax.xml.bind.annotation.adapters;version=0,\
 javax.xml.bind.attachment;version=0,\
 javax.xml.bind.helpers;version=0,\
 javax.xml.bind.util;version=0,\
 javax.xml.crypto;version=0,\
 javax.xml.crypto.dom;version=0,\
 javax.xml.crypto.dsig;version=0,\
 javax.xml.crypto.dsig.dom;version=0,\
 javax.xml.crypto.dsig.keyinfo;version=0,\
 javax.xml.crypto.dsig.spec;version=0,\
 javax.xml.datatype;version=0,\
 javax.xml.namespace;version=0,\
 javax.xml.parsers;version=0,\
 javax.xml.soap;version=0,\
 javax.xml.stream;version=0,\
 javax.xml.stream.events;version=0,\
 javax.xml.stream.util;version=0,\
 javax.xml.transform;version=0,\
 javax.xml.transform.dom;version=0,\
 javax.xml.transform.sax;version=0,\
 javax.xml.transform.stax;version=0,\
 javax.xml.transform.stream;version=0,\
 javax.xml.validation;version=0,\
 javax.xml.ws;version=0,\
 javax.xml.ws.handler;version=0,\
 javax.xml.ws.handler.soap;version=0,\
 javax.xml.ws.http;version=0,\
 javax.xml.ws.soap;version=0,\
 javax.xml.ws.spi;version=0,\
 javax.xml.ws.spi.http;version=0,\
 javax.xml.ws.wsaddressing;version=0,\
 javax.xml.xpath;version=0,\
 org.ietf.jgss;version=0,\
 org.omg.CORBA;version=0,\
 org.omg.CORBA.DynAnyPackage;version=0,\
 org.omg.CORBA.ORBPackage;version=0,\
 org.omg.CORBA.TypeCodePackage;version=0,\
 org.omg.CORBA.portable;version=0,\
 org.omg.CORBA_2_3;version=0,\
 org.omg.CORBA_2_3.portable;version=0,\
 org.omg.CosNaming;version=0,\
 org.omg.CosNaming.NamingContextExtPackage;version=0,\
 org.omg.CosNaming.NamingContextPackage;version=0,\
 org.omg.Dynamic;version=0,\
 org.omg.DynamicAny;version=0,\
 org.omg.DynamicAny.DynAnyFactoryPackage;version=0,\
 org.omg.DynamicAny.DynAnyPackage;version=0,\
 org.omg.IOP;version=0,\
 org.omg.IOP.CodecFactoryPackage;version=0,\
 org.omg.IOP.CodecPackage;version=0,\
 org.omg.Messaging;version=0,\
 org.omg.PortableInterceptor;version=0,\
 org.omg.PortableInterceptor.ORBInitInfoPackage;version=0,\
 org.omg.PortableServer;version=0,\
 org.omg.PortableServer.CurrentPackage;version=0,\
 org.omg.PortableServer.POAManagerPackage;version=0,\
 org.omg.PortableServer.POAPackage;version=0,\
 org.omg.PortableServer.ServantLocatorPackage;version=0,\
 org.omg.PortableServer.portable;version=0,\
 org.omg.SendingContext;version=0,\
 org.omg.stub.java.rmi;version=0,\
 org.w3c.dom;version=0,\
 org.w3c.dom.bootstrap;version=0,\
 org.w3c.dom.css;version=0,\
 org.w3c.dom.events;version=0,\
 org.w3c.dom.html;version=0,\
 org.w3c.dom.ls;version=0,\
 org.w3c.dom.ranges;version=0,\
 org.w3c.dom.stylesheets;version=0,\
 org.w3c.dom.traversal;version=0,\
 org.w3c.dom.views;version=0,\
 org.w3c.dom.xpath;version=0,\
 org.xml.sax;version=0,\
 org.xml.sax.ext;version=0,\
 org.xml.sax.helpers;version=0

**Comment by pkriens** [comment]
# Java 1.8 bugfix
# Add this file to your cnf/ext directory
-runsystempackages.bugfix = \
 javax.annotation.processing;version=0,\
 javax.crypto;version=0,\
 javax.crypto.interfaces;version=0,\
 javax.crypto.spec;version=0,\
 javax.lang.model;version=0,\
 javax.lang.model.element;version=0,\
 javax.lang.model.type;version=0,\
 javax.lang.model.util;version=0,\
 javax.management;version=0,\
 javax.management.loading;version=0,\
 javax.management.modelmbean;version=0,\
 javax.management.monitor;version=0,\
 javax.management.openmbean;version=0,\
 javax.management.relation;version=0,\
 javax.management.remote;version=0,\
 javax.management.remote.rmi;version=0,\
 javax.management.timer;version=0,\
 javax.naming;version=0,\
 javax.naming.directory;version=0,\
 javax.naming.event;version=0,\
 javax.naming.ldap;version=0,\
 javax.naming.spi;version=0,\ javax.net;version=0,\
 javax.net.ssl;version=0,\
 javax.rmi.ssl;version=0,\
 javax.script;version=0,\
 javax.security.auth;version=0,\
 javax.security.auth.callback;version=0,\
 javax.security.auth.kerberos;version=0,\
 javax.security.auth.login;version=0,\
 javax.security.auth.spi;version=0,\
 javax.security.auth.x500;version=0,\
 javax.security.cert;version=0,\
 javax.security.sasl;version=0,\
 javax.sql;version=0,\
 javax.sql.rowset;version=0,\
 javax.sql.rowset.serial;version=0,\
 javax.sql.rowset.spi;version=0,\
 javax.tools;version=0,\
 javax.transaction;version=0,\
 javax.transaction.xa;version=0,\
 javax.xml;version=0,\
 javax.xml.crypto;version=0,\
 javax.xml.crypto.dom;version=0,\
 javax.xml.crypto.dsig;version=0,\
 javax.xml.crypto.dsig.dom;version=0,\
 javax.xml.crypto.dsig.keyinfo;version=0,\
 javax.xml.crypto.dsig.spec;version=0,\
 javax.xml.datatype;version=0,\
 javax.xml.namespace;version=0,\
 javax.xml.parsers;version=0,\
 javax.xml.stream;version=0,\
 javax.xml.stream.events;version=0,\
 javax.xml.stream.util;version=0,\
 javax.xml.transform;version=0,\
 javax.xml.transform.dom;version=0,\
 javax.xml.transform.sax;version=0,\
 javax.xml.transform.stax;version=0,\
 javax.xml.transform.stream;version=0,\
 javax.xml.validation;version=0,\
 javax.xml.xpath;version=0,\
 org.ietf.jgss;version=0,\
 org.w3c.dom;version=0,\
 org.w3c.dom.bootstrap;version=0,\
 org.w3c.dom.events;version=0,\
 org.w3c.dom.ls;version=0,\
 org.xml.sax;version=0,\
 org.xml.sax.ext;version=0,\
 org.xml.sax.helpers;version=0
