### ISSUE TITLE
NoSuchMethodError: bndtools.central.Central.getSourceFolderModel(Lorg/eclipse/core/resources/IProject;)Ljava/util/Collection;

### ISSUE THREAD

**Issue by The-Alchemist** [bndtools/bndtools#1180]
I don't even have any bndtools projects in my workspace, I just installed the plugins into my SpringToolSuite 3.7.0 based on Eclipse 4.5.

## Stack Trace
```
java.lang.NoSuchMethodError: bndtools.central.Central.getSourceFolderModel(Lorg/eclipse/core/resources/IProject;)Ljava/util/Collection;
	at org.bndtools.builder.decorator.ui.PackageDecorator.decorate(PackageDecorator.java:44)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:267)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:83)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:367)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:349)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:372)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:332)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

## Environment Details
* Mac OS X 10.10.5
* java version "1.8.0_60"
* Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
* Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
*   Bndtools 2.4.1.REL-20150116-150145-g75d944b	bndtools.main.feature.feature.group	Bndtools

**Comment by gamerson** [comment]
Which version of bndtools did you install?  If you installed the latest
(3.0.0) that stacktrace doesn't correspond to 3.0.  Did you perhaps have a
previous version installed (2.x) before you updated?

On Fri, Sep 18, 2015 at 6:32 AM, The Alchemist <notifications@github.com>
wrote:

> I don't even have any bndtools projects in my workspace, I just installed
> the plugins into my SpringToolSuite 3.7.0 based on Eclipse 4.5.
> Stack Trace
>
> java.lang.NoSuchMethodError: bndtools.central.Central.getSourceFolderModel(Lorg/eclipse/core/resources/IProject;)Ljava/util/Collection;
>     at org.bndtools.builder.decorator.ui.PackageDecorator.decorate(PackageDecorator.java:44)
>     at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:267)
>     at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:83)
>     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
>     at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:367)
>     at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:349)
>     at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:372)
>     at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:332)
>     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
>
> Environment Details
>
>    - Mac OS X 10.10.5
>    - java version "1.8.0_60"
>    - Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
>    - Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
>    - Bndtools 2.4.1.REL-20150116-150145-g75d944b
>    bndtools.main.feature.feature.group Bndtools
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bndtools/issues/1180>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by The-Alchemist** [comment]
Thanks, @gamerson .  I installed whatever came up in the Eclipse Marketplace, and I think you're right, I have 2.x.  Eclipse says:

``
  Bndtools	2.4.1.REL-20150116-150145-g75d944b	bndtools.main.feature.feature.group
```

**Comment by gamerson** [comment]
The Eclipse marketplace entry should have been updated to 3.0.0.  Perhaps
an uninstall and reinstall is in order for you.  Also I would try using the
updatesite below directly and avoiding marketplace for now:

https://dl.bintray.com/bndtools/bndtools/3.0.0/

On Fri, Sep 18, 2015 at 12:03 PM, The Alchemist <notifications@github.com>
wrote:

> Thanks, @gamerson <https://github.com/gamerson> . I installed whatever
> came up in the Eclipse Marketplace, and I think you're right, I have 2.x.
> Eclipse says:
>
> ``
> Bndtools 2.4.1.REL-20150116-150145-g75d944b
> bndtools.main.feature.feature.group
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bndtools/issues/1180#issuecomment-141508270>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by The-Alchemist** [comment]
Ah, Eclipse Update brought up 3.0.0 for me, and now I don't get that error anymore.

Thanks, @gamerson !
