### ISSUE TITLE
ArrayIndexOutOfBoundException: -1 when Resolve

### ISSUE THREAD

**Issue by JSlain** [bndtools/bndtools#1185]
Bndtools	3.1.0.DEV-20150918-142717-gc38e509
But i have the problem for a while...

Only happening with one of my bundle so far.
When i click the [Resolve] button, prior to launching my framework, i get this error.
Nothing appears in the eclipse Error view.

My /cnf contains the jpm4j repo, and i added Amdatu repo.

Here's the manifest of the bundle causing the problem.
The same code was working in a previous released version of bndtools.

    Bundle-ManifestVersion: 2
    Bundle-Name: org.jslain.core.mongo
    Bundle-SymbolicName: org.jslain.core.mongo
    Bundle-Version: 1.0.0.201509191344
    Created-By: 1.8.0_45 (Oracle Corporation)
    Export-Package: org.jslain.core.jpa.mongo;version="1.0.0";uses:="net.vz. mongodb.jackson,org.amdatu.mongo,org.jslain.core.jpa"
    Import-Package: com.mongodb;version="[2.10,3)",net.vz.mongodb.jackson;ve
    rsion="[1.4,2)",org.amdatu.mongo;version="[1.1,2)",org.bson.types;versi
    on="[2.10,3)",org.jslain.core.jpa;version="[1.0,2)"
    Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
    Tool: Bnd-3.1.0.201509181810

![image](https://cloud.githubusercontent.com/assets/986798/9976479/b52b6124-5eb3-11e5-97f3-03171a33117e.png)

**Comment by JSlain** [comment]
Anyway i can get the full stacktrace?

**Comment by seanbright** [comment]
There should be a stacktrace in eclipse's Error Log view.

**Comment by JSlain** [comment]
I wish so... but no.
However, I dropped my /cnf folder, put it back from enRoute templates, and the error is gone.

But now I have this one... should I open a new ticket?

![image](https://cloud.githubusercontent.com/assets/986798/10037240/74cf9e8a-6181-11e5-83fc-ff3d851d4404.png)

**Comment by seanbright** [comment]
Are you able to publish a workspace somewhere that we can use to replicate the problem?

**Comment by bjhargrave** [comment]
@pkriens has also observed launch/test problems in 3.1.0.DEV. We need to investigate.

**Comment by JSlain** [comment]
I'll try to produce a workspace to reproduce the problem tonight, if it can help.

**Comment by JSlain** [comment]
https://drive.google.com/file/d/0B2Ua4syAhIBwNC1DcXBZaWlFYm8/view?usp=sharing

I took my 'not-working' project, and removed content and dependencies as long as the problem persists (I could have found the culprit). Funny thing, I ended with a near-empty project, with no dependencies at all. Maybe the problem is in the /cnf folder, or in the workspace itself.

**Comment by JSlain** [comment]
I cloned bndtools to try to debug my workspace. It turns out I cannot start it 'cause I get the same error. The problem seems unrelated to the workspace, cnf or project to run. Do you use the latest build to work on bndtools?

**Comment by pkriens** [comment]
3.1 is cratered :-( Don’t use it. We need probably to revert.

**Comment by JSlain** [comment]
If it helps, i noticed it only happens while trying to run the bnd.bnd file. The .bndrun files seems to work.

**Comment by JSlain** [comment]
The original problem (ArrayIndexOutOfBoundException: -1) is still happening, 3.0.0.REL, in a completely new Eclipse installation (Mars).
Still nothing in the Error Log.

**Comment by JSlain** [comment]
I managed to get the stacktrace (using master sources):

    java.lang.ArrayIndexOutOfBoundsException: -1
	at org.apache.felix.resolver.util.CopyOnWriteList.set(CopyOnWriteList.java:53)
	at org.apache.felix.resolver.Candidates.prepare(Candidates.java:1052)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:173)
	at biz.aQute.resolve.BndResolver.resolve(BndResolver.java:22)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:69)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:52)
	at org.bndtools.core.resolve.ResolveOperation.run(ResolveOperation.java:65)
	at org.bndtools.core.resolve.ResolveJob.run(ResolveJob.java:57)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by pkriens** [comment]
Since 3.0.0 does work for many resolves there must be something special in your setup. Could you share a minimal workspace?

Kind regards,

	Peter Kriens

>

**Comment by JSlain** [comment]
Here's my current workspace.
The problem is in the org.jslain.ratemydinner.ui/start.bndrun, when i added a run requirement on org.jslain.ratemydinner.dinner.fake
Once the problem appeared, it won't go away, even when i remove the run requirement.
Seems like there's something hanging in cache or something... Even if i re-create the cnf folder. The only way i got it working was by reinstalling eclipse. And it went back at the time i added back the run requirement.

So the workspace i share is my entire one, since i cannot remove things until the problem appears.

https://drive.google.com/file/d/0B2Ua4syAhIBwbUpla1pvX2xXU28/view?usp=sharing

**Comment by JSlain** [comment]
I just hope i dind't just made a noob error, making you loosing your time...

**Comment by JSlain** [comment]
This is where it seems to break

![image](https://cloud.githubusercontent.com/assets/986798/10206117/4b0cfa44-6793-11e5-8d24-6de645830169.png)

**Comment by bjhargrave** [comment]
So this may be a bug in the Apache Felix Resolver (We are currently using the 1.4 version).You should file a bug there: https://issues.apache.org/jira/browse/FELIX/component/12318103.

**Comment by JSlain** [comment]
Thank you. Issue opened.

**Comment by gravelld** [comment]
I had this when I tried to resolve a bndrun file from an older version of bndtools with 3.0.0.REL. I tracked it down to:

    -runsystempackages: sun.misc,sun.nio,sun.nio.ch,sun.reflect,junit.framework,javax.servlet,javax.servlet.http,sun.reflect

Removing that line allowed it to resolve... I now need to do some further work to check if that is going to cause me problems!

**Comment by pkriens** [comment]
The sun.* packages should in generally be ok. The javax.servlet.* and junit.* packages are worrisome. They should in general come from other bundles and not from the class path. They should also have versions. Such a setup could cause uses constraints.

Kind regards,

	Peter Kriens

**Comment by gravelld** [comment]
Agree, I'll review why that's there. All the same, it still gives an AIOOBE with only the sun.* packages.

**Comment by jest** [comment]
@JSlain it indeed looks like resolver problem.

In my case this error was caused by "Amdatu Release" repository -- when I removed it (I only need their "Dependencies" repo), the resolution continued. (Didn't succeeded though, due to extensive memory usage by the resolver, but this is another story)

**Comment by JSlain** [comment]
Thanks, i'm using 'Amdatu Release' repo too.
I'll try if it resolve my problem.

**Comment by paulbakker** [comment]
I'm not using the resolver at all myself, but I did some testing just now, and I'm not getting errors (with Amdatu Release enabled).

**Comment by JSlain** [comment]
@jest You're right, everything works fine when i remove Amdatu Release! It's ok for me too since I don't use Amdatu for now. But they provide very usefull bundles too, i might need them someday.

**Comment by JSlain** [comment]
Worth noting, as of today i still have the bug, with latest version.
I also found out what was the cause.

I'm using the: *osgi.enroute.template/cnf*

In the file:
*/cnf/ext/enroute-distro.bnd*

There's this line:
*-runsystempackages.eqnx:		javax.script*

For what i understand, the execution environment is used like a bundle. Every package it contains is considered as exported, and same thing for the *-runsystempackages* part. So, in this case, *javax.script* is kinda exported *twice* fro the *EE* bundle.

So i just have to remove that line (as stated by @gravelld), and everything works fine.

In the felix resolver, there's a loop to replace every capability with a wrapped one, and that doesn't seem to support duplicated capabilities at all.

**Comment by pkriens** [comment]
So the question is what happens on Equinox? I guess there must have been a reason why I added this to enRoute?

**Comment by JSlain** [comment]
Since this is something added to /cnf folder, and is global to the workspace, it could work on some project and not for others, since their run configuration may be different.

For example, a project could run on Java5, which didn't have javax.script, while another one runs on Java8.

Could the solution be to ignore *-runsystempackages* on packages that are already exported?

**Comment by pkriens** [comment]
Well, since it is possible to export the same package with different versions it is primarily the framework's responsibility.

**Comment by JSlain** [comment]
I'm not sure to understand all of it. I'm not talking about the framework, but about the Execution Environment, which in my case is Java8.

The resolver creates a EE bundle for it, and scan/adds all packages for Java8 as offered Capabilities. It then does the same for explicitely state *-runsystempackages*.

Is the EE bundle a mix of Framework + Execution Environment?

**Comment by pkriens** [comment]
Sorry my mistake. I should have read the whole thread.

**Comment by JSlain** [comment]
Is it okay to exclude duplicates? That's an easy fix i can work on.

**Comment by pkriens** [comment]
Depends on what you call a duplicate. If 2 capabilities have the same name space, same directives, and same attributes then they can be discarded. You might want to check if bnd's code is properly implementing the equals/hashCode so that this happens automatically.

**Comment by JSlain** [comment]
Can the bug be reopen, since it's still happening, and the fix will be in bndtools?

**Comment by bjhargrave** [comment]
I suggest a new issue in the right place: https://github.com/bndtools/bnd/issues/new
