### ISSUE TITLE
Deadlock during refreshing/building workspace

### ISSUE THREAD

**Issue by peterkir** [bndtools/bndtools#1194]
Win7, Java 8, Eclipse 4.5, Bndtools 3.0 REL
looks similar to #1105 

Worker-32 [151] (BLOCKED)
   aQute.bnd.build.Project.getBuilder line: 187 
   aQute.bnd.build.Project.getSubBuilders line: 2394 
   aQute.bnd.build.Project.getVersions line: 2817 
   aQute.bnd.build.WorkspaceRepository.versions line: 143 
   aQute.bnd.build.Project.getBundle line: 1174 
   aQute.bnd.build.Project.getBundles line: 597 
   aQute.bnd.build.Project.parseBuildpath line: 504 
   aQute.bnd.build.Project.prepare line: 351 
   aQute.bnd.build.Project.getTarget line: 1474 
   aQute.bnd.build.Project.clean line: 1942 
   org.bndtools.builder.BndtoolsBuilder.clean line: 320 
   org.eclipse.core.internal.events.BuildManager$2.run line: 736 
   org.eclipse.core.runtime.SafeRunner.run line: 42 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 205 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 245 
   org.eclipse.core.internal.events.BuildManager$1.run line: 300 
   org.eclipse.core.runtime.SafeRunner.run line: 42 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 303 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 262 
   org.eclipse.core.internal.events.BuildManager.build line: 402 
   org.eclipse.core.internal.resources.Project$1.run line: 556 
   org.eclipse.core.internal.resources.Workspace.run line: 2241 
   org.eclipse.core.internal.resources.Project.internalBuild line: 534 
   org.eclipse.core.internal.resources.Project.build line: 111 
   org.eclipse.ui.internal.ide.dialogs.CleanDialog.doClean line: 323 
   org.eclipse.ui.internal.ide.dialogs.CleanDialog$1.runInWorkspace line: 153 
   org.eclipse.core.internal.resources.InternalWorkspaceJob.run line: 39 
   org.eclipse.core.internal.jobs.Worker.run line: 55 

Worker-745 [931] (BLOCKED)
   aQute.bnd.build.Project.getVersions line: 2815 
   aQute.bnd.build.WorkspaceRepository.versions line: 143 
   aQute.bnd.build.Project.getBundle line: 1174 
   aQute.bnd.build.Project.getBundles line: 597 
   aQute.bnd.build.Project.parseBuildpath line: 504 
   aQute.bnd.build.Project.prepare line: 351 
   aQute.bnd.build.Project.getBuildpath line: 808 
   org.bndtools.builder.classpath.BndContainerInitializer$Updater.calculateProjectClasspath line: 291 
   org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer line: 198 
   org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate line: 88 
   org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate line: 133 
   org.bndtools.builder.jobs.newproject.AdjustClasspathsForNewProjectJob.runInWorkspace line: 55 
   org.eclipse.core.internal.resources.InternalWorkspaceJob.run line: 39 
   org.eclipse.core.internal.jobs.Worker.run line: 55

**Comment by peterkir** [comment]
also directly after an restart on bndtools workspace itself :-( I wanted to debug the issue.

Worker-6 [42] (BLOCKED)
   aQute.bnd.build.Project.getVersions line: 2815 
   aQute.bnd.build.WorkspaceRepository.versions line: 143 
   aQute.bnd.build.Project.getBundle line: 1174 
   aQute.bnd.build.Project.getBundles line: 597 
   aQute.bnd.build.Project.parseBuildpath line: 504 
   aQute.bnd.build.Project.prepare line: 351 
   org.bndtools.builder.BndtoolsBuilder.build line: 167 
   org.eclipse.core.internal.events.BuildManager$2.run line: 734 
   org.eclipse.core.runtime.SafeRunner.run line: 42 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 205 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 245 
   org.eclipse.core.internal.events.BuildManager$1.run line: 300 
   org.eclipse.core.runtime.SafeRunner.run line: 42 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 303 
   org.eclipse.core.internal.events.BuildManager.basicBuildLoop line: 359 
   org.eclipse.core.internal.events.BuildManager.build line: 382 
   org.eclipse.core.internal.resources.Workspace.buildInternal line: 486 
   org.eclipse.core.internal.resources.Workspace.build line: 398 
   org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$3.run line: 2996 
   org.eclipse.core.internal.jobs.Worker.run line: 55 
main [1] (BLOCKED)
   aQute.bnd.build.Project.getBuilder line: 187 
   aQute.bnd.build.Project.getSubBuilders line: 2394 
   aQute.bnd.build.Project.getVersions line: 2817 
   aQute.bnd.build.WorkspaceRepository.versions line: 143 
   aQute.bnd.build.Project.getBundle line: 1174 
   aQute.bnd.build.Project.getBundles line: 597 
   aQute.bnd.build.Project.parseBuildpath line: 504 
   aQute.bnd.build.Project.prepare line: 351 
   aQute.bnd.build.Project.getBuildpath line: 808 
   org.bndtools.builder.classpath.BndContainerInitializer$Updater.calculateProjectClasspath line: 291 
   org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer line: 198 
   org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate line: 88 
   org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate line: 133 
   org.bndtools.builder.classpath.BndContainerInitializer.modelChanged line: 105 
   bndtools.central.Central.refreshPlugin line: 531 
   bndtools.views.repository.RepositoriesView$13$1.run line: 621 
   org.eclipse.jface.action.Action.runWithEvent line: 473 
   org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection line: 595 
   org.eclipse.jface.action.ActionContributionItem.access$2 line: 511 
   org.eclipse.jface.action.ActionContributionItem$5.handleEvent line: 420 
   org.eclipse.swt.widgets.EventTable.sendEvent line: 84 
   org.eclipse.swt.widgets.Display.sendEvent line: 4362 
   org.eclipse.swt.widgets.Widget.sendEvent line: 1113 
   org.eclipse.swt.widgets.Display.runDeferredEvents line: 4180 
   org.eclipse.swt.widgets.Display.readAndDispatch line: 3769 
   org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run line: 1127 
   org.eclipse.core.databinding.observable.Realm.runWithDefault line: 337 
   org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run line: 1018 
   org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI line: 156 
   org.eclipse.ui.internal.Workbench$5.run line: 654 
   org.eclipse.core.databinding.observable.Realm.runWithDefault line: 337 
   org.eclipse.ui.internal.Workbench.createAndRunWorkbench line: 598 
   org.eclipse.ui.PlatformUI.createAndRunWorkbench line: 150 
   org.eclipse.ui.internal.ide.application.IDEApplication.start line: 139 
   org.eclipse.equinox.internal.app.EclipseAppHandle.run line: 196 
   org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication line: 134 
   org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start line: 104 
   org.eclipse.core.runtime.adaptor.EclipseStarter.run line: 380 
   org.eclipse.core.runtime.adaptor.EclipseStarter.run line: 235 
   sun.reflect.NativeMethodAccessorImpl.invoke0 line: not available [native method]
   sun.reflect.NativeMethodAccessorImpl.invoke line: 62 
   sun.reflect.DelegatingMethodAccessorImpl.invoke line: 43 
   java.lang.reflect.Method.invoke line: 497 
   org.eclipse.equinox.launcher.Main.invokeFramework line: 669 
   org.eclipse.equinox.launcher.Main.basicRun line: 608 
   org.eclipse.equinox.launcher.Main.run line: 1515

**Comment by bjhargrave** [comment]
This is a similar but different issue than #944. PR to come.

**Comment by fhuberts** [comment]
how about #702?

**Comment by bjhargrave** [comment]
> how about #702?

702 is pretty old and predates the changes to the builder and classpath. I suspect it may be the same sort of problem (non-thread safety of bndlib) but since the builder and classpath code is so different, I can't be sure.

**Comment by peterkir** [comment]
Issue appears again today. Sadly I haven't remote debug activated.

**Comment by bjhargrave** [comment]
Are you using the latest 3.1.0.DEV builds from master (where this issue is fixed)? Or are you still using 3.0.0.REL (which the stack trace seems to indicate <https://github.com/bndtools/bndtools/blob/3.0.0.REL/bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java#L167>)?
