### ISSUE TITLE
Resolve bug

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1202]
Hi

In my musicTreePrograms project (https://github.com/fhuberts/musicTreePrograms) I think I have found a resolve bug.

I'm on latest master bndtools.

* Checkout the branch 'resolve-bug'.
* Build
* Try to resolve ```audiotagchecker/audiotagchecker.bndrun```

You now find that ```nl.pelagic.audio.conversion.flac2mp3``` is included.
bndtools claims that this is because
```
nl.pelagic.audio.conversion.flac2mp3
  REQUIRED BY nl.pelagic.shutdownhook
```

This is NOT true. The requirement is the other way around!
And since ```nl.pelagic.audio.conversion.flac2mp3``` is not in the run requirements it should not be in the resolved result.

**Comment by fhuberts** [comment]
ping?

**Comment by pkriens** [comment]
Why is it required by nl.pelagic.shutdownhook? The window provides a lot more info

**Comment by fhuberts** [comment]
It is not.

flac2mp3 implement ShutdownHookParticipant. That does not mean the shutdownhook requires it.

Please look at the code.

**Comment by pkriens** [comment]
I am not going to look at any code before I’ve exhausted all other possibilities. Even then, the reporter should make a very small example exhibiting the problem not a big project with lots of unrelated projects.

Anyway. the resolver pane provides extensive information WHY something is required. This information would be useful. I.e. make an image of the result window with all the reasons opened would help.

Kind regards,

	Peter Kriens

**Comment by fhuberts** [comment]
How is providing you with a 100% reproducible project not good enough?

And the problem is very clear.
The direction of dependencies is wrongly interpreted sometimes.

Doing the resolve yourself, seeing what happens and then looking at the 
implemented interfaces will make you see it right away. All it takes is 
a 'git clone', opening the workspace in Eclipse, importing the projects, 
and doing the resolve.
Not more than 5 minutes.

I'm disappointed. I'm reporting a true bug here and you won't invest 5 
minutes.

You can also resolve the flac3mp.bndrun.
That provides you with an even bigger demonstration of the same bug.
So I've already made it smaller for you.


On 30/10/15 18:57, Peter Kriens wrote:
> I am not going to look at any code before I’ve exhausted all other 
> possibilities. Even then, the reporter should make a very small 
> example exhibiting the problem not a big project with lots of 
> unrelated projects.
>
> Anyway. the resolver pane provides extensive information WHY something 
> is required. This information would be useful. I.e. make an image of 
> the result window with all the reasons opened would help.
>
> Kind regards,
>
> Peter Kriens
>
>
>
> > On 30 okt. 2015, at 18:41, Ferry Huberts <notifications@github.com> 
> wrote:
> >
> > It is not.
> >
> > flac2mp3 implement ShutdownHookParticipant. That does not mean the 
> shutdownhook requires it.
> >
> > Please look at the code.
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/bndtools/bndtools/issues/1202#issuecomment-152597716>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bndtools/bndtools/issues/1202#issuecomment-152602565>.
>

-- 
Ferry Huberts

**Comment by pkriens** [comment]
Are you going to provide the resolve window output?

**Comment by fhuberts** [comment]
This is the best I can do on my screen.
There is a _lot_ of info in the resolve window and none of the panes can be resized.

```
@ConsumerType
public interface ShutdownHookParticipant {
 ...
}
```

ShutdownHook component:
```
<?xml version="1.0"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" name="nl.pelagic.shutdownhook.ShutdownHook" activate="activate" deactivate="deactivate">
  <implementation class="nl.pelagic.shutdownhook.ShutdownHook"/>
  <reference name="shutdownHookParticipant" cardinality="1..n" policy="dynamic" interface="nl.pelagic.shutdownhook.api.ShutdownHookParticipant" bind="addShutdownHookParticipant" unbind="removeShutdownHookParticipant"/>
</scr:component>
```



![screenshot from 2015-10-30 19-19-51](https://cloud.githubusercontent.com/assets/635705/10854323/3c8248fc-7f3b-11e5-985a-de0811e05468.png)

**Comment by bjhargrave** [comment]
Those are all `osgi.service` dependencies (filter on objectClass and effective is active). Are you sure bnd DS annotation processing did not add osgi.service requirements?

**Comment by fhuberts** [comment]
there is this on the ShutdownHook component
```
Require-Capability: osgi.service;filter:="(objectClass=nl.pelagic.shutdo
 wnhook.api.ShutdownHookParticipant)";effective:=active;cardinality:=mul
 tiple,osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
```

and this on Flac3Mp3
```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```

**Comment by bjhargrave** [comment]
So the other bundle probably provides that osgi.service capability.

**Comment by pkriens** [comment]
The shutdownhook require Shutdownhook services. Your nl.pelagic.audio.conversion.flac2mp3 provides such a service ... So it might not be what you want but it is correct as far as I can see.

You can blacklist the nl.pelagic.audio.conversion.flac2mp3 bundle to prevent this.

**Comment by fhuberts** [comment]
Not really.
There is already such a service in the run requirements AND flac2mp3 is NOT in the run requirements; it shouldn't be dragged in.
IMHO this should be treated as optional for resolving.

How do I blacklist?

I changed shutdownhook to have MULTIPLE i.s.o. AT_LEAST_ONE and that 'fixes' it.

**Comment by pkriens** [comment]
Take  a look at for some features of the resolver: 
https://github.com/osgi/osgi.enroute/blob/master/cnf/enroute-distro.bnd
