### ISSUE TITLE
Not sure I understand error level choices...

### ISSUE THREAD

**Issue by keshlam** [bndtools/bndtools#1204]
Being told to use a directory that doesn't exist causes Git to report an ERROR.

Generating an empty jarfile only causes Git to report a WARNING.

One or the other of those seems wrong. I would call them either comparable severity, or treat the latter as an ERROR but the former as a WARNING. Missing an input directory which might have gone out of use could still produce a perfectly correct jarfile; an empty jarfile seems far more unexpected and threatening.

Admittedly that may just be me and the use cases I've happened to run into.

**Comment by pkriens** [comment]
Can you give us the error messages and the conditions? We're not Git so we assume this is about bnd? We need a little bit more information.

You can always fix error/warnings with the -fixupmessages instruction.

**Comment by keshlam** [comment]
Sorry... Yes, these are bnd error messages. I'll get you the details 
shortly.
