### ISSUE TITLE
Automatically attach source for bundles from maven

### ISSUE THREAD

**Issue by cschneider** [bndtools/bndtools#1207]
In maven the source code  is provided in a separate artifact. When creating an index from a maven pom the bundles can be used in bndtools but there is no source available. This also happens when referencing maven artifacts directly in bndrun files.

So bndtools should also load the source artifacts from maven and automatically provided them when doing debugging.

**Comment by bjhargrave** [comment]
The new maven repo support has a context menu to Add Sources to a artifact from a maven repo.

**Comment by cschneider** [comment]
Adding the source code is already possible in m2e. The problem was just that the bndtools builds did not upload a source jar into the maven repo.

**Comment by bjhargrave** [comment]
I guess I do not understand the specific issue here then.

The latest code will generate -sources.jar when releasing to maven repos. See https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles/biz/aQute/bnd/biz.aQute.bndlib/3.2.0-SNAPSHOT/ for example.

**Comment by cschneider** [comment]
That is great. It was not the case when I created the issue. So I will close
