### ISSUE TITLE
Simplify resolution of requirements to bundles

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1210]
The resolution procedure is cumbersome in the tutorials. There might be use cases that need to specify run bundles explicitly but the additional Resolve step is odd in the tutorials. I'm not sure where the resolve button could actually pay off.

1) Auto-resolve on save is not marked by default. This leads to the cumbersome behaviour that you first save, then resolve, then have to see that the file was automatically modified in the background, and then can really save before running the configuration.

2) Resolve button could automatically save the file if the file was not dirty before.

(original reporter https://github.com/groenda)

**Comment by pkriens** [comment]
We're doing 2

**Comment by lostiniceland** [comment]
If nobody has done anything yet, I can offer to work on a PR over the next week(end). So you guys can spend your precious time on more important issues ;-)
