### ISSUE TITLE
Bndtools regression from 2.4.1-REL - gives a warning for a Scala project

### ISSUE THREAD

**Issue by collymy** [bndtools/bndtools#1220]
Bndtools 3.0.0-REL gives a warning on Scala projects as follows: -

```
The .classpath contains an unknown container: org.scala-ide.sdt.launching.SCALA_CONTAINER	.classpath	/bndtools-scala	line 1	Bndtools Path Problem Marker
```

The .classpath is as follows: -

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin" path="src"/>
	<classpathentry kind="src" output="bin_test" path="test"/>
	<classpathentry kind="con" path="org.scala-ide.sdt.launching.SCALA_CONTAINER"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="aQute.bnd.classpath.container"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

The warning did not happen with 2.4.1-REL.

**Comment by bjhargrave** [comment]
Yes, this warning was added in bndtools 3.0 indicating that there is a problem with fidelity to the command line build. That is, the container is outside of bnd's knowledge of the `-buildpath`. I think you can disable the warning with `-fixupmessages`.

**Comment by collymy** [comment]
Thanks for that. Adding -fixupmessages: "Eclipse*classpath*SCALA_CONTAINER*";is:=ignore to build.bnd in the cnf project gets rid of the warning. 


    On Wednesday, 18 November 2015, 14:58, BJ Hargrave <notifications@github.com> wrote:
 

 Yes, this warning was added in bndtools 3.0 indicating that there is a problem with fidelity to the command line build. That is, the container is outside of bnd's knowledge of the -buildpath. I think you can disable the warning with -fixupmessages.—
