### ISSUE TITLE
"Cannot open Junit port" on every first itest-run when opening workspace

### ISSUE THREAD

**Issue by shomeier** [bndtools/bndtools#1224]
Hi,

when I start Eclipse with a bndtools workspace and then try to run an integration test (with bndtools OSGi Junit launcher) for the first time I always get the error "Cannot open the JUnit Port: XXXX".

All subsequent runs of the integration tests work fine. It is always only the very first run after opening a workspace which fails. (The randomly choosen Junit port is available on my machine.)

Used environment:
**OS:** Mac OS X 10.11.1 (El Capitan)
**Eclipse:** Mars Release 4.5.0 (Build id: 20150621-1200)
**Java Version used to start Eclipse:** jdk1.8.0_60
**Java Version used as execution runtime for the itest:** jdk1.7.0_75
**bndtools:** 3.0.0.REL-20150910-120816-g9a0d4f8

bndtools jars git infos:

Jar | Git-SHA | Git-Descriptor
-----|-------------|-------------------
biz.aQute.bndlib_3.0.0.201509101326.jar | 0ac3b76c9bd573dfc30cbeaa53700c13ee5187d0 | 3.0.0.REL
biz.aQute.repository_3.0.0.201509101328.jar | 0ac3b76c9bd573dfc30cbeaa53700c13ee5187d0 | 3.0.0.REL
biz.aQute.resolve_3.0.0.201509101328.jar | 0ac3b76c9bd573dfc30cbeaa53700c13ee5187d0 | 3.0.0.REL
bndtools.api_3.0.0.201509101608.jar | 9a0d4f818f3e4b4aa619a41aa82500da2405131c | 3.0.0.REL
bndtools.builder_3.0.0.201509101609 | 9a0d4f818f3e4b4aa619a41aa82500da2405131c | 3.0.0.REL
bndtools.core_3.0.0.201509101608.jar | 9a0d4f818f3e4b4aa619a41aa82500da2405131c | 3.0.0.REL
bndtools.jareditor_3.0.0.201509101609.jar | 9a0d4f818f3e4b4aa619a41aa82500da2405131c | 3.0.0.REL
bndtools.release_3.0.0.201509101609.jar | 9a0d4f818f3e4b4aa619a41aa82500da2405131c | 3.0.0.REL
bndtools.repository.base_3.0.0.201509101608.jar | 9a0d4f818f3e4b4aa619a41aa82500da2405131c | 3.0.0.REL

Link to related post in bndtools google group:
https://groups.google.com/forum/#!topic/bndtools-users/g2lsl9-4hgQ

**Comment by pkriens** [comment]
We've added potential fix in bnd. So I am closing this 

See https://github.com/bndtools/bnd/pull/1236
