### ISSUE TITLE
Resolution errors out depending on bundles and/or repositories included

### ISSUE THREAD

**Issue by ro6** [bndtools/bndtools#1229]
I need some information to help narrow this to a reproducing case I can share. I have a run descriptor that I've been using in the same way since version 2.4, but about a week after updating to 3.0, now I get:

`java.lang.IllegalArgumentException: Comparison method violates its general contract!`

with no other information or anything in the Eclipse error log to help track down the source of the error.

I can prevent the error from getting thrown by removing certain bundles from the run requires (haven't figured out a pattern yet), or by playing with the runrepos. Also, certain combinations and orderings of repositories work, while others don't.

For example:

```
-runrepos: \
	Workspace,\
	Release,\
	Local,\
	Build
```
fails, but
```
runrepos: \
	Release,\
	Workspace,\
	Local,\
	Build
```
succeeds, even though the bundle versions selected (all 'snapshot' for bundles from my workspace) don't end up different than resolving without the 'Release' repo.

I'm assuming that's because the resolution algorithm givens preference to later versions of the same bundle?

Bndtools Version 3.0.0.REL-20150910-120816-g9a0d4f8
Eclipse Version: Mars Release (4.5.0), Build id: 20150621-1200
Arch Linux 4.3.0-1-ck x86_64

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by bjhargrave** [comment]
Please try again on the latest 3.2 build. If still a problem, please provide more detail.
