### ISSUE TITLE
Allow the bndtools builder that generates a jar to be disabled for automatic builds

### ISSUE THREAD

**Issue by eli-jordan** [bndtools/bndtools#1231]
As was discussed here https://groups.google.com/forum/#!topic/bndtools-users/1eZ9Qau4a_0

Sometimes generating the jar and manifest can take some time. It would be great if it was possible to disable that portion of the build, for automatic incremental builds in eclipse, and allow it to be invoked manually. 

Note: That I think for this to be useful, the 'Bnd Bundle Path' classpath container would need to be updated incrementally without a full build.

**Comment by bjhargrave** [comment]
You can always set `-nobundles: true` in the project bnd file or even the cnf/build.bnd file.
