### ISSUE TITLE
Repositories vanish from Repository view when modifying build.bnd | An internal error occurred during: "Refresh Workspace Repository". java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by flangel** [bndtools/bndtools#1246]
**3.1 RC2** Mars1

Following flow
1. modify build.bnd (any modification), for instance 1.8 -- > 1.9 --> 1.8

#javac:                 javac
javac.source:			1.8
javac.target:			1.8

2. save
3. Repository view shows only workspace folder, all other entries vanished !!!

Getting error An internal error occurred during: "Refresh Workspace Repository". java.util.ConcurrentModificationException

4. Press Menu Bndtools | Refresh Repositories
5. Repositories are back

Very easily reproducable works everytime.

**Comment by bjhargrave** [comment]
@pkriens Didn't you make some changes in the area of the repository views just recently?

**Comment by pkriens** [comment]
Need to know the setup and/or the actual exception trace.

**Comment by flangel** [comment]
With a fresh approach, we found the issue. 

Our repository was pointing to aQute.bnd.deployer.repository.FixedIndexedRepo; name=Bndtools Hub; locations=https://github.com/bndtools/bundle-hub/raw/master/index.xml.gz,\

Whereas the default from 3.1 was aQute.bnd.deployer.repository.FixedIndexedRepo; name=Bndtools Hub; locations=https://raw.githubusercontent.com/bndtools/bundle-hub/master/index.xml.gz,\
	
May i ask when the location was changed?
Thanks

**Comment by pkriens** [comment]
Still would like to see the stack trace so I can fix the bug. Even an invalid setup should not give you a Concurrent Modification Exception ...

**Comment by flangel** [comment]
I would have added a stack trace if there was. But there wasn't
