### ISSUE TITLE
Bug (Project Template) Directories are not created when template directory is empty

### ISSUE THREAD

**Issue by flangel** [bndtools/bndtools#1249]
Reproduce 3.1RC2
===============
1. Create a new template
2. Add directories to template/$srcDir$/$basePackageDir$

Problem
======
The directories that are empty (with no file) will not be created when creating a new project from that template. In this example, only bootstrap dir is created in resulting project

![directoriesignored](https://cloud.githubusercontent.com/assets/2772980/11807465/3506beac-a31a-11e5-8cdc-32925128738d.png)

**Comment by njbartlett** [comment]
I can fix this but I'm not convinced it's even a good idea. Why are empty folders useful? They will be deleted by your SCM anyway (certainly Git will delete them). Maybe the template should contain a placeholder or README explaining what the user is supposed to put in there?

**Comment by flangel** [comment]
Yes. I could put placeholder files in there, but it would be nice to leave the user a choice.

**Comment by njbartlett** [comment]
Yes I am planning to do so.
