### ISSUE TITLE
Don't update framework during build

### ISSUE THREAD

**Issue by brampouwelse** [bndtools/bndtools#1267]
Sometimes the framework is updated when a build is still running.

When using the default launcher behavior (on a mac) which is installing bundles by reference this causes Felix to get in an inconsistent state as updating bundles causes the framework to do a refresh of bundles that are not available in the generated folder at the time of the refresh. 

This will result in exceptions like the one below in a consecutive update. 

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.apache.felix.framework.BundleImpl.adapt(BundleImpl.java:1064)
        at org.apache.felix.framework.BundleImpl.getSymbolicName(BundleImpl.java:896)
```

With some additional launcher configuration `launch.noreferences=true` things get better Felix doesn't get in an invalid state BUT bundles that are being rebuilt during the update are uninstalled (and reinstalled in a next update). This makes that bundles depending on a bundle that was reinstalled go into a RESOLVED state.

**Comment by njbartlett** [comment]
This will be tricky, the launcher is a separate process and has no knowledge of ongoing builds happening in Eclipse. For this reason the launcher waits for the file size and timestamp to remain unchanged (for a couple of seconds, I think).

Perhaps the Eclipse build could create a marker file before changing the file, and remove it afterwards...

**Comment by bjhargrave** [comment]
Well each project's builder is independent of the other project's builder. Only Eclipse knows when it it done building. So I am not sure how the launcher can know when all the building is done.

**Comment by brampouwelse** [comment]
Maybe it's enough if the launcher doesn't remove the bundle when the file doesn't exist during an update (at least when using ```launch.noreferences=true```) 

https://github.com/bndtools/bnd/blob/master/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L512

Here the bundle is not added to the desired set of bundles just because the jar doesn't exist (because it's being rebuilt), would it be safe to add it to the desired bundle list in case it's already installed to prevent the bundle from being uninstalled?
