### ISSUE TITLE
Clicking on bundle version in Repositiories view does not open JAR File Viewer window

### ISSUE THREAD

**Issue by flangel** [bndtools/bndtools#1268]
I could not reopen old issue, so here I opened new ticket with same issue from
https://github.com/bndtools/bndtools/issues/1250

Hi, thanks for the update. But it didnt solve the issue.

- Using Mars1
- Using Java 1.8
- Using BndTools downloaded here https://bndtools.ci.cloudbees.com/job/bndtools.next/lastSuccessfulBuild/artifact/build/generated/p2/ contains the fix.

Still, when clicking on version number of any bundle in https://dl.bintray.com/bnd/dist/, no bundle is loaded and no error message appears (for any bundle)

![image](https://cloud.githubusercontent.com/assets/2772980/12170933/c57b80ca-b545-11e5-8fc6-d764c59a6c6a.png)

**Comment by flangel** [comment]
@bjhargrave : needed to reopen/create new ticket. No access to the bundles/no error message of any kind.

**Comment by bjhargrave** [comment]
When you say "hang" do you mean that Eclipse is unusable and you have to kill the Eclipse process?

**Comment by flangel** [comment]
@bjhargrave : I click on the version number, but the bundle doesnt open and no error is being shown.

**Comment by bjhargrave** [comment]
Yes, I can see the jar viewer does not open for the bundle. However, I am able to drag-n-drop the version onto a bnd file editor window (e.g. Build Path).

So this does need a fix but since there is no hang, it is not a critical blocking issue.

**Comment by flangel** [comment]
Ok. thank you. I couldn't drag it to any window / open the version of that bundle at all and consider this crucial, but we are looking forward to the fix in 3.2.

**Comment by peterkir** [comment]
If you select the bundle press the download button and afterwards double-click the version the jar viewer is opening.

**Comment by gamerson** [comment]
@flangel is this the same as this one? https://github.com/bndtools/bndtools/issues/1286

**Comment by bjhargrave** [comment]
I think this is fixed by https://github.com/bndtools/bndtools/pull/1347

**Comment by ottlinger** [comment]
Verified with 
```
3.2.0.201605022116-SNAPSHOT
```
behaviour seems to be related to fixes introduced via #1347
