### ISSUE TITLE
NullPointerException after adding exported package

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bndtools#1270]
(See https://github.com/bndtools/bndtools/issues/781, adding this as new issue accoring to comment.)

While trying Bndtools for the first time I got the following error: "Error finding source package for exported 1packages."

I'm just trying to walk through the tutorial. In order to keep things clean, I've created a top-level project OSGi-Test and put everything below it. Version is 3.1.0.REL-20151218-090315-gffa01d9 (what a number, and not even copyable!).

[OSGi-Test.zip](https://github.com/bndtools/bndtools/files/82980/OSGi-Test.zip)

Quite frustrating to run into such a problem when you do your first steps...

(For me, this is a priority one issue. I don't know what to do eventually, tyring to develop an OSGi project without IDE support doesn't seem like a good idea. But I know that I cannot manage my project if every OSGi item has to be a top level project in my workspace.)

**Comment by pkriens** [comment]
Not sure which tutorial you did and we recognize the problem. (You should get lots of warnings since the bnd file is empty.)

Could you try the OSGi enRoute [Quick Start tutorial][1]

[1]: http://enroute.osgi.org

**Comment by bjhargrave** [comment]
No response.
