### ISSUE TITLE
Ambiguous warnings from ProjectPathsValidator

### ISSUE THREAD

**Issue by jawi** [bndtools/bndtools#1274]
When updating our projects to the latest greatest (3.1.1) Bndtools, we get a set of warnings that are rather ambiguous, for example:

    Eclipse: The .classpath contains an unknown container: org.eclipse.jdt.junit.JUNIT_CONTAINER/4

The message looks like as if Eclipse itself is complaining about this instead of Bndtools. In addition, the message suggests that the container itself is no longer recognised. Though I've doubts whether this is actually a valid warning, I propose that the message (and the other messages generated by the validator) should state something like:

    Bndtools: the classpath contains an unknown container: <NAME>. This could make your build not portable.

**Comment by bjhargrave** [comment]
Sounds good. Can you make a PR?

**Comment by jawi** [comment]
Will do.

**Comment by jawi** [comment]
PR created in #1275.
