### ISSUE TITLE
Maven project layout folders not added to bnd.bnd

### ISSUE THREAD

**Issue by kitschen** [bndtools/bndtools#1277]
I create a new Bnd OSGi project in Eclipse.
- Choose component development
- Choose Maven project layout
- Click Finish
The src folders src/main/Java and src/test/java are created,
but in bnd.bnd there is no src etc parameter. 

Eclipse complains with warnings like
Eclipse: bnd's src folder 'src' is not in the Eclipse build path	bnd.bnd
Eclipse: Found source folder 'src/main/java' that is not on bnd's source path 'src'	

Expected is bnd.bnd content is (probably):
...
src: src/main/java
bin: target/classes
target-dir: target
testsrc: src/test/java
testbin: target/test-classes
...

Using: 
Eclipse Mars.1 on Ubuntu 
with latest Bndtools from Marketplace (3.1.1)

**Comment by pkriens** [comment]
Probably a new template issue

**Comment by bjhargrave** [comment]
See another report of this problem: <https://groups.google.com/forum/#!topic/bndtools-users/dYVCGQgOL0o>.

**Comment by pkriens** [comment]
@njbartlett  Neil??

**Comment by bjhargrave** [comment]
Remove the maven option. Another template can be created to maven project layout.
