### ISSUE TITLE
Resolve Button is doing nothing when org.eclipse.osgi-3.10.101 is part of the Run Requirements

### ISSUE THREAD

**Issue by peterkir** [bndtools/bndtools#1278]
BndEditor is neither resolving nor giving an error if OSGi bundle org.eclipse.osgi-3.10.101 is part of the run requirements. A warning would be nice for fools like myself who included it there.

**Comment by pkriens** [comment]
Hmm, I am getting 

    'org.osgi.service.resolver.ResolutionException: Unable to resolve <<INITIAL>> version=null: missing requirement org.eclipse.osgi; version=3.10.1'

Could you retry this with the 3.2.0 RC?
