### ISSUE TITLE
BND Editor does not  reflect updates of section "Repositories" inside section "Browse Repos"

### ISSUE THREAD

**Issue by peterkir** [bndtools/bndtools#1279]
win7, java 8, eclipse 4.5.1, bndtools 3.1.1.REL-20160122-125321-g240736f

After adding or removing repos from the **Repositories** the **Browse Repo** is not updated.
Even after saving it is not updated.
Only after closing and re-opening the editor the updates are visible.

**Comment by pkriens** [comment]
Can you show each step? Because changing the set of repos should be a complete refresh?

**Comment by peterkir** [comment]
1. Run descriptor open
2. Changing the ext/repositories.bnd file
3. Repository Section in Run descriptor is not updated (even after 5 mn)

the Stand-alone Repository View is updated.

**Comment by pkriens** [comment]
I've tested this on 3.2.0 and it seems to work. It takes a second or so. I deleted an entry from a local repository and that was reflected ok. So could you retest?
