### ISSUE TITLE
BND Editor resolve is not considering repo updates for local repos

### ISSUE THREAD

**Issue by peterkir** [bndtools/bndtools#1280]
win7, java 8, eclipse 4.5.1, bndtools 3.1.1.REL-20160122-125321-g240736f

After "Resolve" gives an "Resolution failed!, the missing bundle is added to the local repo and "Resolve" is started again. Added bundle is not considered and the Resolution Error happens again. Only after closing and re-opening of the BND Editor the resolution is working fine.
Tested only with local repo.

**Comment by pkriens** [comment]
What is the type of the local repo?

**Comment by peterkir** [comment]
It is working fine. I was mixing this case up with the issues #1279. Hence closing.
