### ISSUE TITLE
Non annotation argument to lifecycle method with descriptor wrongly reported

### ISSUE THREAD

**Issue by ivoleitao** [bndtools/bndtools#1283]
Hi !,

I'm doing some tests with declarative services and I noticed a compile error in bnd tools that is apparently wrong. I't very easy to simulate. We only need to declare a class like this one:

    public class BaseService<T extends Annotation> {
	    @Activate
	    public void activate(T annotation) {	}
    }

Bndtools will immediatly report the following error:
_Non annotation argument to lifecycle method with descriptor (Ljava/lang/annotation/Annotation;)V,  type java/lang/annotation/Annotation_

This should be valid. I will have dozens of classes that will extend something like this and storing the configuration in the base class is very helpful.

**Comment by ivoleitao** [comment]
This looks like an error in bnd itself. I've found the message in the bnd source code and I can confirm that using directly the maven bundle plugin the same error occurs

**Comment by bjhargrave** [comment]
The problem with your example is that T is not bound to a specific annotation type. So when bnd examines the bytecodes for the activate method, T's "erased" type is Annotation which is not a legitimate annotation type that DS can construct at runtime.

What you are trying to do cannot really be done with bnd or DS since they both need to know the actual annotation type. Your use of T means that the type in the class file is "erased".

**Comment by bjhargrave** [comment]
In a subclass where T is bound to a specific annotation type, you can put use the @Activate annotation.

```java
public class BaseService<T extends Annotation> {
    public void activate(T annotation) {    }
}
public class FooService extends BaseService<FooAnnotation> {
    @Activate
    public void activate(FooAnnotation annotation) {  super.activate();  }
}```

**Comment by pkriens** [comment]
I do not understand what you want to do here? Your base class can only use the annotation like Annotation and will have to reflect. That is basically the same as using a Map. What is the advantage of that?

And you're using inheritance while the OSGi annotations do NOT work officially with inheritance.

**Comment by ivoleitao** [comment]
Let me try to explain. In my company we have a SOA like infrastructure composed of thousand of soap services. To tackle with that I'm using CXF and I plan to create a bundle with all the proxy's for the SOAP Services that I will need (+- 250).  Each proxy is accessed through a OSGI service. To alleviate the code needed I've developed a base class to handle some common cxf proxy initialization stuff.

Since I will have a lot of services I'm trying to reduce the code needed to type for each service. The first step was to declare the @Activate and the @Modified annotations in the base class and to receive a map with configurations on those methods. That has worked fairly well since all the services have the same set of configurations that I will reproduce bellow in an example:

    @ObjectClassDefinition(name = "%name", description = "%description", localization = "OSGI-INF/l10n/service/qry", icon = @Icon(resource = "OSGI-INF/icon/ws.png", size = 32) )
    public @interface ServiceQryCfg {
        @AttributeDefinition(name = "%name.name", description = "%name.description")
	    String name() default "Service:qry";

        @AttributeDefinition(name = "%namespaceUri.name", description = "%namespaceUri.description")
	    String namespaceUri() default "http://localhost/Service.wsdl";

        @AttributeDefinition(name = "%serviceName.name", description = "%serviceName.description")
	    String serviceName() default "serviceWSDL";

        @AttributeDefinition(name = "%wsdlLocation.name", description = "%wsdlLocation.description")
	    String wsdlLocation() default "wsdl/service/Service.qry.wsdl";

        @AttributeDefinition(name = "%address.name", description = "%address.description")
	    String address() default "http://localhost/service";

        @AttributeDefinition(name = "%userName.name", description = "%userName.description")
	    String userName() default "user";

        @AttributeDefinition(type = AttributeType.PASSWORD, name = "%password.name", description = "%password.description")
	    String password() default "password";

        @AttributeDefinition(type = AttributeType.LONG, name = "%connectionTimeout.name", description = "%connectionTimeout.description")
	    int connectionTimeout() default 10000;

        @AttributeDefinition(type = AttributeType.LONG, name = "%receiveTimeout.name", description = "%receiveTimeout.description")
	    int receiveTimeout() default 180000;
    }

My activate and modified methods in the base class are like the following:

	@Activate
	public void activate(ComponentContext ctx, Map<String, Object> configMap) {
		prepare(ctx, configMap);
	}

	@Modified
	public void modified(ComponentContext ctx, Map<String, Object> configMap) {
		synchronized (this.preparationMonitor) {
			prepare(configMap);
		}
	}


However some of the services will have particular configurations that will deviate from this pattern. To tackle with that my first approach was to add the Annotation parameter to the base class and store in there the annotation to be used. That's when I've found this problem (I've changed the activate and modified methods above accordingly). Doing that would remove the need to store the configuration in each class. I've not investigated but maybe I can extract the annotation from the bundle context in those cases... (it's possible ?).

I understand the limitation as explained. However I didn't know that inheritance is not supported, It has worked fairly well. My objective in here as said is reduce as much as possible the typed code. Adding @Activate and @Modified to all this services is a perfect example since they will do exactly the same for each one.

**Comment by bjhargrave** [comment]
Re: inhertance

1). Annotation classes do not support inheritance. So I don't see any useful value to <T extends Annotation> as argument type to an activate method. This is the same as saying Annotation as an argument type that is of zero value.

2.) OSGi DS annotations are specified to only apply to the directly annotated class. That is, @Component, etc on super type are ignored. This is because the super types can come from an imported package and this can change between build time and runtime. No bnd supports, with a flag, "inheritance" which mean bnd will look at the super types visible at build time to generate the DS XML.

These two items are mostly orthogonal except where you seem to be hitting them both in you usage.

Please show how you would use the ServiceQueryCfg type in the base  and subclass activate methods.

**Comment by pkriens** [comment]
I am really curious how much behavior you have in your proxies? If you have no special code for a proxy, it is just all about configuration then there are much better solutions than using DS?
