### ISSUE TITLE
wab support in bnd-maven-plugin is broken

### ISSUE THREAD

**Issue by thomasmey** [bndtools/bndtools#1284]
Hi,

okay I did debug this a bit and your statement "In particular the bnd-maven-plugin only creates OSGi metadata (bundle manifests, DS XML files...) " is not true at least for wab instruction.

Here is what I understood and what's happing in the bnd-maven-plugin (3.1.0):

1.) All classes are compiled to target/classes directory
2.) Then the bnd-maven-plugin runs and creates the "metadata-only jar file in memory" and it add first all relevant classes:
Thread main

Builder.doExpand(Jar) line: 512
Builder.build() line: 97

BndMavenPlugin.execute() line: 161

2.) possible includes are added to the metadata-jar:
Thread main

Builder.build() line: 98

BndMavenPlugin.execute() line: 161

3.) then the wab instruction is processed:
here happens the problem/error as all classes are renamed, i.e. moved(!) in the in memory metadata jar.
when tracing is enabled this will be outputted to stderr:
"# wab: moving: de/m3y3r/testing/Example.class"

Inside Jar.rename() the resource is moved from target/classes/ to target/classes/WEB-INF/classes/
Thread main

Jar.rename(String, String) line: 732

Builder.doWab(Jar) line: 224

Builder.build() line: 99

BndMavenPlugin.execute() line: 161

4.) finally all additional resource from the -wab instructions are added to the metadata-jar.
After this step the resource of the metadata jar will look like this:
[WEB-INF/classes/de/m3y3r/Example.class, WEB-INF/web.xml, doc/index.html]

And the resource entry of WEB-INF/classes/de/m3y3r/Example.class will actually point to target/classes/de/m3y3r/Example.class

Then the manifest is processed/created and some other things are happing. you can expand the metadata jar with undocumented bnd instruction: "-expand: /dir/to/expand/to" after that the builder is finished.

Fun fact 1: The expanded metadata jar nearly looks correct. There is only a duplicated content of doc/index.html under expanded/WEB-INF/classes/. But this is maybe a bug in the dot.expand(out) (line 174 of aQute.bnd.osgi.Builder class, need to check this again).

5.) After the builder is finished actually resources are created in the target/classes directory:
First the META-INF/MANIFEST.MF file is created at BndMavenPlugin.execute() line: 164

And then the metadata jar is "expanded":
BndMavenPlugin.execute() line: 171

Here the bug manifests itself:
in this method all metadata-jar resource are actually copied from their original position to WEB-INF/classes! I think this is a bug, as before those resource were meant to be moved (in the Builder) but here they are copied and after the copy process the original file is not deleted in target/classes:

Thread main

BndMavenPlugin.expandJar(Jar, File) line: 241

BndMavenPlugin.execute() line: 171

This leaves the target/classes directory in an inconsitent state, with duplicated classes:
1.) the original classes from the compile step under target/classes and
2.) the copied classed from the wab osgi Builder move step under target/classes/WEB-INF/classes.

So what do you think about this? I would argue that this is a bug and should be fixed, but I'm not sure what's the best solution for this. Probably remove the original resource after the IO.copy()?

And after going throuh all this, I would argue that using the type jar is the correct "packager" (maven-jar-plugin) for wab files created by the bnd-maven-plugin, as most work to create a correct war/wab structure is done already in this plugin.

Hope this all makes sense.

Feedback is most welcome!

**Comment by bjhargrave** [comment]
The bnd maven plugin is not in the bndtools repo. It is in the bnd repo. There is already a bug you wrote there: https://github.com/bndtools/bnd/issues/1273. Lets move the discussion back to the bnd repo's issues. Thanks,

**Comment by thomasmey** [comment]
Hi,
Sorry for the mix up. I had the impression that my comment was lost as the bug was already closed and nobody did answer.
What should I do? Is there an mailing list to subscribe to?
With kind regards
Thomas

Am 08.02.2016 10:04 nachm. schrieb BJ Hargrave <notifications@github.com>:The bnd maven plugin is not in the bndtools repo. It is in the bnd repo. There is already a bug you wrote there: bndtools/bnd#1273. Lets move the discussion back to the bnd repo's issues. Thanks,

**Comment by bjhargrave** [comment]
My main point is that this is the wrong repo for issues with the bnd maven plugin.

As for the issue there, @timothyjward made a lengthy comment in it regarding building wars with maven.

**Comment by bjhargrave** [comment]
Also, you can ask questions in the bndtools-users mail list described in https://github.com/bndtools/bnd#feedback
