### ISSUE TITLE
 Honoring workspace -runvm parameters when exporting to executable jar 

### ISSUE THREAD

**Issue by vittali** [bndtools/bndtools#1293]
I have created a *.bnd file in cnf/ext containing config data pertaining to all workspace projects, like:

-runvm: ...
-Dfelix.fileinstall.poll=1000, -Dfelix.fileinstall.noInitialDelay=true, -Dfelix.fileinstall.dir=./cid
...

When exporting a project (with the Export button) , the executable jar doesn't seem to contain this configuration data.

**Comment by bjhargrave** [comment]
is the `-Dfelix...` on a separate line in the bnd file? If so, then all you do is define a bnd property called `-Dfelix.fileinstall.poll` which is unused. I think you want to say

```
-runproperties=-Dfelix.fileinstall.poll=1000, -Dfelix.fileinstall.noInitialDelay=true, -Dfelix.fileinstall.dir=./cid
```

**Comment by bjhargrave** [comment]
If there is still an issue after fixing the runproperties, can you please make a small repo which demonstrates the issue so we can investigate?

**Comment by vittali** [comment]
In fact, I just showed the isolated for the sake of brievety. In my workspace configuration file in cnf/ext/workspace.bnd it looks like this:

...
-runvm: -Dbinary.css=false, -Dorg.osgi.framework.storage.clean=onFirstInit, -Dorg.osgi.service.http.port=8080, \
-Dorg.apache.felix.http.jettyEnabled=true, -Dfelix.webconsole.loglevel=0,  -Dorg.ops4j.pax.logging.DefaultServiceLog.level=WARN, \
-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StrErrLog, -Dorg.eclipse.jetty.LEVEL=WARN,  \
-Dfelix.fileinstall.poll=1000, -Dfelix.fileinstall.noInitialDelay=true, -Dfelix.fileinstall.dir=./cid
...

This works fine as long as I don't export to jar. So for instance, FileInstall will look for configuration data in directory "cid" instead of the default "load" during normal development. But the executable jar will look for config data in "load" ( the default) , so the workspace setting in cnf/etc/workspace.bnd is not exported to the jar.

**Comment by bjhargrave** [comment]
I think you mean back ticks (`) not (.) to get your example correct. Otherwise markdown folds the line. You also need to mention the version of bnd you are using.

Does it work for export if you put this line in cnf/build.bnd?

**Comment by vittali** [comment]
No, it does not work in cnf/build.bnd either.
Version is: 3.1.1.REL-20160122-125321-g240736f

I have a small example project with a single component that requires conf data:

```
@Component(immediate=true, configurationPolicy = ConfigurationPolicy.REQUIRE)
public class Example {
	@Activate public void activate(BundleContext bctx, Map<String, Object> config) { 
	System.out.println("activated: " + config);
	}
}
```

and a folder **cid** at the project level containing a single conf file for felix fileinstall:

example.Example.cfg

This folder **cid** is not the standard dir for fileinstall ( which is **load** ). Since I have overridden the default in cnf/ext/workspace.bnd as shown above, this works during dev time.

I then export to jar, create a folder cid in the same dir as the jar and start the bundle:

`java -jar example.jar`

 the component will not be activated unless I rename the non-standard  conf folder **cid** to **load**.

**Comment by bjhargrave** [comment]
Can you please make a small github repo which demonstrates the problem?

**Comment by vittali** [comment]
https://github.com/vittali/bndtools1293.git

**Comment by bjhargrave** [comment]
From <https://github.com/vittali/bndtools1293/blob/master/cnf/ext/workspace.bnd#L9>

```
-runvm: -Dbinary.css=false, -Dorg.osgi.framework.storage.clean=onFirstInit, -Dorg.osgi.service.http.port=8080, \
-Dorg.apache.felix.http.jettyEnabled=true, -Dfelix.webconsole.loglevel=0,  -Dorg.ops4j.pax.logging.DefaultServiceLog.level=WARN, \
-Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StrErrLog, -Dorg.eclipse.jetty.LEVEL=WARN,  \
-Dfelix.fileinstall.poll=1000, -Dfelix.fileinstall.noInitialDelay=true, -Dfelix.fileinstall.dir=./cid
```

This is not one continued line. To continue a line, the line must end in `\` and the next line must start with whitespace. So the lines after `-runvm` are not continuing the `-runvm` statement. Also, I think these should all be on `-runproperties` since they are not arguments to the VM:

```
-runproperties: binary.css=false, org.osgi.framework.storage.clean=onFirstInit, org.osgi.service.http.port=8080, \
 org.apache.felix.http.jettyEnabled=true, felix.webconsole.loglevel=0, org.ops4j.pax.logging.DefaultServiceLog.level=WARN, \
 org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StrErrLog, org.eclipse.jetty.LEVEL=WARN, \
 felix.fileinstall.poll=1000, felix.fileinstall.noInitialDelay=true, felix.fileinstall.dir=./cid

```

Also, I tried to build the repo with gradle (after adding the necessary gradle files in the root of the repo) and it does not build since files are not found in the configured repos.

**Comment by bjhargrave** [comment]
Also, `-runsystempackages` is also has messed up line continuation.

**Comment by vittali** [comment]
Changing **runvm** to **runproperties** does not work for me even in normal dev mode. I fixed the whitespace formatting but it doesn't solve the problem.

I am working with eclipse, creating a new workspace with eclipse ( thereby creating a fresh cnf dir) and importing the example project from the github repo should build the project.

**Comment by vittali** [comment]
I uploaded the complete cnf dir with all the jars.

**Comment by bjhargrave** [comment]
> Changing runvm to runproperties does not work for me even in normal dev mode.

Because you did not fully read my example :-) When you use `-runproperties` you do not specify the `-D` before each property!

There was still a build error. I had to copy `osgi.cmpn` to the `buildrepo` which is of type `FileRepo`. I was then able to build the example bundle. However the `localrepo` is of type `LocalIndexedRepo` and the `index.xml` file is empty, so the `localrepo` repo is effectively empty which meant the exported jar was missing key things like the framework :-)

But I was able to prove (once removing all the `-D` from `-runproperties` that building `gradle :example:export` produced `example/generated/distributions/executable/launch.jar` with an expected `launcher.properties` file containing: 

```
launch.bundles=jar/example.m.jar
org.eclipse.jetty.LEVEL=WARN
launch.noreferences=false
org.apache.felix.http.jettyEnabled=true
org.osgi.service.http.port=8080
launch.activators=
org.osgi.framework.storage.clean=onFirstInit
launch.timeout=0
launch.system.capabilities=osgi.native;osgi.native.osname\:List<String>\="MacOSX,Mac OS X";osgi.native.osversion\:Version\="10.11.3";osgi.native.processor\:List<String>\="x86-64,amd64,em64t,x86_64"
launch.embedded=true
felix.webconsole.loglevel=0
org.ops4j.pax.logging.DefaultServiceLog.level=WARN
launch.system.packages=javafx.collections,netscape.javascript,jdk.nashorn.api.scripting,javafx.beans.value,javafx.scene.web,javafx.application,javafx.scene,javafx.stage,javafx.scene.layout,javafx.event,javafx.collections,javafx.scene.control,javafx.scene.paint,javafx.scene.shape,javafx.collections,javafx.event,javafx.beans.property,javafx.scene,javafx.stage,javafx.scene.control,javafx.scene.layout,javafx.embed.swing,javafx.scene.paint,javafx.scene.text,javax.swing,javax.swing.table,javax.sql,javafx.scene.shape,javafx.scene.control.cell,javafx.util,javafx.geometry,javafx.scene.image,shape.paint,javax.net,javax.net.ssl,javafx.scene.input,sun.rmi.runtime,javax.xml.namespace,javax.xml.stream,javax.xml.stream.events,javax.management,javax.naming,javax.xml.parsers,org.w3c.dom,org.xml.sax,org.xml.sax.helpers,javax.jmdns,com.ibm.uvm.tools,com.sun.jdmk.comm,javax.jms,javax.mail,javax.mail.internet,javax.management,javax.naming,javax.swing,javax.swing.border,javax.swing.event,javax.swing.table,javax.swing.text,javax.swing.tree,javax.xml.parsers,org.w3c.dom,org.xml.sax,org.xml.sax.helpers,javax.xml.datatype,org.w3c.dom.bootstrap,org.w3c.dom.ls,javax.management.modelmbean,javax.management.remote,javax.security.auth,javax.security.cert,javafx.concurrent,com.sun.javadoc
launch.keep=false
felix.fileinstall.dir=./cid
binary.css=false
felix.fileinstall.poll=1000
org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StrErrLog
launch.trace=false
launch.name=example
felix.fileinstall.noInitialDelay=true
launch.notificationPort=-1
launch.services=true
```

**Comment by vittali** [comment]
Great, thank you, that works. I resume:

**replacing -runvm with -runproperties AND removing the -D prefix and  solves the problem . **


As a footnote, I can't reproduce your build error here :-) As you can see from the output in the README.md , the bundle in Step 4 certainly started ( so I suppose there was a framework ) as long as the config data was in the fileinstall default dir. Perhaps this is due to differences between the eclipse build and the gradle build.
