### ISSUE TITLE
Bundles are not available to Build Path when workspace first created

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1298]
1. Create a new (empty) workspace.
2. Create a new Bndtools project.
3. Create a Bundle Hub cnf
4. Switch to the Build tab of the bnd.bnd editor
5. In the Build Path section, click green plus to add a bundle
6. The list of available bundles is empty

If you close and re-open the bnd.bnd file, it will work as expected.

**Comment by pkriens** [comment]
Neil, can you take a look?

**Comment by njbartlett** [comment]
Reopening... I realised this commit fixes a different (but related) problem.
