### ISSUE TITLE
Maven Bundle Plugin 3.0.1 not processing the annotations correctly

### ISSUE THREAD

**Issue by arunasujith** [bndtools/bndtools#1300]
Recently I've upgraded from maven-bundle-plugin version from 2.5.4 to 3.0.1 and I am experiencing the following behavior with the latest version.

I have following section in  Sample class

```
@Component(
        name = "org.wso2.carbon.kernel.internal.deployment.DeploymentEngineListenerComponent",
        immediate = true,
        **property = {
                "capability-name=org.wso2.carbon.kernel.deployment.Deployer",
                "component-key=carbon-deployment-service"
        }**
)
```

for the 2.5.4 version's generated MANIFEST.MF I could see the following in Provide-Capability section.

```
Provide-Capability: osgi.service;effective:=active;objectClass="org.wso2
 .carbon.kernel.startupresolver.RequiredCapabilityListener";capability-n
 ame="org.wso2.carbon.sample.deployer.mgt.Deployer";component-key=carbon
 -sample-deployment-engine
```

And for the 3.0.1 version's generated MANIFEST.MF I could see the following in Provide-Capability section. the property tag inside the Component annotation is missing. and also the objectClass is changed to objectClass:List<String>.

```
Provide-Capability: osgi.service;objectClass:List<String>="org.wso2.carb
 on.kernel.startupresolver.RequiredCapabilityListener"
```

How do I make the property inside the Component  available in MANIFEST.MF in the 3.0.1 version?

I don't use maven-scr-plugin to process the annotations, I use the , <_dsannotations>*</_dsannotations> to process the annotations.

**Comment by bjhargrave** [comment]
The correct repo for bnd issues is https://github.com/bndtools/bnd. 

But we made a specific decision to not copy service properties onto generated osgi.service capabilities and requirements which is what you are seeing now. The osgi.service capability is not terribly useful at runtime. It is more advice to deployment resolvers like that in bndtools. Service properties are dynamic. For DS components, they can be changed by a configuration. So hardcoding then from the component XML into the osgi.service capability or requirement is wrong.

If you need the properties on the capability, you can of course add the specific capability you need to the bnd instructions.

Also, as of bnd 3.0, you no longer need to say `<_dsannotations>*</_dsannotations>` as `*` is the default value of `-dsannotations`.

**Comment by pkriens** [comment]
As agreed after discussing this on the bnd(tools) group

**Comment by sameera-jayasoma** [comment]
I  tried putting the following to the bnd instructions.

```
Provide-Capability: osgi.service;effective:=active;objectClass="org.wso2
 .carbon.kernel.startupresolver.RequiredCapabilityListener";capability-n
 ame="org.wso2.carbon.sample.deployer.mgt.Deployer";component-key=carbon
```
 
But in the generated manifest I can see following entries. Looks like BND has put the instruction specified by me as well as the auto generated header. Is it possible to avoid this duplication?

```
Provide-Capability: osgi.service;effective:=active;objectClass="org.wso2
 .carbon.kernel.startupresolver.RequiredCapabilityListener";capability-n
 ame="org.wso2.carbon.sample.deployer.mgt.Deployer";component-key=carbon
Provide-Capability: osgi.service;objectClass:List<String>="org.wso2.carb
 on.kernel.startupresolver.RequiredCapabilityListener"
```

Thanks,
Sameera.

**Comment by pkriens** [comment]
Can you send your bnd file and the manifest as attached files?

bnd merges the clauses of different capabilities. And having the manifest show 2 same headers is impossible since it is a Hashtable … So the header you provide can almost by definition not be the Provide-Capability header?

Kind regards,

	Peter Kriens

**Comment by sameera-jayasoma** [comment]
Hi Peter.

I've attached the requested files. Here I am using Maven Bundle Plugin 3.0.1 which uses 3.0 version of bnd.

Thanks,
Sameera.

[files.zip](https://github.com/bndtools/bndtools/files/189531/files.zip)

**Comment by pkriens** [comment]
The manifest only contains 1 Provide-Capability header, which is what is expected?

Kind regards,

	Peter Kriens

**Comment by sameera-jayasoma** [comment]
Hi Peter,

Apologies for the late reply. Yes. There is only one Provide-Capability header, but you can two see osgi.service capabilities in the header value as follows.

`
Provide-Capability: 
osgi.service;effective:=active;objectClass:List<String>="org.wso2.carbon.kernel.startupresolver.RequiredCapabilityListener";capability-name="org.wso2.carbon.sample.deployer.mgt.Deployer";component-key=carbon, osgi.service;objectClass:List<String>="org.wso2.carbon.kernel.startupresolver.RequiredCapabilityListener"
`

First is the one I put and the second one is the generated one.

**Comment by pkriens** [comment]
Ok. The second is likely generated by DS. I do not think we have a way to disable that. And we very consciously decided to not include properties because it creates very fragile systems. Properties are for the runtime only.

We would need a function to selectively enable/disable the requirement generation but I am not crazy about that. What is your use case?

**Comment by bjhargrave** [comment]
This is similar to https://github.com/bndtools/bnd/issues/1075. Some code which handled merging would be useful.

**Comment by pkriens** [comment]
Well, these capabilities are not identical ... Rules to decide what can be merged get very hairy extremely quickly

**Comment by djencks** [comment]
I don't think these capabilities can be merged.  As is, they state that there's one capability with the mentioned extra properties and a second capability without them.  I'd suggest that the requester come up with their own namespace for extra properties since osgi decided not to include other properties in the osgi.service namespace.
