### ISSUE TITLE
Renaming a package renames the project

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1303]
I had a package foo and a project foo. When renaming the package, the project was also renamed.

**Comment by njbartlett** [comment]
I've not been able to reproduce this.

**Comment by BryanHunt** [comment]
I have seen a case similar to this.  I had an API package that was imported by another project.  When I renamed the package, the project itself was not renamed, but the project in the Build Path in bnd.bnd was renamed.

**Comment by njbartlett** [comment]
So the reference in the -buildpath of the *other* project was renamed?

**Comment by BryanHunt** [comment]
Yes

**Comment by pkriens** [comment]
That could probably have been my case as well

**Comment by njbartlett** [comment]
Yes I can reproduce this problem. Thanks for the extra info.

**Comment by bjhargrave** [comment]
@gamerson Can you look at this?

**Comment by gamerson** [comment]
sure
