### ISSUE TITLE
Less restrictive project/workspace layout

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bndtools#1309]
Bndtools is very restrictive regarding the project/workspace layout.

I understand that the restriction that projects have to be in the same directory as the bnd workspace (project) originates from bnd. I have some problems with this, but I think I can get around those for some time.

Bndtools, however, introduces the additional restriction that the bnd workspace (project) must be a top level project in the Eclipse workspace. Combining this with the bnd restriction, this results in the fact that *all* my projects must be top level projects in the eclipse workspace. This is something that breaks my project organization completely.

If I were to provide a patch that fixes this, would it be accepted? Or is their some strong philosophical background for this requirement?

**Comment by njbartlett** [comment]
There is no philosophical objection as such. When Bndtools first started, there was a hard restriction in Eclipse that projects could neither be nested nor overlapping... there was no concept of a "top-level" project because everything was top-level! So we were simply fitting in with that reality.

My understanding is that this restriction has loosened somewhat in Eclipse, but we are not taking advantage of that loosening yet. I would like to see the ability to open multiple bnd workspaces in a single Eclipse workspace, but we are not ready for that because there are a number of singletons and assumptions throughout the code which would have to be revisited.

Contributions are welcome. It's more likely that you would be able to chip away at the problem than to solve it outright. Having said that, before writing any code I would ask you to clearly lay out your requirements for discussion.

**Comment by mnlipp** [comment]
> I would like to see the ability to open multiple bnd workspaces in a single Eclipse workspace

I'm thinking of something more humble than that. Personally, I currently don't have a use case for more than one bnd workspace in an Eclipse workspace. (It would nicely fit bnd's concepts, though [http://bnd.bndtools.org/chapters/130-concepts.html]). 

By introducing subprojects, Eclipse enables the user to define a project that is an "undertaking" or "solution" (the term used in MS Visual/Whatever). A stand-alone, self-contained Java application has always been a very special case. If you were striving for modularity and re-usability, a well designed application has always consisted of a main part and parts bundled as libraries. In Eclipse, those parts had to be projects, and due to this, traditionally the "solution" had to be a workspace (or a working set in a workspace).

With subprojects, the layout gets much more intuitive. The "solution" becomes an Eclipse project that can simply be imported as a project into the workspace (checking the "import subprojects", of course). And it shows as you'd expect it in the project explorer (using the hierarchical mode). If a solution consists of set of OSGi bundles, the subprojects are bndtools projects. Though in some cases it *might* make sense that the top project was the "bnd workspace project", I don't consider that a necessity. The top level project can be a simple resource project. It probably would be nice if it was at least a gradle project with the "top level activities" like building a distribution package, generating overall documentation or whatever. So the gradle related parts from cnf might move to the top level project, but well, this is for the future.

So what I propose is to use a different algorithm for searching for the bnd workspace (the cnf project). Currently, bndtools searches for a top level project of that kind in the workspace, although bnd itself actually only requires the bnd workspace to be a sibling of the project you're working with. If bndtools search algorithm was changed to search for a sibling cnf project of the project that is to be built (ignoring its relation to the workspace), it would be possible to have bndtools projects (and an accompanying bnd cnf project) that are subprojects of an Eclipse project.

It would still be an error condition if no cnf project was found. It would be a new error condition if more than one cnf project would be found as siblings of open bndtools projects. So we'd still have the restriction that all open bndtools projects must be siblings.

**Comment by mnlipp** [comment]
When I just tried to get a feeling about what to change, I found that bndtools actually already supports the project/subproject layout outlined above. Not only with "master", but (when I retried) also with the latest release.

I haven't got the slightest idea what I did wrong before; I *had* tested this several times. Please excuse me for wasting your time.

**Comment by njbartlett** [comment]
No problem. Thanks, these kind of well-thought out bug reports are always valuable even if we don't ultimately need to fix anything.
