### ISSUE TITLE
Classes found in the wrong directory

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bndtools#1318]
I have just checked out bndtools at commit aae2856f9771b0ef9b3b226ce9596d2e28c9d963.

bndtools.core fails to build with:

```
Classes found in the wrong directory: {enroute/osgi.enroute.template/_api_/bin/_package_/package-info.class=_package_.package-info, enroute/osgi.enroute.template/_api_/bin/_package_/_stem_.class=_package_._stem_}	bnd.bnd	/bndtools.core	line 1	Bndtools Problem Marker
```

I can get rid of the error by removing 
```
    enroute=resources/enroute
```
from `Include-Resource:` in bnd.bnd (line 46). (I assume this has undesired side effects.)

What strikes me as odd is that I cannot find "resources/enroute" in the Java Build Path/Libraries (Bnd Bundle Path) (before removing it from bnd.bnd, of course). I'm not an OSGi expert, but should resources enumerated in `Include-Resource` really be added to the project's class path?

**Comment by bjhargrave** [comment]
You need to be running the latest bndtools 3.2 dev releases to build the latest bnd or bndtools repos.
