### ISSUE TITLE
Allow to do the resolve step in a maven build

### ISSUE THREAD

**Issue by cschneider** [bndtools/bndtools#1319]
This is a follow up to the [discussion on the bndtools user list](https://groups.google.com/forum/#!topic/bndtools-users/cXxc29_cMsw).  

I would like to be able to do the whole build of a bndtools application using maven. Currently the main step missing there seems to be resolving the run bundles from requirements.

So there should be a maven plugin goal that takes a launch config and updates the run bundles. 

A typical use case for this would be that you have an existing launch config and runbundles that work for CXF 3.1.0 and you update the repository entry to point the the CXF 3.1.4 version. In this case the resolve step should be automatic as we would not expect to need to do changes in the requirements.
We just need new runbundles that reflect the new repository contents.

I am willing to implement this but I will need some pointers to where the resolve step happens today in code and where to add the new code to.

**Comment by cschneider** [comment]
I have implemented this in a maven plugin. See https://github.com/cschneider/osgi-maven-plugins/tree/master/bndrun-maven-plugin . I would be happy if this could be integrated in the bnd builds.

**Comment by bjhargrave** [comment]
I think you should make a PR against bndtools/bnd repo with your plugin as a contribution.

For future reference, the maven plugins are in the bndtools/bnd repo. This repo (bndtools/bndtools) is the Eclipse integration.

**Comment by bjhargrave** [comment]
See also https://github.com/bndtools/bnd/issues/1107 which can be the issue in the bndtools/bnd repo to reference in your PR.

**Comment by cschneider** [comment]
I created a pull request for the issue you linked.
