### ISSUE TITLE
Readme.txt of Bndtools Template Project contains wrong process instruction

### ISSUE THREAD

**Issue by nielsboogaard** [bndtools/bndtools#1321]
The [readme.txt](https://github.com/bndtools/bndtools/blob/master/org.bndtools.templates.template/shared/readme.txt) as packaged in the Bndtools Template Project contains a reference to a wrong process instruction. It states:

```
# don't process .img files
process.extra: !*.img
```
but it should be
```
# don't process .img files
process.before: !*.img
```
This is confusing when creating new templates based on the Template Project.

**Comment by bjhargrave** [comment]
Can you submit a PR?
