### ISSUE TITLE
Maven AetherRepository authentication - Eclipse Mars.2 startup hangs Password Required Artifactory realm login dialog - bndtools 3.1.1

### ISSUE THREAD

**Issue by buzz3791** [bndtools/bndtools#1323]
Originally reported on the bndtools-user forum
"Bug? Maven AetherRepository authentication - Eclipse Mars.2 startup hangs Password Required Artifactory realm login dialog - bndtools 3.1.1"
https://groups.google.com/d/msg/bndtools-users/ZzIEFLTCZmE/ywvVcU9GDgAJ

I'm encountering an annoyance when using the aQute.bnd.deployer.repository.aether.AetherRepository bnd plugin.  After adding the Aether repo, every time I startup Eclipse I get prompted (twice!) for my Artifactory credentials.  The Eclipse startup hangs.  Eclipse is showing:
1. The Eclipse splash window.
2. Two dialogs with the title "Password Required".  The dialogs contain:
2a. Connect to: arthost
2b. Artifactory Realm
2c. User name:
2d. Password
2c. OK and Cancel buttons.

I only see this "Password Required" prompt during Eclipse startup.  For example, I didn't see such a prompt when bndtools added the repo.

Environment:
Java 1.8.0_66
Eclipse Mars.2 (4.5.2)
Bndtools 3.1.1.REL-20160122-125321-g240736f
Artifactory OSS 3.7.0
https://bintray.com/artifact/download/jfrog/artifactory/artifactory-3.7.0.zip
https://bintray.com/jfrog/artifactory/jfrog-artifactory-oss-zip/3.7.0/view

The Artifactory instance is configured to require authentication i.e. Artifactory->Admin->Security->General->checkbox "Allow Anonymous Access" is unchecked.

I've configured the bnd AetherRepository in cnf/ext/repositories.bnd like this:

bnd-release    = https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles
-pluginpath: ${build}/cache/biz.aQute.repository.aether-latest.jar;url=${bnd-release}/biz.aQute.repository.aether/biz.aQute.repository.aether-latest.jar;
-plugin \
    aQute.bnd.deployer.repository.aether.AetherRepository; \
    name=Artifactory; \
    url=http://arthost:8082/artifactory/; \
    username=joe;password=joepass; \
    indexUrl=http://arthost:8082/artifactory/repo/.index/nexus-maven-repository-index.gz

Note that the new "Artifactory" repo shows up in the bndtools perspective Repositories view just fine.

The issue seems similar to this resolved m2e issue...
Bug 440273 - unexpected auth popup when accessing password-protected repositories
https://bugs.eclipse.org/bugs/show_bug.cgi?id=440273

**Comment by buzz3791** [comment]
Potential workaround is change Artifactory to allow anonymous access:
Artifactory->Security->General->checkbox Allow Anonymous Access->checked/enabled

**Comment by bjhargrave** [comment]
The aether repo is being replaced by MavenBndRepository which has setting for authentication.

**Comment by bjhargrave** [comment]
See <https://github.com/bndtools/bnd/wiki/Changes-in-3.2.0#maven-repository-support>.
