### ISSUE TITLE
biz.aQute.resolve and biz.aQute.repository should be published to maven central

### ISSUE THREAD

**Issue by cschneider** [bndtools/bndtools#1326]
I have written a plugin to do the resolve and export step in maven.
Currently it is a bit hard to get this running as two of the libraries I need are not available in maven repos.

So it would be great if you could add at least these two jars to the bundles you export to maven central. It would be even better of course if you could simply automatically export all bnd libs to maven central. 

This is what I currently do to publish them by hand:
mvn install:install-file -Dfile=biz.aQute.resolve/generated/biz.aQute.resolve-3.2.0.jar -DgroupId=biz.aQute.bnd -DartifactId=biz.aQute.resolve -Dversion=3.2.0-SNAPSHOT -Dpackaging=jar
mvn install:install-file -Dfile=biz.aQute.repository/generated/biz.aQute.repository-3.2.0.jar -DgroupId=biz.aQute.bnd -DartifactId=biz.aQute.repository -Dversion=3.2.0-SNAPSHOT -Dpackaging=jar

**Comment by bjhargrave** [comment]
Since these bundles include pom files, you don't need to specify `-DgroupId`, `-DartifactId`, or `-Dversion`.

For the 3.2 release, we can add these bundles to maven central. I think we can do the others as well depending upon how the new bnd maven repo support from Peter goes.
