### ISSUE TITLE
[usage question] [low priority] How to see workspace root files?

### ISSUE THREAD

**Issue by paulvi** [bndtools/bndtools#1329]
When new project is created in new workspace, a wizard pops up to create `cnf` project.
As  a project without within workspace without `cnd` can't be compiled, this seems to obligatory step to use bndtools.

When `cnf` project is created, it also created file in workspace root, however those files are not visible, even though they affect gradle build of component projects.

How to see workspace root files?

I only managed, with a special project with `.project` like below

```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>_Enide-BndToolsWorkspace</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
	</buildSpec>
	<natures>
	</natures>
	<linkedResources>
		<link>
			<name>.gitignore</name>
			<type>1</type>
			<locationURI>PARENT-1-PROJECT_LOC/.gitignore</locationURI>
		</link>
		<link>
			<name>build.gradle</name>
			<type>1</type>
			<locationURI>PARENT-1-PROJECT_LOC/build.gradle</locationURI>
		</link>
		<link>
			<name>gradle.properties</name>
			<type>1</type>
			<locationURI>PARENT-1-PROJECT_LOC/gradle.properties</locationURI>
		</link>
		<link>
			<name>settings.gradle</name>
			<type>1</type>
			<locationURI>PARENT-1-PROJECT_LOC/settings.gradle</locationURI>
		</link>
	</linkedResources>
</projectDescription>
```

Workspace root even with .project can't be imported.

**Comment by paulvi** [comment]
s

![screen1](https://cloud.githubusercontent.com/assets/1614482/14308770/d92e8a20-fc0a-11e5-984c-bcb7afbc0152.PNG)

**Comment by bjhargrave** [comment]
Usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.

**Comment by paulvi** [comment]
@bjhargrave Google is absent in China completely, and not all are using VPN (It is very slow nevertheless, because servers all not near)

Do you need Chinese users?

For the issue itself, it was addressed in https://github.com/bndtools/bndtools/issues/1331#issuecomment-206384867
