### ISSUE TITLE
.gitignore in workspace root should add more

### ISSUE THREAD

**Issue by paulvi** [bndtools/bndtools#1331]
`.gitignore` in workspace root should add more files like

```
.metadata
RemoteSystemsTempFiles
```

see https://github.com/paulvi/BndtoolsWorkspaceExample/blob/master/.gitignore

ref #1330

**Comment by fhuberts** [comment]
you should not put your eclipse workspace in the same place as the code

**Comment by paulvi** [comment]
The layout as in https://github.com/paulvi/BndtoolsWorkspaceExample was created by bndtools.
I just expect that `build.gradle`, `settings.gradle` and `cnf/` should be put into version control.

**Comment by fhuberts** [comment]
and they will when you to git add && git commit

**Comment by paulvi** [comment]
@fhuberts bndtools by default add `.gitignore` file in bndtools workspace. This issue is about 2 lines that should be added in the file by default.

**Comment by fhuberts** [comment]
see my first comment

**Comment by timothyjward** [comment]
> see my first comment

As Ferry said in his first comment:

> you should not put your eclipse workspace in the same place as the code

Eclipse adds lots of metadata and working folders to the workspace, making it extremely version control unfriendly. It is much better to create the Eclipse workspace in one folder, and then to put all of the projects in a different folder. This prevents all of the Eclipse-specific data from being tied up with the version controlled files.

To put it another way. If you have an existing version controlled build which you check out, you would not normally use that checkout directory as the root of the Eclipse workspace. Instead you would import the projects into an Eclipse workspace that used a different working folder.

**Comment by bjhargrave** [comment]
See http://enroute.osgi.org/qs/200-workspace.html where the tutorial has the eclipse workspace in a different folder than the git repo.

**Comment by paulvi** [comment]
@fhuberts @timothyjward As a user, I just followed what bndtools v3.1 wizards were suggesting and got bnd workspace on the same level as Eclipse workspace, it was misleading users, but as @bjhargrave noted, in v3.2 it will be 

> Just create a new Eclipse workspace and then do `New/Other/Bndtools/Bnd OSGi Workspace`.

I have successfully checked out https://github.com/paulvi/BndtoolsWorkspaceExample in a new Eclipse workspace subfolder and it seems to work.

- [ ] Current users should be let know about some files that are in Eclipse unaccessible workspace root folder.
