### ISSUE TITLE
OSGi enRoute workspace: cnf ends up in the Eclipse workspace

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1332]
I just created a new workspace using the enRoute template. I explicitly indicated I wanted it to use another bnd workspace so I filled this in. However, the cnf ended up in the Eclipse workspace. This was very likely caused by the fact that the Eclipse workspace already contained a cnf directory.

**Comment by paulvi** [comment]
This is not related to 1 bnd workspaces in one eclipse workspaces limitation https://github.com/osgi/osgi.enroute.site/pull/79 ?

**Comment by paulvi** [comment]
I have just tried new Eclipse workspace (Java perspective is default), new enRoute project and got rather messed UX

![bndtools-enroute](https://cloud.githubusercontent.com/assets/1614482/14377869/b40c5aec-fda4-11e5-99f6-098fb29a830a.PNG)

![bndtools-enroute-2](https://cloud.githubusercontent.com/assets/1614482/14377877/c56877da-fda4-11e5-8df9-1f2740105ef4.PNG)

**Comment by paulvi** [comment]
Please note 

> Last path segment must be 'cnf'.

when I add `\cnf` (`D:\Workspaces\Enide-BndTools-enRoute-bndworkspace\cnf`) I am logically end-up with a new project not inside new bdn workspace and in error state similar to https://github.com/bndtools/bndtools/issues/1338

**Comment by pkriens** [comment]
You seem to be mixing an OSGi enRoute template, which requires an OSGi enRoute workspace setup, with a standard Bndtools template? The OSGi enRoute template requires the repositories, gradle, and a number of other things to be setup. 

Did you follow the OSGi enRoute Quick Start Tutorial? [1]

It looks like you’re using 3.1? In 3.2 we can install the workspace from Github through Bndtools. Very nicely provided by Neil Bartlett?

Kind regards,

	Peter Kriens

[1]: http://enroute.osgi.org/qs/050-start.html <http://enroute.osgi.org/qs/050-start.html>

**Comment by paulvi** [comment]
@pkriens I am sorry, I have mixed a few issues together e.g. #1339 

Right now, I have just created new enRoute project in a new Eclipse workspace using 3.1
and just followed what IDE was suggesting.

**Comment by pkriens** [comment]
You need to start with an OSGi enRoute workspace ... In the further future the OSGi enRoute templates will come from the workspace setup so this confusion won't happen then. 3.4 or so.

**Comment by paulvi** [comment]
Commented in https://github.com/bndtools/bndtools/issues/1342

for now the quickest fix for this would be to extend description in the template, e.g.

> You need to start with an OSGi enRoute workspace  <link>
what to do in version 3.1 or version 3.2
