### ISSUE TITLE
new project out of bnd workspace is immediately in error state

### ISSUE THREAD

**Issue by paulvi** [bndtools/bndtools#1338]
new project created with wizards out of bnd workspace is immediately in error state

![bndtools new project out of bnd workspace is immediately in error state](https://cloud.githubusercontent.com/assets/1614482/14377372/da296fa6-fda1-11e5-8fee-14ce98eadf51.PNG)

**Comment by paulvi** [comment]
![bndtools new project out of bnd workspace unresolved types](https://cloud.githubusercontent.com/assets/1614482/14377587/0fc594f4-fda3-11e5-863f-e2d6db67d8c8.PNG)

**Comment by bjhargrave** [comment]
Looks like a dup of #1277.
