### ISSUE TITLE
Workflow Story - User should be promted to create bnd workspace before new project wizard opens

### ISSUE THREAD

**Issue by paulvi** [bndtools/bndtools#1339]
Workflow Story 

1. User should be prompted to create bnd workspace before creating new bndtools project.

2. Wizard should show what bnd workspace this new bndtools project will belong to.

currently wizard for bnd workspace pop-ups afterwards

![bndtools-enroute](https://cloud.githubusercontent.com/assets/1614482/14377869/b40c5aec-fda4-11e5-99f6-098fb29a830a.PNG)

![bndtools-enroute-2](https://cloud.githubusercontent.com/assets/1614482/14377877/c56877da-fda4-11e5-8df9-1f2740105ef4.PNG)

Please note 

> Last path segment must be 'cnf'.

when I add `\cnf` (`D:\Workspaces\Enide-BndTools-enRoute-bndworkspace\cnf`) I logically end-up with a new project not inside new bdn workspace and in error state similar to https://github.com/bndtools/bndtools/issues/1338

**Comment by bjhargrave** [comment]
Changed for bndtools 3.2.
