### ISSUE TITLE
personal feedback on bnd and bndtools 3.1

### ISSUE THREAD

**Issue by paulvi** [bndtools/bndtools#1342]
I don't need solution for my pet project. If I needed only for me, I would not raise ticket for every bug I come across. I am looking for tools to give to my team. And I can't recommend tool, that lead developers to wrong direction (putting bnd workspace inside Eclipse workspace #1331 @fhuberts ), or gives error when stepping aside from main line (like creating project not for a bnd workspace https://github.com/bndtools/bnd/issues/1399 https://github.com/bndtools/bnd/issues/1398) or hide details that leads to not easy to understand error (https://github.com/bndtools/bndtools/issues/1329). 

Those may be UX issues. But for now for my team it is better to wait next release #1341 . A good tool is to encourage for experiments, not to force in one direction.
I am also concern wether new users are easy to get onboard by learning one new trick at a time https://github.com/bndtools/bnd/issues/1394 .

**Comment by bjhargrave** [comment]
Usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bndtools#feedback>.

**Comment by paulvi** [comment]
reason was https://github.com/bndtools/bnd/issues/1393 China issue
