### ISSUE TITLE
When opening bnd.bnd file in eclipse with a class with incomplete annotations an exception is thrown

### ISSUE THREAD

**Issue by cbrommer** [bndtools/bndtools#1351]
![image](https://cloud.githubusercontent.com/assets/10833336/14778659/817d8ef6-0ad4-11e6-8aa7-efba0b75c29e.png)

IllegalStateException:: the class must be annotated with either one of the following types: [....]

**Comment by bjhargrave** [comment]
This exception is being throw by the `org.apache.felix.dm.annotation.plugin`... plugin which is not part of Bnd/Bndtools. Perhaps you should file a bug with them about this exception?

**Comment by bjhargrave** [comment]
Not a bnd issue.
