### ISSUE TITLE
Bnd Project Editor - Activator creation

### ISSUE THREAD

**Issue by fipro78** [bndtools/bndtools#1353]
I created a simple auto configurator for Equinox and tried to do this with Bndtools. For this I need an Activator, and as I'm used to PDE I expected that a click on the Activator link in the Bnd Project Editor would open up a wizard for the creation of the class. 

With Bndtools 3.1.1 this is not working. Not sure if it ever worked. I just started with Bndtools. 

When I create the Activator manually and enter the full qualified name of the Activator class in the Bnd Project Editor - Activator field, the link opens the Activator class in a Java editor (which is the intended behavior).

Just a minor issue. Fixing this would improve the user experience, but it is not a critical issue.

**Comment by njbartlett** [comment]
This is the intended behaviour. An activator is just a class and you can create it with the standard New Class wizard. After that, you can start typing the name in the Activator field, which will offer completions based on the classes found in the project. After you have defined an activator, the link takes you to the class.

My general advice is never to write activators (you should write DS components instead) so I don't really want to do any work to make it easier to make activators.

**Comment by fipro78** [comment]
> My general advice is never to write activators (you should write DS components instead)

I totally agree and I give that advice to my team colleagues for a while now. There are very rare cases nowadays where an Activator is needed, e.g. an Equinox configurator to automatically install and activate bundles in a specific directory. For sure this could also be done in a DS component, but would force developers to configure the auto activation of the ds bundle in the config.ini additionally to the configurator. To simplify things I decided to use an Activator instead to reduce the amount of configuring bundles. I think about publishing that simple configurator on GitHub to see if this would work. Then maybe we can introduce some configuration property in the existing Equinox configurators to perform auto activation. A long lasting discussion as you teached me. :-)

BTW, thanks for all your very valuable feedback in various channels!

**Comment by njbartlett** [comment]
Thanks. Yes I know there are cases where activators are needed, essentially in bootstrapping. I just don't think it's worth investing time in this area compared to other areas.

FWIW I kind of wish DS was part of Core OSGi so we didn't have to worry about these kinds of issues.

**Comment by fipro78** [comment]
> FWIW I kind of wish DS was part of Core OSGi so we didn't have to worry about these kinds of issues.

That would indeed solve several issues with regards to startup orders aswell
