### ISSUE TITLE
Version update warning dialog shouldn't be shown for release

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bndtools#1356]
There is a handy dialog which comes up if you try to update bundle version via Release Bundles in Eclipse, which warns of any versions which are defined as macros and will be overwritten by the tool. This is nice and all, but the warning also shows up when it doesn't need to, if you just perform a release without updating the versions. This is a little confusing, as it seems to imply the versions will be modified when they won't... The main problem though is that it teaches you to just ignore the warning, and I think it would be very easy to accidentally do a version update and kill all the macros without even realising it at first.

**Comment by pkriens** [comment]
Could you propose a PR?

**Comment by eliasvasylenko** [comment]
Sure thing.
