### ISSUE TITLE
Add current project's sources to debug configuration

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bndtools#1366]
When I click "Debug OSGi" in the "Run" tab of the bnd.bnd editor for the first time, Bndtools creates a new Eclipse Run/Debug configuration for the project.

Regrettably, the configuration doesn't include the current project's source in the "Source Lookup Path". Although this can easily be fixed in the "Edit Source Lookup Path" dialog by the experienced Eclipse user, it is annoying and quite irritating for the less experienced user.

**Comment by BryanHunt** [comment]
Related to this, I've been doing a lot of debugging of bundles released from another project.  I've been creating a "debug" project and adding the bundle I want to debug as a build dependency.  I can then open the component using cmd-shift-t and set a breakpoint just fine.  When the debugger hits the breakpoint, it can't find the source and I must Edit Source Lookup Path.  It would greatly help productivity if this whole story got some love.

**Comment by gamerson** [comment]
In https://github.com/bndtools/bndtools/issues/1395 we are looking into overriding the default Eclipse launch calculation of runtime classpath entries to be much more precise and it should be able to address issues @mnlipp and @BryanHunt  are seeing.
