### ISSUE TITLE
New workspace wizard: legacy templates do not work

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1373]
For the 'Bndtools Bundle Hub' choice I get an empty list of files to generate, and 'next' and 'finish' are greyed out.

major

**Comment by fhuberts** [comment]
New workspace wizard

**Comment by fhuberts** [comment]
bndtools 3.2.0.REL

**Comment by njbartlett** [comment]
I don't quite follow... can you show a screenshot?

**Comment by fhuberts** [comment]
![1](https://cloud.githubusercontent.com/assets/635705/15396571/079501a2-1ddd-11e6-8445-b0abce2c26a0.png)
![2](https://cloud.githubusercontent.com/assets/635705/15396572/07a7ed76-1ddd-11e6-9f6f-1bdef96d0351.png)
![3](https://cloud.githubusercontent.com/assets/635705/15396574/07c32b9a-1ddd-11e6-8c72-10aa2aa5b04c.png)
![4](https://cloud.githubusercontent.com/assets/635705/15396573/07bba348-1ddd-11e6-9de6-636e15e2ed5e.png)

**Comment by njbartlett** [comment]
Ah okay. I am able to reproduce the problem.
