### ISSUE TITLE
${warning} bnd macro not reported correctly in the Eclipse Problems view.

### ISSUE THREAD

**Issue by nport** [bndtools/bndtools#1376]
BndTools version: 3.2.0.REL
OS: Windows 10

It seems that the ${warning} bnd macro used in the .bnd files present on an newly create enroute project are not correctly bound to the correct project files.
1.  Create an empty Eclipse workspace
2.  Create in this Eclipse workspace a BndTools Workspace of type osgi/workspace 
3. Create a BndTools enroute Project named myproject.example. The newly created project will contain four .bnd files (one for the project itself, and three subprojects).

The resulting project will have some warnings, due to the ${warning} macros present in the .bnd files. 

Some issues here:
- I would expect to have 4 warnings (we have 4 .bnd files, each one with this macro inside), but only 3 warnings are reported.
- In the Problems view, if I double click on one of the 3 listed warnings, the main bnd.bnd file is opened, instead of the .bnd file this warning report belongs.
- In the Package explorer view no warning icon appears beside the .bnd files (it is only on the main bnd.bnd file).

**Comment by pkriens** [comment]
This should be improved in PR bnd#2049

Likely only 3 warnings were seen because the bnd.bnd was overridden.
