### ISSUE TITLE
JPA support

### ISSUE THREAD

**Issue by gadieichhorn** [bndtools/bndtools#1380]
any recommendations for using JPA/persistence?

I noticed the enRoute sample is deprecated (the blog sample) and there is no news about when it will be updated with BNDtools 3.2.0 and new enRoute samples.

our requirements:
1. would like to use Derby for tests (in memory)
2. EclipseLink for production.
3. use config admin for creating factory instances with different data sources per service instance.
4. also be great to be able to test it in integration (black box) phase with derby or similar.

thanks,

**Comment by mitpjones** [comment]
Have a look at http://aries.apache.org/modules/transactioncontrol.html and https://github.com/apache/aries/tree/trunk/tx-control, it should cover all the requirements you have listed (see the EclipseLink itest https://github.com/apache/aries/blob/trunk/tx-control/tx-control-jpa-itests/src/test/java/org/apache/aries/tx/control/itests/XAEclipseLink_2_6_0_Test.java). The solution is backed by Transaction Control Service RFC-221 which is still in-progress but the majority of the work has been completed. Peter Kriens should be able to give you an idea of what plans if any he has for incorporating it into the enRoute project.

Regards,

Tim

**Comment by cschneider** [comment]
Take a look at https://github.com/cschneider/bndtools-tutorials/tree/master/tasklist-ds

It should give you a good idea of what bundles and config you need. I used a special index plugin to create a local bnd repo index. Using this it is quite easy to change versions as it is all based on a pom with dependencies.

As soon as tx control is released I will also do an example for it.

**Comment by bjhargrave** [comment]
Usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.
