### ISSUE TITLE
Eclipse runs out of file descriptors

### ISSUE THREAD

**Issue by lukewink** [bndtools/bndtools#1386]
On Linux, I noticed that eclipse ran out of file descriptors.  It was using 4096 total, and 4000 of those were on the /cnf/cache/wrapper/lock file.

We were not experiencing any issues like this when we were using the old cnf workspace layout (the one that was generated from bndtools 2.4).

Each time I clean all the projects to force eclipse to rebuild everything, it will use an additional 250 file descriptors.

**Comment by bjhargrave** [comment]
I suspect issue has something to do with https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/deployer/repository/wrapper/InfoRepositoryWrapper.java#L55. It would appear there are an excessive number of PersistentMaps on the /cnf/cache/wrapper folder.

@lukewink What does you workspace -plugin configuration look like? Are you using wrappers?

**Comment by lukewink** [comment]
Here is what the build.bnd file looks like (everything should match the generated build.bnd file expect for -plugin.5):
`
-plugin.1.Central: \
    aQute.bnd.deployer.repository.wrapper.Plugin; \
        location = "${build}/cache/wrapper"; \
        reindex = true, \
    aQute.bnd.jpm.Repository; \
        includeStaged = true; \
        name = Central; \
        location = ~/.bnd/shacache; \
        index = ${build}/central.json

-plugin.2.Local: \
    aQute.bnd.deployer.repository.LocalIndexedRepo; \
        name = Local; \
        pretty = true; \
        local = ${build}/local

-plugin.3.Templates: \
    aQute.bnd.deployer.repository.LocalIndexedRepo; \
        name = Templates; \
        pretty = true; \
        local = ${build}/templates

-plugin.4.Release: \
    aQute.bnd.deployer.repository.LocalIndexedRepo; \
        name = Release; \
        pretty = true; \
        local = ${build}/release

-plugin.5.MyCompany: \
    aQute.bnd.deployer.repository.FixedIndexedRepo;readonly=false;name=MyCompany ThirdParty;locations=http://MyCompanyUrl/ThirdParty/index.xml.gz,\
    aQute.bnd.deployer.repository.FixedIndexedRepo;readonly=false;name=MyCompany Release;locations=http://MyCompanyUrl/Release/index.xml.gz

-releaserepo: Release
-baselinerepo: Release

# JUnit
junit: org.apache.servicemix.bundles.junit; version=4.12
`

**Comment by pkriens** [comment]
Mitigated but not solved yet

**Comment by rotty3000** [comment]
Could you test again after this merge? https://github.com/bndtools/bnd/pull/1514

**Comment by lukewink** [comment]
I am unable to reproduce the issue with Bndtools 3.3.0.DEV-20160622
