### ISSUE TITLE
Field injection leads to error for Map.Entry type

### ISSUE THREAD

**Issue by fipro78** [bndtools/bndtools#1405]
I tried was to use the Map.Entry field type. The DS 1.3 spec says: "An unmodifiable Map.Entry whose key is an unmodifiable Map containing the service properties of the bound service, as above, and whose value is the bound service object." So I tried the following:

    @Component
    public class StringInverterCommand {

	    @Reference
	    private Map.Entry<Map<String, ?>, StringInverter> serviceMap; 
	
	    public void invert(String input) {
		  System.out.println("From map: " + serviceMap.getValue().invert(input));
	    }
    }

But this leads to an error during the generation of the component. It says _java.lang.StringIndexOutOfBoundsException: String index out of range: -1_

**Comment by bjhargrave** [comment]
This issue should be in the bnd repo. This repo (bndtools) is for the Eclipse plugins of bndtools. The people who work on the core bnd function are working in the other repo.

We have a test case for this which passes: https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java#L2537

Are you using the OSGi DS annotations (and not the Felix or bnd annotations)? Are you using the latest release of bnd (3.2)?

**Comment by fipro78** [comment]
I'm using bndtools 3.2 and the OSGi DS annotations in Eclipse Neon.
Am 23.06.2016 20:41 schrieb "BJ Hargrave" <notifications@github.com>:

**Comment by bjhargrave** [comment]
OK, then please open a new issue in the bnd repo for this and provide a small github repo which demonstrates the bug. Thanks.
