### ISSUE TITLE
Improve the spacing or size of Resolve/Run view

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bndtools#1406]
On a HiDPI display the Resolve/Run view is very hard, if not impossible, to use for editing Runtime Properties.

![resolve-run](https://cloud.githubusercontent.com/assets/146764/16178278/855f8138-3611-11e6-9f69-f7fdca11f0aa.png)

Note that it's not possible to resize the panels vertically so I'm forced to use source view to edit these.

**Comment by lostiniceland** [comment]
Could be fixed by [issue 1412](https://github.com/bndtools/bndtools/issues/1412). I will add a task there for highDPI
