### ISSUE TITLE
add an import suggestion for packages from repositories

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bndtools#1408]
It would be fantastic if bndtools could provide import suggestions from exports available in the repositories which would result in a `-buildpath` addition.

**Comment by lostiniceland** [comment]
It sounds like a very nice feature, but I suspect it would be very easy to end up with a cyclic dependency, since all (exported) packages would be visible in code-completion.

**Comment by kriegfrj** [comment]
Is this a duplicate of #1589?
