### ISSUE TITLE
Gradle does not build form command

### ISSUE THREAD

**Issue by daghanacay** [bndtools/bndtools#1410]
I am using BndTool V3.2.0.REL-20160517-162512-g3a83c33. I am following http://enroute.osgi.org/tutorial_base/800-ci.html

On the command line I have executed 

./gradlew export.com.acme.prime.eval --debug

I get the following error

21:24:07.273 [ERROR] [org.gradle.api.Task] Error  : Failed to load plugin aQute.bnd.repository.maven.provider.MavenBndRepository;releaseUrl="https://repo.maven.apache.org/maven2/";name=Central, error: aQute.bnd.repository.maven.provider.MavenBndRepository not found, parent:  org.gradle.internal.classloader.MutableURLClassLoader@1237e0be urls:[] exception:java.lang.ClassNotFoundException: aQute.bnd.repository.maven.provider.MavenBndRepository 
21:24:07.274 [ERROR] [org.gradle.api.Task] Error  : Cannot load the plugin aQute.bnd.repository.maven.provider.MavenBndRepository
21:24:07.274 [ERROR] [org.gradle.api.Task] Error  : isgi.enroute.examples.prime :Failed to load plugin aQute.bnd.repository.maven.provider.MavenBndRepository;releaseUrl="https://repo.maven.apache.org/maven2/";name=Central, error: aQute.bnd.repository.maven.provider.MavenBndRepository not found, parent:  org.gradle.internal.classloader.MutableURLClassLoader@1237e0be urls:[] exception:java.lang.ClassNotFoundException: aQute.bnd.repository.maven.provider.MavenBndRepository 
21:24:07.275 [ERROR] [org.gradle.api.Task] Error  : isgi.enroute.examples.prime :Cannot load the plugin aQute.bnd.repository.maven.provider.MavenBndRepository

**Comment by bjhargrave** [comment]
You should open gradle plugin issues in the bnd repo.

I suspect you are using an older gradle plugin. You need to use 3.2 for the MavenBndRepository support (since it is new with 3.2). What is the version in your gradle.properties file?

**Comment by daghanacay** [comment]
I will check but i was following the tutorial after installing the latest bndtools plugin. If issue continues then i will create another bug report in bnd repository. Thanks.
