### ISSUE TITLE
Marketplace install fails in Neon

### ISSUE THREAD

**Issue by paulbakker** [bndtools/bndtools#1416]
When installing bndtools from the marketplace in Neon:

![screen shot 2016-06-23 at 10 25 19](https://cloud.githubusercontent.com/assets/109484/16296503/db2d6170-392c-11e6-8242-267ac2a15e73.png)

**Comment by timothyjward** [comment]
This looks like a Java 9 problem. Does Neon actually support Java 9?

Tim

Sent from my iPhone

On 23 Jun 2016, at 09:26, Paul Bakker <notifications@github.com<mailto:notifications@github.com>> wrote:


When installing bndtools from the marketplace in Neon:

[screen shot 2016-06-23 at 10 25 19]<https://cloud.githubusercontent.com/assets/109484/16296503/db2d6170-392c-11e6-8242-267ac2a15e73.png>

-

**Comment by paulbakker** [comment]
You're right, Neon decided to put my jdk9 install in it's eclipse.ini. Clearly not a bndtools problem, and I verified it works with jdk8.
