### ISSUE TITLE
Bnd OSGi Launch configuration will by itself remove Bnd Dependencies source container 

### ISSUE THREAD

**Issue by gamerson** [bndtools/bndtools#1444]
The Bnd OSGi Launcher launch configuration when it is created initially has two source containers under the "source tab" in the launch configuration

- Default
- Bnd Dependencies

This is correct.  However, if you "edit" an existing launchconfiguration and you "expand" the Bnd Dependencies or the "Default" containers just to view them and then you try to exit the "launch configuration" dialog, Eclipse prompts you for "saving" the changes to the launch configuration.  However, it is unclear what "changes" have been made because we simply just expanded the "Dependencies" node in the source view.  

When you "save" the changes and then go back to that launch configuration the "Bnd Dependencies" source container is gone and then it breaks source lookup.   I've posted a screencap of this error:

http://g.recordit.co/MAHdgTPkjI.gif

**Comment by gamerson** [comment]
I don't know how long this launch configuration source container bug has been around, but I can try to take a look before 3.3 is wrapped up.

**Comment by bjhargrave** [comment]
> I don't know how long this launch configuration source container bug has been around, but I can try to take a look before 3.3 is wrapped up.

Thanks
