### ISSUE TITLE
JUnit test fails when running gradle build

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1466]
I have a JUnit test that works just fine when run within the IDE, but fails when running the gradle build.  I get the following error:

```
net.springfieldusa.data.auth.comp.junit.tests.TestEntityAuthorizationComponent > testIsDeleteAuthorizedForValidPrincipalIsNotOwner FAILED
    java.lang.NoClassDefFoundError at TestEntityAuthorizationComponent.java:45
        Caused by: java.lang.ClassNotFoundException at TestEntityAuthorizationComponent.java:45
```

TestEntityAuthorizationComponent.java:45 is: `securityService = mock(SecurityService.class);`

The project is located here: https://github.com/BryanHunt/web-in-a-box/tree/next

**Comment by bjhargrave** [comment]
What is the full exception from the junit output?

**Comment by bjhargrave** [comment]
Also, this issue belongs in the bnd repo rather than the bndtools repo.

**Comment by BryanHunt** [comment]
Moved to https://github.com/bndtools/bnd/issues/1593
