### ISSUE TITLE
Workspace template URL changes after value set

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1471]
Using Bndtools	3.3.0.DEV-20160816-142142-ge312869

Starting with an empty workspace, open Preferences and set the following Raw Git Clone URL's:

https://github.com/BryanHunt/workspace; name=Rest; branch=origin/rest
https://github.com/BryanHunt/workspace; name=Web; branch=origin/web

Click OK

![preferences_and_test_workspace_-_bndtools_-_eclipse](https://cloud.githubusercontent.com/assets/504299/17715551/3ca6d432-63ca-11e6-8837-3077bafc1fd7.jpg)

Create a new Bnd OSGi Workspace and notice that the Web template URL was changed to:

https://github.com/BryanHunt/workspace~

![test_workspace_-_bndtools_-_eclipse](https://cloud.githubusercontent.com/assets/504299/17715577/661d5534-63ca-11e6-89a8-d13770203ed7.jpg)

**Comment by seanbright** [comment]
This is because we are using `aQute.bnd.header.Parameters` to store these settings. We use the clone URL as the key and the `Parameters` class disambiguates by appending a `~` to duplicate keys.

**Comment by seanbright** [comment]
Serializing the prefs to JSON instead of using `Parameters.toString()` might be better.
