### ISSUE TITLE
GitHub repository workspace template does not work

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#1473]
Bndtools	3.3.0.DEV-20160816-142142-ge312869

Open Preferences and add a new GitHub repository workspace template:  BryanHunt/workspace on branch "rest".  Click Validate and notice that validation was successful.

![preferences](https://cloud.githubusercontent.com/assets/504299/17738456/f4ea2328-6456-11e6-8a8e-e38a29d97331.jpg)

Create a new Bnd OSGi Workspace and pick the GitHub template BryanHunt/workspace.  Click Next and see the error: Ref rest can not be resolved.

![bndtools_test_-_java_-_eclipse](https://cloud.githubusercontent.com/assets/504299/17738526/2fbf9320-6457-11e6-93bd-6610efcea5af.jpg)

**Comment by rotty3000** [comment]
It's strange because I just used this on HEAD of bndtools yesterday using this github repo:

https://github.com/rotty3000/osgi.web.boot

**Comment by rotty3000** [comment]
granted it's using the master branch of that repo... so maybe it's the branch support that isn't working properly.

**Comment by seanbright** [comment]
@BryanHunt try using **origin/rest** as the branch.

**Comment by BryanHunt** [comment]
origin/rest works :)
