### ISSUE TITLE
Missing close/dismiss button in "Errors in running OSGi Framework" message box.

### ISSUE THREAD

**Issue by nport** [bndtools/bndtools#1498]
In case of runtime errors while debugging a bndrun configuration, bndtools display the attached dialog.
This dialog do not have a close or dismiss button (i.e. for instance a x on the upper corner).
It can be dismissed only by clicking with the mouse on the dialog and then click with the mouse outside the dialog. 

![runerror](https://cloud.githubusercontent.com/assets/6675853/17890498/b564f1a8-6936-11e6-8558-9a51e8dfa9c0.png)

**Comment by seanbright** [comment]
I've added both a "Dismiss..." hyperlink in the dialog at the bottom right:

![image](https://cloud.githubusercontent.com/assets/114601/18279562/f8998306-7423-11e6-8a8b-9bb04e46c8e1.png)

And also a Close action in the drop down menu on the upper right (not pictured).
