### ISSUE TITLE
Removing @RunWith(MockitoJUnitRunner.class) from ExampleIntegrationTest deadlocks Gradle CLI build in :test :check

### ISSUE THREAD

**Issue by vorburger** [bndtools/bndtools#1527]
Here is a "fun" bug I've found by coincidence while playing around...

Removing @RunWith(MockitoJUnitRunner.class) from ExampleIntegrationTest deadlocks Gradle CLI build in :test :check!

This is easily reproducible by creating a New Bnd OSGi Project from template "Integration Testing". Running ExampleIntegrationTest in-IDE works, of course. Likewise, initially a ../gradlew build in it works too, of course, everything hunky dory:

```
:demo:check
Tests run  : 1
Passed     : 1
```

Now remove the `@RunWith(MockitoJUnitRunner.class)` from the ExampleIntegrationTest - the example doesn't use Mockito, and I wasn't planning to use it for my [first enRoute integration test](http://enroute.osgi.org/tutorial_base/600-testing.html), so removed. Now re-run the Gradle build from the CLI, and watch it get "stuck" forever (deadlock) here:

```
:demo:test UP-TO-DATE
> Building 81% > :demo:check
```

A `jstack PID` (where _PID_ is the one of `Launcher` shown by `jps`) shows this:
```

2016-09-07 23:23:01
Full thread dump OpenJDK 64-Bit Server VM (25.102-b14 mixed mode):

"Attach Listener" #22 daemon prio=9 os_prio=0 tid=0x00007f557c001000 nid=0x663e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"FelixStartLevel" #17 daemon prio=5 os_prio=0 tid=0x00007f55c41fa000 nid=0x65f7 in Object.wait() [0x00007f559acc4000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000075aff66d0> (a java.util.ArrayList)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:283)
	- locked <0x000000075aff66d0> (a java.util.ArrayList)
	at java.lang.Thread.run(Thread.java:745)

"FrameworkWaiter" #16 prio=5 os_prio=0 tid=0x00007f55c41f9000 nid=0x65f6 in Object.wait() [0x00007f559aac2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000075b17b250> (a org.apache.felix.framework.util.ThreadGate)
	at org.apache.felix.framework.util.ThreadGate.await(ThreadGate.java:79)
	- locked <0x000000075b17b250> (a org.apache.felix.framework.util.ThreadGate)
	at org.apache.felix.framework.Felix.waitForStop(Felix.java:1073)
	at aQute.launcher.Launcher$2.run(Launcher.java:670)

"FelixFrameworkWiring" #15 daemon prio=5 os_prio=0 tid=0x00007f55c41bd000 nid=0x65f5 in Object.wait() [0x00007f559a9c1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000075aff6650> (a java.util.ArrayList)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.framework.FrameworkWiringImpl.run(FrameworkWiringImpl.java:172)
	- locked <0x000000075aff6650> (a java.util.ArrayList)
	at java.lang.Thread.run(Thread.java:745)

"FelixDispatchQueue" #10 prio=5 os_prio=0 tid=0x00007f55c41e3800 nid=0x65f0 in Object.wait() [0x00007f559b1f0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000075aff6568> (a java.util.ArrayList)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.felix.framework.util.EventDispatcher.run(EventDispatcher.java:1123)
	- locked <0x000000075aff6568> (a java.util.ArrayList)
	at org.apache.felix.framework.util.EventDispatcher.access$000(EventDispatcher.java:55)
	at org.apache.felix.framework.util.EventDispatcher$1.run(EventDispatcher.java:103)
	at java.lang.Thread.run(Thread.java:745)

"Timer-0" #9 daemon prio=5 os_prio=0 tid=0x00007f55c415c800 nid=0x65ef in Object.wait() [0x00007f559b2f1000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000075a7e0f20> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000075a7e0f20> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Service Thread" #8 daemon prio=9 os_prio=0 tid=0x00007f55c40d3000 nid=0x65ed runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f55c40ce000 nid=0x65ec waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f55c40cc800 nid=0x65eb waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f55c40bf000 nid=0x65ea waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f55c40bd000 nid=0x65e9 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f55c4093000 nid=0x65e8 in Object.wait() [0x00007f559b9f8000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000075a708e98> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x000000075a708e98> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f55c408e800 nid=0x65e7 in Object.wait() [0x00007f559baf9000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000075a706b40> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000075a706b40> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007f55c4009800 nid=0x65df in Object.wait() [0x00007f55cb0f0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000075bedfbe8> (a java.util.Vector)
	at java.lang.Object.wait(Object.java:502)
	at aQute.junit.Activator.automatic(Activator.java:193)
	- locked <0x000000075bedfbe8> (a java.util.Vector)
	at aQute.junit.Activator.run(Activator.java:142)
	at aQute.launcher.Launcher$5.call(Launcher.java:1198)
	at aQute.launcher.Launcher$5.call(Launcher.java:1196)
	at aQute.launcher.Launcher.run(Launcher.java:278)
	at aQute.launcher.Launcher.main(Launcher.java:87)

"VM Thread" os_prio=0 tid=0x00007f55c4084800 nid=0x65e6 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f55c401e000 nid=0x65e2 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f55c4020000 nid=0x65e3 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f55c4021800 nid=0x65e4 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f55c4023800 nid=0x65e5 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f55c40d5800 nid=0x65ee waiting on condition 

JNI global references: 43

```

I'm filing this bug in this repo just because I found the [source of the template containing ExampleIntegrationTest here](https://github.com/bndtools/bndtools/search?utf8=%E2%9C%93&q=ExampleIntegrationTest); the root cause of this problem may lay elsewhere, of course.

**Comment by bjhargrave** [comment]
There is no bug here per se. You changes the test bundle so that  no test cases are available runtime in the launched framework. The launcher is waiting for the test cases to "appear" and they never do, so the execution never completes.

**Comment by vorburger** [comment]
@bjhargrave thanks for closing this and giving me the opportunity to dig into it and learn something... ;-)

I meanwhile figured out that this is related to this line in the bnd.bnd:

```
# Discover and run all test cases annotated with the @RunWith annotation
Test-Cases: ${classes;CONCRETE;ANNOTATED;org.junit.runner.RunWith}
```

To me as an end-user, this seems non-intuitive and problematic on two levels:

1. If I'm not using Mockito in my test, one should be able to remove the `@RunWith(MockitoJUnitRunner.class) `from e.g. ExampleIntegrationTest and it should still work. Mockito has nothing to do with OSGi / bnd / bndtools. There is no hard requirement for JUnit tests having to be annotated with `@RunWith`. Would it be possible in the future to refine this to discover and run all test cases with methods annotated with the `@Test` annotation, instead of classes annotated with `@RunWith`?

2. Shoudln't that launcher have a timeout if no test cases appear? The way you currently have it, this would block CI systems such as Travis etc. when validating PRs just when that annotation is removed. That's not great IMHO.

**Comment by bjhargrave** [comment]
> I meanwhile figured out that this is related to this line in the bnd.bnd:
> 
> # Discover and run all test cases annotated with the @RunWith annotation
> Test-Cases: ${classes;CONCRETE;ANNOTATED;org.junit.runner.RunWith}
> 
> To me as an end-user, this seems non-intuitive and problematic on two levels:

Well that is this bnd file. You can of course customize that line to use any criteria that makes sense for your project. For example, if you are writing JUnit 3 tests, then you may want:

    Test-Cases: ${classes;CONCRETE;EXTENDS;junit.framework.TestCase}

<https://github.com/bndtools/bnd/blob/master/org.osgi.impl.bundle.repoindex.test/bnd.bnd#L31>

So feel free to customize that to your needs. See <http://bnd.bndtools.org/macros/classes.html> for docs on the ${classes} macro.

> 
>     If I'm not using Mockito in my test, one should be able to remove the @RunWith(MockitoJUnitRunner.class)from e.g. ExampleIntegrationTest and it should still work. Mockito has nothing to do with OSGi / bnd / bndtools. There is no hard requirement for JUnit tests having to be annotated with @RunWith. Would it be possible in the future to refine this to discover and run all test cases with methods annotated with the @Test annotation, instead of classes annotated with @RunWith?

As I said above, you should customize this to your project's testing needs. I imagine no matter what it would be changed to, it would not meet someones needs :-)

> 
>     Shoudln't that launcher have a timeout if no test cases appear? The way you currently have it, this would block CI systems such as Travis etc. when validating PRs just when that annotation is removed. That's not great IMHO.

It might be nice to timeout the launcher, but you would then like the launcher to fail a test to indicate to the failure. But of course there are no test cases to fail :-) In general, I don't think this is a major issue as all CI systems will timeout and fail a stuck build. Bnd uses Travis, AppVeyor and Jenkins as CI systems and they all timeout stuck builds with a failure.

**Comment by timothyjward** [comment]
> There is no hard requirement for JUnit tests having to be annotated with `@RunWith`.

This is true for "vanilla JUnit tests", but we're looking at OSGi integration tests here, which can define different rules if needed.

> If I'm not using Mockito in my test, one should be able to remove the `@RunWith(MockitoJUnitRunner.class)`

You can - replacing it with `@RunWith(JUnit4.class)` will work just fine.

> Would it be possible in the future to refine this to discover and run all test cases with methods annotated with the @Test annotation, instead of classes annotated with @RunWith

To my knowledge there's no macro that can do this. You can use another heuristic (e.g. class name) right now, or start work on a PR if you're really keen to use `@Test`.
