### ISSUE TITLE
Eclipse Error on Run OSGi of bndrun

### ISSUE THREAD

**Issue by sachinb4u** [bndtools/bndtools#1540]
I get this intermittent eclipse error when I click on _Run OSGi_ button of bndrun. Next time when I click on the button, it works. 
I understand this isn't helping much in making issue clear, I am working on reproducing it in sample workspace however any inputs will be appreciated.

 **Environment Details**
1. BndTools : 3.2.0.REL-20160517-162512-g3a83c33
2. OS : Windows 10
3. Java : 1.8.0_102
4. Eclipse: Neon 4.6.0 / Juno / Mars

![run-osgi-erron-on-windows](https://cloud.githubusercontent.com/assets/2748549/18417839/98c4837a-7858-11e6-80cf-89e7323214c6.png)

**Comment by seanbright** [comment]
@sachinb4u, can you test with 3.3RC2 please? The P2 update site is here:

https://bndtools.ci.cloudbees.com/job/bndtools.next/84/artifact/build/generated/p2/

**Comment by sachinb4u** [comment]
Sure, I will test on 3.3RC2. Thanks!
