### ISSUE TITLE
Delete of project cnf on Windows not completely possible

### ISSUE THREAD

**Issue by peterkir** [bndtools/bndtools#1545]
Using 3.3.0.RC3 with Eclipse Neon

steps to reproduce:
1. creating a new Eclipse Workspace
2. create a bnd workspace from Template Github/osgi/workspace
3. delete the cnf (including files on filesystem)

file **/cnf/cache/wrapper/lock** cannot be deleted cause a handle is still open on it 

An Eclipse restart is necessary, to release the handle and delete the directory.

**Comment by bjhargrave** [comment]
Should be fixed in 3.4. If not please open a new issue.
