### ISSUE TITLE
Export/Release Project for Deployment

### ISSUE THREAD

**Issue by ferrisyang** [bndtools/bndtools#1546]
How to export/release project with a war/wab ?
From the Guide, I only find one way to export an executable jar.
I want to build the project in war/wab(s) (include all the dependent jars), and deploy it to other server containers, like Glassfish/JBoss.

**Comment by seanbright** [comment]
Usage questions should be asked in the bndtools-users mail list. See https://github.com/bndtools/bndtools#feedback
