### ISSUE TITLE
Multiple problems with the repository view

### ISSUE THREAD

**Issue by ivoleitao** [bndtools/bndtools#1551]
Hi!,

I'm dealing with a very annoying error in bndtools for a long time. Since it is related with the repository view and this view had some changes in the roadmap for bndtools 3.3 I decided to wait. Unfortunately the error is still present and I think that it's worst than before. This is happening in a debian linux box with the following details:

BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product -data /app/epm/ws/cfcom/platform

I have a couple of maven repositories in the repository view and almost every time I refresh the repositories (via menu option) all the repo's simply disappear and only the workspace repo remains. This happens also when I change something in the cnf/ext folder. In the error log the only message available is Failed to refresh repository: <name of the repo> without a stack trace. After that I need to press the refresh repository again a couple of times or change a file in the ext folder and sometimes out of frustration I simply restart eclipse. Sometimes the repository view recovers sometimes not and I need to repeat the process (via restart it normally works)

To make matters worse when I press the refresh repository, trying to recover from the missing repository situation or simply in normal use sometimes I'm presented with an exception like the one bellow.

```
java.util.ConcurrentModificationException
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1367)
	at aQute.lib.collections.IteratorList.<init>(IteratorList.java:11)
	at aQute.lib.collections.SortedList.fromIterator(SortedList.java:463)
	at aQute.bnd.osgi.Processor.getWildcardProperty(Processor.java:1303)
	at aQute.bnd.osgi.Processor.getProperty(Processor.java:1291)
	at aQute.bnd.osgi.Processor.mergeLocalProperties(Processor.java:2580)
	at aQute.bnd.osgi.Processor.getPlugins(Processor.java:524)
	at aQute.bnd.osgi.Processor.getPlugins(Processor.java:466)
	at bndtools.central.WorkspaceRepositoryChangeDetector$1.run(WorkspaceRepositoryChangeDetector.java:130)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

This is really driving me crazy since it's the only thing that seriously hampers my productivity with bndtools which I think is a fantastic tool.

Can I provide more debug data somehow to help solving this issues ?

**Comment by seanbright** [comment]
If you have a workspace you can share that consistently reproduces the problem, that would be helpful.

**Comment by ivoleitao** [comment]
Well I think I can help a little more. I started bndtools in debug mode and followed the source of the message "Failed to refresh repository". It is triggered by the bndtools.RefreshReposHandler class as an error in the method 

    public Object execute(ExecutionEvent event) throws ExecutionException

more precisely in the window.run instruction

            window.run(true, false, new IRunnableWithProgress() {
                public void run(IProgressMonitor monitor) throws InvocationTargetException, InterruptedException {
                    try {
                        buildFile.getWorkspace().run(new IWorkspaceRunnable() {
                            public void run(IProgressMonitor monitor) throws CoreException {
                                List<RepositoryPlugin> repos = RepositoryUtils.listRepositories(true);
                                for (RepositoryPlugin i : repos) {
                                    if (i instanceof Refreshable) {
                                        boolean success = false;
                                        Exception ex = null;
                                        try {
                                            success = ((Refreshable) i).refresh();
                                        } catch (Exception e) {
                                            ex = e;
                                        }
                                        if (!success) {
                                            logger.logError("Failed to refresh repository: " + i.getName(), ex);
                                        }
                                    }
                                }

                                buildFile.touch(monitor);
                            }
                        }, monitor);
                    } catch (CoreException e) {
                        throw new InvocationTargetException(e);
                    }
                }
            });
        } catch (Exception e) {
            logger.logError("Error refreshing repositories.", e);
        }

From what I understand from this source code if a Refreshable interface via refresh method returns false it is considered as an **error condition**. Next step was to follow the trail of this call. I my case I ended in aQute.bnd.repository.maven.provider.MavenBndRepository (already in bnd code):

	@Override
	public boolean refresh() throws Exception {
		return index.refresh();
	}

Which calls aQute.bnd.repository.maven.provider.refresh()

	boolean refresh() throws Exception {

		refresh.getAndSet(false);

		if (indexFile.lastModified() != lastModified && last + 10000 < System.currentTimeMillis()) {
			loadIndexFile();
			last = System.currentTimeMillis();

			return true;
		} else {
			boolean refreshed = false;
			for (BundleDescriptor bd : descriptors.values()) {
				if (bd.promise != null && bd.promise.isDone() && bd.promise.getFailure() == null) {
					File f = bd.promise.getValue();
					if (f.isFile() && f.lastModified() != bd.lastModified) {
						updateDescriptor(bd, f);
						refreshed = true;
					}
				}
			}
			if (refreshed)
				return true;
		}
		return false;
	}

In my case this ends in the *else* branch which executes *return false* hitting the error condition. Also I noticed that MavenBndRepository also calls index.refresh() in its pool method (which seems a call made by the eclipse in a UI thread). I was unable to understand if the *return false* which triggers the error is directly responsible for the clearing of the repository window but from what I have seem it seems that this is a concurrency problem between the UI refresh and the refresh triggered by bndtools. Also from my tests it seems that this is a problem mainly with the bnd maven plugin and not with the other plugins. It is certainly worst in my case because a I have 7 maven repositories.

So to trigger this is very easy:
- more than one bndmavenrepository
- Execute multiple times a refresh repositories til the repositories view is cleared. I noticed that in debug mode is much harder to simulate but it's possible. This could be related to the lack of theming support and / or the absence of other plugins.

**Comment by bjhargrave** [comment]
I think this is a side effect of a late change in 3.3 to look for `-plugin` only in local properties. The local property path, unlike the inherited property path, did not use a copy of the keys. It iterates over the live keys and this is the source of the issue (I think). I have a fix I am testing which should address this. PR to come.

**Comment by ivoleitao** [comment]
Hi @bjhargrave  Thnks for looking at this. Just one side node I had this problem since the first version that I have used, 3.1, I think. Probably it became worse in the last release but the problem was already there.

**Comment by bjhargrave** [comment]
Try the latest bndtools from cloudbees to see if your issue is fixed. I made changed beyond my comment above. I am not sure the changes are the complete solution but they may ameliorate the majority of the issue. If the problem is still present, please open a new issue.
