### ISSUE TITLE
Failed to start bundle org.apache.felix.scr-2.0.6

### ISSUE THREAD

**Issue by dixiesraj** [bndtools/bndtools#1554]
Hello,

I have just updated my bndtools installation to 3.3.0.
I created a bndtools cnf workspace (not the enroute one).
Then created a simple Component type OSGi project.
The added the component jar to launch.bndrun. 

After successful resolution I did Run OSgi, I get this error and I notice scr is not loaded.

> Failed to start bundle org.apache.felix.scr-2.0.6, exception activator error org/osgi/service/cm/ConfigurationListener from: java.lang.ClassLoader:defineClass1#-2

Kindly help.

**Comment by zhsc** [comment]
Have no idea if this is your issue.  But I've seen antivirus stop files with .scr in the file name from being loaded.  Apparently it thinks they're screen savers stupidly.  Even though the .scr isn't the extension.  Wasted a few hours on that myself.  Easy to test if that's what is happening.

**Comment by dixiesraj** [comment]
It was not the issue. I downgraded the jar to previous version and it worked.

**Comment by wodencafe** [comment]
Hi, I have this same error:
 Failed to start bundle org.apache.felix.scr-2.0.6, exception activator error org/osgi/service/cm/ConfigurationListener from: java.lang.ClassLoader:defineClass1#-2 

@dixiesraj if you don't mind me asking, how in bndtools did you downgrade the scr versoin?

**Comment by dixiesraj** [comment]
Download the act version 2.0.2 then drag and drop the jar in your local repo. 

Then expand the jar and you should see 2.0.2. Click and drag the version 2.0.2 onto your run bundles. 

Hope this helps. 

Regards,
Dixie. 
www.dartlesystems.com

**Comment by wodencafe** [comment]
@dixiesraj Thank you very much, this workaround got me past this problem :)

**Comment by dixiesraj** [comment]
Anytime. 

Founder, 
www.dartlesystems.com

**Comment by njbartlett** [comment]
This was a bug in Felix SCR, it has been fixed in Felix SCR 2.0.10.
