### ISSUE TITLE
Migrate enroute project wizard to new template system

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1555]
Given complaints about the complexity of creating a new workspace (see #1549) with working projects, the Enroute project wizard is now a problem because it can create projects that do not build in the user's workspace.

It needs to be migrated to one or more templates using the new template system, which should be maintained within the Enroute Workspace. I would like to make this a priority for 3.4.

@pkriens I would be grateful if you could identify any functional gaps in the template system that would make this difficult, and raise bugs for those against the 3.4 milestone. Thanks.

**Comment by njbartlett** [comment]
Since Peter does not have time to look at this, my proposal is to remove the Enroute project wizard from core Bndtools. The templates can then be implemented in the OSGi Enroute workspace (which is a separate GitHub project) by the Enroute user community.

**Comment by pkriens** [comment]
And what about the tutorials?

**Comment by njbartlett** [comment]
I suppose they would have to be updated along with the templates.

**Comment by pkriens** [comment]
Yes ... but if you remove it you effectively kill the site since the problem is lack of time ...

**Comment by njbartlett** [comment]
Do you have an alternative suggestion?

**Comment by pkriens** [comment]
Leave it as is. Not sure I understand the urgency.

**Comment by njbartlett** [comment]
I'm trying to simplify the initial user experience and not have wizards that produce invalid output for the chosen workspace.

I'm not saying this is urgent but I'd like to get it done for 3.4 if possible, and it seems unlikely that this can happen unless we start the process of removing them early in the cycle.

**Comment by timothyjward** [comment]
Also the earlier that this happens the longer users have to migrate the templates into the 3.4 release.

Sent from my iPhone

On 4 Oct 2016, at 06:22, Neil Bartlett <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm trying to simplify the initial user experience and not have wizards that produce invalid output for the chosen workspace.

I'm not saying this is urgent but I'd like to get it done for 3.4 if possible, and it seems unlikely that this can happen unless we start the process of removing them early in the cycle.

-

**Comment by njbartlett** [comment]
PR #1564

**Comment by njbartlett** [comment]
PR 21 in project [osgi/osgi.enroute](https://github.com/osgi/osgi.enroute/pull/21) should address this issue.
