### ISSUE TITLE
Bndtools->Refresh Repositories menu results in multiple refresh jobs

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bndtools#1559]
If you click the Bndtools->Refresh Repositories menu (or shift-command-F) to refresh repositories, two background jobs are triggered to do the work.

In the Progress view, you first see ["Refresh Workspace Repository"](https://github.com/bndtools/bndtools/blob/master/bndtools.core/src/bndtools/central/WorkspaceRepositoryChangeDetector.java#L124) followed by ["Updating repositories content"](https://github.com/bndtools/bndtools/blob/master/bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java#L78).

I am not sure what each job is doing, but it seems odd that two jobs are needed by Bndtools to refresh the repositories from the menu item.

Also, if you click the Refresh Repositories Tree button in the Repositories view, you end up with a third, different job: ["Refresh repositories"](https://github.com/bndtools/bndtools/blob/master/bndtools.core/src/bndtools/views/repository/RepositoriesView.java#L575).

So there seems to be too many cooks in the kitchen.

**Comment by daghanacay** [comment]
I believe relevant to this, when I click on Bndtools-> refresh repositories in eclipse menu the Repositories view removes some repositories. It takes multiple clicks to get the full set of repositories. 

PS: This might be due to my internet connection being choppy.
PSS: I am using bndtools 3.3.0.REL-...g069791c

**Comment by gamerson** [comment]
@bjhargrave did some research.  When you execute `Bndtools > Refresh repositories...` it will touch the `cnd/build.bnd` file. Which causes the following...

1. https://github.com/bndtools/bndtools/blob/master/bndtools.core/src/bndtools/central/WorkspaceRepositoryChangeDetector.java#L50 
This will detect the `cnf/build.bnd` change and it fires off a new job here: https://github.com/bndtools/bndtools/blob/master/bndtools.core/src/bndtools/central/WorkspaceRepositoryChangeDetector.java#L124
2. By touching the `cnf/build.bnd` this fires off a BndtoolsBuilder to rebuild all of the bundles in your workspace.  In my workspace one of the bundles `launch.simple/bnd.bnd` had error markers.  And as you know error markers are all removed during a rebuild.  So when the error markers are removed (and subsequently readded) by the BndtoolsBuilder, the WorkspaceRepositoryChangeDetector once again sees this as a change at https://github.com/bndtools/bndtools/blob/master/bndtools.core/src/bndtools/central/WorkspaceRepositoryChangeDetector.java#L50 and thus it fires off another WorkspaceJob

So it seems that when you touch the top-level `cnf/build.bnd` it sets off several file changes that all get collected by the WorkspaceChangeDetector which for each one fires off a new refresh job.  So depending on the state of your workspace you may see a different set of new jobs being created.

**Comment by bjhargrave** [comment]
> When you execute Bndtools > Refresh repositories... it will touch the cnd/build.bnd file

This seems like a bad way to trigger a rebuild. I think we need to find a different way.

**Comment by gamerson** [comment]
As discussed with committers, we will make the `Bndtools > Refresh Repositories...` menu action do the exact same thing as the `Repositories View > Refresh` toolbar action.
