### ISSUE TITLE
How to get info on @Deprecated in a baseline diff?

### ISSUE THREAD

**Issue by jepet** [bndtools/bndtools#1562]
Question: We're using the baseline analysis to detect API changes. We would like to be able to detect APIs which have been annotated with @Deprecated, but it seems as though the baseline diff tool removes this information. We have found that we can detect these changes using the Analyzer which gives access to Clazz objects. We haven't been able to find where information on @Deprecated methods are stored. Is this possible?

**Comment by pkriens** [comment]
I am not sure what you want? What effect should a deprecated have? There should be a micro change on this?

**Comment by jepet** [comment]
We're automatically generating a changelog of API changes by diffing the current and previous release. This works great. We'd like to enhance this changelog with additional info on which APIs have been deprecated. Unfortunately, the @Deprecated annotation is removed from the Diff result by the baseline diff algorithm (why?). We're able to detect all other annotation changes from one version to the other, but sadly not this one. I found a way to locate the info on the Clazz objects, but for methods I'm lost.

**Comment by pkriens** [comment]
The annotations are specified as attributes. So in JavaElement the class file is reparsed to get the relevant information. You should override the methods in the ClassDataCollector that get the attributes and process them accordingly.

I am rather puzzled though. Deprecated is not a binary issue, it is intended to be detected by the compiler. Why would you not detect this easier in compiling than baselining?

**Comment by jepet** [comment]
OK, thanks, I'll look into this. 
And yes, we could very well find the deprecations using an annotation processor. From a convenience point of view, though, it's nice to be able to do this in a single separate process. We have a jenkins job retrieving the different versions of our software (>300 bundles) and doing a diff using the baseline. We like the approach, but the need to add deprecations soon became apparent. As we're diffing the binaries, the compiler isn't in play here.
