### ISSUE TITLE
New project dialog not working in Eclipse neon.1

### ISSUE THREAD

**Issue by ottlinger** [bndtools/bndtools#1567]
I'm using Eclipse Neon.1 (Eclipse Java EE IDE for Web Developers. Version: Neon.1a Release (4.6.1)) and bndtools 3.3.0.201609221907 with Oracle JDK 1.8_112 on Mac v10.11.6.

The dialogue

```
File -> New -> Bnd OSGi Project
```

results in an exception dialogue without any further action possible.

The dialogue is:
Problem Opeing Wizard

```
Plug-in "bndtools.core" was unable to instantiate class "bndtools.wizards.project.NewBndProjectWizardFactory".
org/eclipse/jdt/ui/wizards/NewJavaProjectWizardPageOne
```

Thus I'm unable to create any new bnd projects within Eclipse.

Is this a bndtools-Issue? Eclipse itself has no further updates and I'm able to create regular Java projects.

**Comment by LiamTelensa** [comment]
I had the same problem on a Fedora 24 VM installation. (Same Eclipse, bndtools, jdk as above).

**Comment by qkxy** [comment]
I have the same config as ottlinger has and I get the same exception in Eclipse Neon.
Do you have solution or workaround for this error?

**Comment by lostiniceland** [comment]
I cannot reproduce this in the current 3.4 dev-version. 
I expected some problem when there is no internet-connection since the templates are retrieved from urls, but everything works as it should even without connection.

**Comment by bjhargrave** [comment]
Open a new issue if this is still a problem in 3.4.
