### ISSUE TITLE
Conditional-Package assemble problem

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1575]
Suppose 2 projects: A and B

A has a Conditional-Package dependency on B.
B is a '-nobundles: true' project

Now change a class in B : the class is compiled and bundle B is reassembled.
Bundle A is NOT reassembled

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by bjhargrave** [comment]
Please reopen when you can provide a github repo to demonstrate.
