### ISSUE TITLE
A multiproject master directory

### ISSUE THREAD

**Issue by cbrommer** [bndtools/bndtools#1576]
This issue is completely written for usage with eclipse bnd tools in combination with gradle.

It would be really nice if one could have access to the main gradle files in a project in a bnd workspace, next to it having the possibility to add a gradle nature (gradle buildship eclipse plugin) to projects.

In gradle it is possible to move the gradle.properties/build.gradle and settings.gradle to a [master directory](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html#sec:structure_of_a_multiproject_build) in the workspace. This way you could also incorporate this directory as project in e.g. eclipse and have access to it.

**Comment by bjhargrave** [comment]
> In gradle it is possible to move the gradle.properties/build.gradle and settings.gradle to a master directory in the workspace.

I don't know what you mean. I do not see anything about moving these files out of parent folder of the projects.

> This way you could also incorporate this directory as project in e.g. eclipse and have access to it.

This is an eclipse issue and you can already add files in the root of a workspace to a project as a link. Go to import from the file system, click the Advanced button and then choose to create link in workspace. Then select the files you care about from the workspace root. I created a "root" project and added settings.gradle, build.gradle, .gitignore, ... as links to this project.
