### ISSUE TITLE
Launch Problems dialog should allow to terminate previous launch

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1583]
When running an OSGi Framwork, for example through the _Run OSGi_ button in the bndrun file editor, a dialog appears saying that 

> One or more OSGi Frameworks have already been launched for this configuration ... and may interfere with each other.

I would find it immersly helpful to have a choice to terminate the already launched framework. Alternatively the run descriptor could have a setting to terminate previous launches.

![image](https://cloud.githubusercontent.com/assets/607182/20642364/0d7f033a-b40d-11e6-8db8-c6dd9cc37485.png)

There may be other warnings which I am unaware of, but in this case, the details message is merely a repetition of the contents displayed in Problems.

Besides that, the _Continue launching anyway?_ message in the bottom right of the dialog is hard to recognize.

**Comment by njbartlett** [comment]
This is our error message but it is presented in a standard Eclipse dialog. I don't believe there is any way to add a button to stop the old run.
