### ISSUE TITLE
Error log view opens unexpectedly when using Bndtools

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1585]
Bndtools writes information messages to the Eclipse Error log like this

> Download https://raw.githubusercontent.com/bndtools/bundle-hub/master/index.xml.gz

With the default settings, where _Active on new events_ is on, this causes the _Error log_ view to be activated unexpectedly and 'stealing' the focus from the view/editor I am currently working in.

Is there are reason for writing these information messages to the log?

**Comment by bjhargrave** [comment]
It is a log and these are information log entries. This is as intended.

**Comment by rotty3000** [comment]
also note that bnd/bndtools are logging those messages necessarily at ERROR. But according to the Eclipse -> `Error Log` view configuration it does also print non-errors which is not bndtools' fault (it is a view titled "Error Log" after all, and as named it should probably filter ERRORs by default)

![error-log-configuration](https://cloud.githubusercontent.com/assets/146764/26007489/b4eae772-370e-11e7-8f84-d7011697b4b3.png)
