### ISSUE TITLE
Make importing packages easy

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1589]
Consider this scenario: First, create this interface in bundle `org.example.api`:
```java
package org.example.api;

public interface Greeting {
  String sayHello( String name );
}
```
and exported the `org.example.api` package. Then create a service that implements the above interface in bundle `org.example.impl`:

```java
package org.example.impl;

import org.osgi.service.component.annotations.Component;

@Component
public class GreetingComponent implements Greeting {
  public String sayHello( String name ) {
    return "Hello " + name;
  }
}
```
Of course, the type `Greeting` cannot be resolved because the `org.example.api` package is not yet _known_ to the `impl` bundle. The bnd file of the `impl` bundle needs to be edited so that its `-buildpath` directive contains the `api` bundle.

I suggest to provide a quick fix that adds the missing bundle to the build path of the `impl` bundle.

**Comment by kriegfrj** [comment]
I'm trying to port a large-ish PDE project to Bndtools, and this feature would save quite a bit of time in the process of adding lots of bundles to the build path. Is anyone working on it? If not, I can have a crack.

**Comment by rotty3000** [comment]
I don't think anyone is working on this. ☺
