### ISSUE TITLE
JAR Editor should sort files before folders

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1590]
The Jar file viewer of the JAR Editor sorts files and folders alphabetically (see screenshot)
![image](https://cloud.githubusercontent.com/assets/607182/20727265/187ddbd0-b679-11e6-93cf-bda45e17c5e0.png)

I suggest to keep the alphabetial order but put files before folders
```
In the above example the order would be
+ parsii
  - packageinfo
  + eval
  + tokenizer
```

**Comment by pkriens** [comment]
Since the order is sometimes relevant I think it is important to show the actual order
