### ISSUE TITLE
Content under bndtools.test/workspace should be excluded from VCS

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1597]
I sugest to add a `.gitignore` file in `bndtools.test` with this content
```
workspace/
```
so that rpojects, files and folder that are created while debugging Bndtools aren't treated as outgoing changes.

Please let me know if you consider this a useful change and I will open a pull request.

**Comment by bjhargrave** [comment]
The teams may want to keep files in the workspace in the git repo, so we don't want a broad ignore.
