### ISSUE TITLE
Unnecessary null check in LaunchUtils::getTargetResource()

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1600]
See https://github.com/bndtools/bndtools/blob/master/bndtools.core/src/bndtools/launch/util/LaunchUtils.java#L28

I think, the null check
```java
if (targetResource == null)
    return null;
```
is unnecessary.

Would you agree to remove the extra null check and inline the above line like this?
```java
return ResourcesPlugin.getWorkspace().getRoot().findMember(target);
```

**Comment by bjhargrave** [comment]
Removing the null check is fine. Removing the local var is not really important and can make debugging since you can set a breakpoint on the return as see that variable value. But it is not a big deal.
