### ISSUE TITLE
creating an bndtools workspace makes command "bnd plugins" fail.

### ISSUE THREAD

**Issue by aploese** [bndtools/bndtools#1603]
After I got some strange error messages during resolving a bndrun I tryed it wit the plain bnd - and got som error messages...

Steps to reproduce:
eclipse neon (Version: Neon.1a Release (4.6.1) Build id: 20161007-1200)
bndtools (3.3.0.201609221907)
bnd (2.4.1.201611140949)

*Create a new workspace as described in the enroute osgi base tutorial.
*execute  "bnd plugins"
I got the following output:

  000 Workspace [test-missing-osgi-framework]
001 java.util.concurrent.ThreadPoolExecutor@4dcbadb4[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
002 java.util.Random@4e515669
003 Maven [m2=/home/aploese/.m2]
004 Settings[/home/aploese/.bnd/settings.json]
005 bnd-cache
006 ResourceRepositoryImpl [cache=/home/aploese/.bnd/caches/shas, indexFile=/home/aploese/workspaces/test-missing-osgi-framework/cnf/repo.json, ]
007 aQute.bnd.osgi.Processor
-----------------
Errors
000: Failed to load plugin aQute.bnd.repository.maven.pom.provider.BndPomRepository;snapshotUrls="https://oss.sonatype.org/content/groups/osgi";releaseUrls="https://repo1.maven.org/maven2/";pom="/home/aploese/workspaces/test-missing-osgi-framework/cnf/central.xml";name=Central;location="/home/aploese/workspaces/test-missing-osgi-framework/cnf/cache/enroute-central.xml", error: aQute.bnd.repository.maven.pom.provider.BndPomRepository not found, parent:  sun.misc.Launcher$AppClassLoader@677327b6 urls:[] exception:java.lang.ClassNotFoundException: aQute.bnd.repository.maven.pom.provider.BndPomRepository 
001: Cannot load the plugin aQute.bnd.repository.maven.pom.provider.BndPomRepository
002: Failed to load plugin aQute.bnd.deployer.repository.LocalIndexedRepo;name=Local;pretty=true;local="/home/aploese/workspaces/test-missing-osgi-framework/cnf/local", error: aQute.bnd.deployer.repository.LocalIndexedRepo not found, parent:  sun.misc.Launcher$AppClassLoader@677327b6 urls:[] exception:java.lang.ClassNotFoundException: aQute.bnd.deployer.repository.LocalIndexedRepo 
003: Cannot load the plugin aQute.bnd.deployer.repository.LocalIndexedRepo
004: Failed to load plugin aQute.bnd.deployer.repository.LocalIndexedRepo;name=Release;pretty=true;local="/home/aploese/workspaces/test-missing-osgi-framework/cnf/release", error: aQute.bnd.deployer.repository.LocalIndexedRepo not found, parent:  sun.misc.Launcher$AppClassLoader@677327b6 urls:[] exception:java.lang.ClassNotFoundException: aQute.bnd.deployer.repository.LocalIndexedRepo 
005: Failed to load plugin aQute.bnd.repository.maven.pom.provider.BndPomRepository;snapshotUrls="https://oss.sonatype.org/content/groups/osgi";releaseUrls="https://repo1.maven.org/maven2/";revision="org.osgi:osgi.enroute.pom.distro:2.0.0";name=Distro;location="/home/aploese/workspaces/test-missing-osgi-framework/cnf/cache/enroute-distro.xml", error: aQute.bnd.repository.maven.pom.provider.BndPomRepository not found, parent:  sun.misc.Launcher$AppClassLoader@677327b6 urls:[] exception:java.lang.ClassNotFoundException: aQute.bnd.repository.maven.pom.provider.BndPomRepository

**Comment by bjhargrave** [comment]
> bndtools (3.3.0.201609221907)
> bnd (2.4.1.201611140949)

You are mixing bnd 2.4.1 and bndtools 3.3.0 (which uses bnd 3.3.0). I would be surprised if it worked. Bnd 2.4.1 has no idea about the newer features of Bnd 3.3.0 such as the BndPomRepository. You need to use the version of Bnd command which matches the version of Bnd used in the workspace. Please update your Bnd command to 3.3.0.

**Comment by aploese** [comment]
I installed bnd as described here: http://bnd.bndtools.org/chapters/120-install.html
Thats what I got ...

So I'm a newbie to bnd - some meaningful error messages like "you are using bnd 2.4 in an 3.3 environment" would be nice.
And Installing bndtool 3.3 as default in eclipse but getting an incompatible version on the bnd site is not very user friendly - by the way how can I install a recent bnd?

Thanks in advance

Arne Plöse

**Comment by bjhargrave** [comment]
I see 3.3 as the top choice for bnd from jpm:
```
$ jpm candidates bnd@*
[M] biz.aQute.bnd:biz.aQute.bnd         3.3.0                         2016-10-14  AA45AB294FE338BF86485549E8996BEE5A8765CE
```
So I am not sure how it would have installed bnd 2.4 as a command. Did you try `jpm update bnd`?

The bnd command would not be able to know your workspace uses plugins from a later version of bnd since it cannot know about the future.

I also find it curious you are using the command line bnd. I almost never use it. Normally I use Bndtools in Eclipse for development and the Bnd Gradle plugin in my gradle build for command line/CI builds.

**Comment by aploese** [comment]
Sorry, the debian bnd had won... ( I forgot to symlink the jpm/bin/bnd to ~/bin/bnd - sorry).

But at the page http://bnd.bndtools.org/chapters/100-release.html there is no information on something like 3.3. - its outdated.
At http://bnd.bndtools.org/chapters/120-install.html there is only version 2.4.0 present.
So for a newbie there is no hint what is the current version is. Can that be changed (feature request?).
Can you reopen this as feature request useability => Give a proper message to the user if the version of bnd and the workspace don't match. This would give the user the chance to search what hit him.

Thank you for your help

Arne Plöse

**Comment by bjhargrave** [comment]
> Can that be changed (feature request?).

The bnd.bndtools.org website it a GitHub pages site in the [docs](https://github.com/bndtools/bnd/tree/master/docs) folder of the [bnd repo](https://github.com/bndtools/bnd). Can you make a PR to improve the docs? (This is the bndtools repo for the Eclipse tooling.)


> Can you reopen this as feature request useability => Give a proper message to the user if the version of bnd and the workspace don't match. This would give the user the chance to search what hit him.

As I tried to explain earlier, workspaces do not have a bnd version. Your workspace used a repository type which is from Bnd 3.3, so Bnd 2.4 did not know the repository type and thus could not load it. So it is hard for a version of Bnd to know about any future repository types so that it could tell you to use some future version of Bnd to use that repository type. Also, any one could author a repository type, so the error may not be because of using an older version of Bnd.
