### ISSUE TITLE
Restarting Eclipse with .bnd editor open on Build tab shows "Workspace is loading, please wait..." forever

### ISSUE THREAD

**Issue by gravelld** [bndtools/bndtools#1617]
Eclipse Neon, 4.6.0. Xubuntu 16.04, Java 1.8.0_91. Bndtools 3.3.0

I have two editors open - a bndrun editor, and a bnd editor, in that order left-to-right in the Editor pane. The bnd editor is active, with the Build tab shown.

I now restart Eclipse. Once restarted, "Workspace is loading, please wait" is shown seemingly forever in the Build tab. CPU usage is low.

If I click on the Contents tab the boxes populate, then back to the Build tab the Build tab is populated. Things seem to work from here - **so not a very important issue**.

If I restart with the Run tab open on the bndrun file I get the same "hang". If I click to the bndrun file with the Build tab open, again the hang continues. If I then click on Contents everything gets populated, including the bndrun file.

If I click the "Workspace is loading, please wait" hyperlink I get:

```
java.lang.NullPointerException
	at bndtools.utils.MessagesPopupDialog.createDialogArea(MessagesPopupDialog.java:72)
	at org.eclipse.jface.dialogs.PopupDialog.createContents(PopupDialog.java:694)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.PopupDialog.open(PopupDialog.java:1134)
	at bndtools.utils.MessageHyperlinkAdapter.showPopup(MessageHyperlinkAdapter.java:44)
	at bndtools.utils.MessageHyperlinkAdapter.linkActivated(MessageHyperlinkAdapter.java:30)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:228)
        ....
```

This is surprising, because **I am using bndtools 3.3** and I thought as part of #1505 this was fixed for that release:

![319885a6-c60b-11e6-99f0-24398b69aa4a](https://cloud.githubusercontent.com/assets/873704/21347581/29e5eef2-c6a1-11e6-929a-037b704dd3c3.png)

I suspect this might be something to do with my workspace. Unless there's a way to package it up easily I think it might be too difficult to recreate (or maybe a simple tar would suffice).

There's nothing in the Error Log, nor on stdout/err.

Please see #1505 for an older, similar problem.

**Comment by gamerson** [comment]
hello @gravelld could you provide a workspace/build that would help to reproduce?  I haven't been able to reproduce this with my test workspaces and Bndtools 3.4.0 RC1

**Comment by gravelld** [comment]
Sorry - moved away from bndtools now...

**Comment by gamerson** [comment]
Ok thanks for following up; I'll close this for now.

**Comment by gamerson** [comment]
NPE exception has at least been fixed MessagesPopupDialog.createDialogArea
