### ISSUE TITLE
Unable to delete /cnf/cache while Bndtools is running

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1623]
Trying to delete the cached index of a Maven repository fails on Windows when Bndtools is running.

To reproduce, edit a bnd file to include a Maven reposiory like this:
```
-plugin: \
    aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
        releaseUrls=https://repo.maven.apache.org/maven2/; \
        pom=${workspace}/cnf/maven-central.xml; \
        location=cnf/cache/maven-central.xml; \
        name=Maven Central;
```
reference some artifacts in the `cnf/maven-central.xml` file and add a dependency from this reporitory to a project.

Trying to delete `cnf/cache/maven-central.xml` will result in this error;
```
Problems encountered while deleting resources.
  Could not delete 'C:\Users\...\cnf\cache\maven-central.xml'.
    Problems encountered while deleting files.
      Could not delete: C:\Users\...cnf\cache\maven-central.xml.
      C:\Users\...\cnf\cache\maven-central.xml: The process cannot access the file because it is being used by another process.
```

Is Bndtools or bnd leaking file handles?

**Comment by rotty3000** [comment]
Could you try removing the location property? I don't think it's needed.

**Comment by rherrmann** [comment]
According to the documentation, the location property controls the location of the cache file. After removing the location property, a file named `cnf/cache/pom-Maven Central.xml` is created.
If the default is chosen, there seems to be no file handle leaking and the file can be deleted.

**Comment by rherrmann** [comment]
After removing the `location` property (resulting in a `cnf/cache/pom-Maven Central.xml` file being created) and working with Bndtools for a while, I still cannot remove the cache file.

Hence, the resource leak seems to be unrelated to how the cache file location is determined (default or explicit).

**Comment by bjhargrave** [comment]
The file is in use and Windows wont let in use files be deleted. I am sure you can delete after stopping Eclipse.

**Comment by rherrmann** [comment]
Why would I have to close Eclipse until I can delete a file? The file should not be in use in the first place, i.e. there was no builder or the like running at that time.

To me, this is a strong indicator of a resource leak that should be fixed instead of being worked around.

**Comment by bjhargrave** [comment]
If the file is open by the eclipse process, then windows wont let you delete an open file. The Bnd workspace holds the repositories, one of which holds the file.

**Comment by rherrmann** [comment]
The issues here is, that the file should not be open. If Eclipse is idle (i.e. no jobs are running) - which it was when I tried to delete the file - there should be no plug-in that holds a file handle.

All plug-ins from Eclipse.org adhere to that rule and so should Bndtools.

**Comment by rherrmann** [comment]
Thank you for fixing this!
