### ISSUE TITLE
New OSGi Project wizard generates uncompiling code

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1651]
Open the Bnd OSGi Project wizard and select the OSGi enRoute project template. Enter `my-example` in the project name input field and select finish.

The generated example code does not escape the project name properly and produces Java code with compile errors. For example:

    public interface My-example {
      ...
    }

**Comment by bjhargrave** [comment]
EnRoute templates are changing for 3.4. Closing for now. Will need to retry on new enroute templates.
