### ISSUE TITLE
NullPointerException when refreshing repository view

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1652]
I got this exception while trying to refresh the _Repositories_ view:
```
java.lang.NullPointerException
	at aQute.bnd.repository.maven.pom.provider.BndPomRepository.refresh(BndPomRepository.java:98)
	at bndtools.central.Central.refreshPlugins(Central.java:466)
	at bndtools.views.repository.RepositoriesView$10$1.runInWorkspace(RepositoriesView.java:536)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

The maven repository plugin is specified as this:
```
-plugin: \
    aQute.bnd.repository.maven.pom.provider.BndPomRepository; \
        releaseUrls=https://repo1.maven.org/maven2/; \
        pom=${workspace}/cnf/pom.xml; \
        name=Maven Central
```
The pom.xml file has this content:
```
<dependencies>
    <dependency>
        <groupId>org.osgi</groupId>
        <artifactId>osgi.enroute.base.api</artifactId>
        <version>2.0.0</version>
    </dependency>
</dependencies>
```

Around the same time I had several connection timeouts due to an unstable internet connection, that may have caused this bug.

**Comment by rherrmann** [comment]
Additional information to reproduce: 
The bnd workspace is new, i.e. the repository content has never been downloaded before and a unreliable internet connection prevents download from succeeding (previous 'connection timeout' errors).

**Comment by pkriens** [comment]
I think this is fixed. I tried something and have not see it again. Please reopen when you see it again with an instruction how to get it.
