### ISSUE TITLE
Test results not reported to JUnit in Bndtools 3.4

### ISSUE THREAD

**Issue by pebarlow** [bndtools/bndtools#1668]
I'm developing using Eclipse Mars and Java 8. 

I created an integration test project in Bndtools 3.4.  I added one JUnit test and ran using the Bnd OSGi Test Launcher.   Based on the information in the "Console" view, 1 test was run and 1 test passed, however, the JUnit View does not show the results.  Under "Runs", on the JUnit View, "1/0" is displayed.

If I force the test to fail, I get the same results on the JUnit View "1/0" listed under "Runs".

I'm not sure if this is a bug in Bndtools or if I'm missing something when setting up the test.

**Comment by bjhargrave** [comment]
Duplicate of #1586
