### ISSUE TITLE
Marking Components

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1671]
Components are the hinges of the design. However, in the package explorer they are not visible as such. This means I am often chasing which classes are components.

I wonder how hard it would be to mark a class as an OSGi component?

**Comment by wodencafe** [comment]
How does this look Peter?

This branch adds support for identifying Components in the Text Editor, the Markers View, the Package Explorer, and Outline.

Here are some picture examples:
![screenshot_20170409_234332](https://cloud.githubusercontent.com/assets/9727493/24847001/ca6c09ae-1d83-11e7-958c-8267eadd6696.png)

![screenshot_20170409_234611](https://cloud.githubusercontent.com/assets/9727493/24847014/e09d0264-1d83-11e7-8b72-30bf689464d9.png)

![screenshot_20170409_234643](https://cloud.githubusercontent.com/assets/9727493/24847019/e659a89c-1d83-11e7-8e87-2b7345843042.png)

![screenshot_20170409_234721](https://cloud.githubusercontent.com/assets/9727493/24847026/ede10178-1d83-11e7-8726-4820112af81f.png)

![screenshot_20170409_234749](https://cloud.githubusercontent.com/assets/9727493/24847028/f0857b16-1d83-11e7-8c90-d084ba1336b4.png)

There is a new "Annotation Type" created in Eclipse Window Preferences, that allows customization of the Component Marker.

![screenshot_20170409_234450](https://cloud.githubusercontent.com/assets/9727493/24847036/05c970d6-1d84-11e7-8ee6-f31ac27846bb.png)

**Comment by pkriens** [comment]
Very nice! Great work. Like the markers view, that is very useful

**Comment by wodencafe** [comment]
Hi @pkriens, I'm glad to hear you like it! 

I will create the PR tonight, I'm also working on marking packages that contain classes with components, with a count of the components and the little LED icon.

**Comment by gamerson** [comment]
fixed in https://github.com/bndtools/bndtools/pull/1697
