### ISSUE TITLE
Different key bindings to run/debug Bnd OSGi Tests

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1674]
The key binding to **run** a Bnd OSGi Test is <kbd>Alt+Shift+X C</kbd> whereas the key binding to **debug** a Bnd OSGi Test is <kbd>Alt+Shift+D K</kbd>.

Is there a reason why the same kind of launch uses different keys (<kbd>C</kbd> vs. <kbd>K</kbd>)?

Applies to Bndtools 3.3.

**Comment by gamerson** [comment]
No reason that I can see, it should be the same.

**Comment by bjhargrave** [comment]
Closed by #1680
