### ISSUE TITLE
Build issues?

### ISSUE THREAD

**Issue by sleschke** [bndtools/bndtools#1677]
I pulled the latest bndtools last night and noticed some time later that many of my projects no longer compile. Any project having a build dependency on either osgi.core (v6), osgi.cmpn or osgi.annotation, fail to compile with errors indicating that the library jars don't exist. It would appear they have disappeared from the bndtools build repo.

I pulled an update a short while ago thinking that might resolve the issue but it did not.

**Comment by sleschke** [comment]
As is my norm, I just did a “Help->Check for Updates” in Eclipse with the bndtools update site pointing at:

https://bndtools.ci.cloudbees.com/job/bndtools.master/lastSuccessfulBuild/artifact/build/generated/p2

In the Repositories view, BndTools Hub is empty, and Build contains no osgi.annotaiton or osgi.cmpn, while osgi.core only contains versions through 5.0.0.
I had a similar issue happen once before quite some time ago but a later update corrected the issue.

Scott

**Comment by bjhargrave** [comment]
I am not sure how to help here. You still fail to provide enough details to fully understand what you are attempting to do. I deduce now you are not trying to build the bndtools repo since you mention `In the Repositories view, BndTools Hub is empty` which we don't use in the bndtools build.

Can you please provide a small github repo which demonstrates the problem? Then we can understand the problem more completely and investigate. Thanks.

**Comment by sleschke** [comment]
Hi again,

I just pulled the latest Bndtools dev release that must have dropped sometime last evening. I now see that the Bndtools Hub repo contains all the libraries I wasn’t seeing and everything is compiling again..

I believe many of the libs in question used to be in the Build repo although I may be mistaken. I am a bit confused as to the relationship between the two though. I’ve never been real clear as to the intended use of the various repos that are shown in the Repositories view and haven’t found a description. I’d love to read one it if you can point me to it.

While I’ve been using Bndtools for a while now, I’m not an expert in its use and I’m probably doing a number of things either incorrectly or inefficiently and doubt I’m using many of the capabilities it has. It certainly does work for me though and is really a fantastic piece of work.

Regards,

Scott Leschke
