### ISSUE TITLE
P2 repository cache doesn't work reliably in Windows

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bndtools#1678]
Every time I start Eclipse the entire repo gets downloaded again from scratch, though the same workspace doesn't have this problem in Linux. I'm not sure if this is a bndtools issue or a bnd one.

That said, I'm not sure why we would ever want to re-download an artefact we already have in the cache even if we refresh the repository since P2 publishes md5 hashes to validate them against, but this seems to happen pretty frequently. Is this expected behaviour or a bug?

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by gamerson** [comment]
@eliasvasylenko this is likely the code that isn't behaving as it should.  If you could debug this code it might give us a some idea of what is going on. https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java#L82-L112

**Comment by eliasvasylenko** [comment]
Okay thanks for the pointer, I'll look into it and get back to you both.

**Comment by pkriens** [comment]
Is this really downloading or just the message? We're using if-modified requests so we do not know ahead of time if there is work or not. So we always have to print the message downloading.

**Comment by eliasvasylenko** [comment]
If it's not downloading it's definitely doing something, slows everything down for like 15 minutes! (It's the entire eclipse neon repo so it takes a long time.) Unfortunately I can only check it at work as I have no Windows at home and it's been hard to find time.

**Comment by eliasvasylenko** [comment]
Okay, just got round to this again. Turns out you were right, Peter, the "downloading" messages were a red herring. It's just disk I/O by itself which is killing everything. Should have noticed that!

Anyway it seems to be caused by reading all the jar files to regenerate the requirements/capabilities. There is a check in the P2Indexer constructor to avoid redoing this if the index file already exists, but then the repositories view asks for a refresh so it ends up doing it anyway. The problem disappears with the view closed.

A solution would be to change the behaviour of a refresh to skip generating metadata for artefacts which are already in the index. Would this be okay or is there any value in keeping the current behaviour of regenerating everything wholesale? I'm happy to make the change myself.

As for why it was happening to me on Windows and not Linux, it must just be because the former boots off an HDD and the latter off an SSD ... but I'm shocked at the scale of the difference.

I'll try to confirm all of this when I get home and if I'm right I'll create a new issue.

**Comment by eliasvasylenko** [comment]
Submitted a more accurate issue at bndtools/bnd#2027 along with a PR
