### ISSUE TITLE
Wrong groupId or artifactId in central.xml fails silently

### ISSUE THREAD

**Issue by aploese** [bndtools/bndtools#1736]
How to reproduce:

add this entry to cnf/central.xml:
```
                <dependency>
			<groupId>test</groupId>
			<artifactId>dummy</artifactId>
			<version>1.0.0</version>
		</dependency>
```
In bnd.bnd add these under Run Requirements.
Note the "java.lang.reflect.InvocationTargetException" in the dialog.

Now try Resolve. Hitting the Finish button will cause an Eclipse error.

This non existant maven artifact should be handled earlier.

**Comment by bjhargrave** [comment]
There is probably somewhere in BndPomRepository that is not handling a failed promise properly and then the InvocationTargetException.
