### ISSUE TITLE
Fixed native setup in exported jar

### ISSUE THREAD

**Issue by aploese** [bndtools/bndtools#1738]
The resulting jar loads only the native library for linux/x86-64. 
Running these jar on a windows machine will not load the windows version but fail with an UnsatisfiedLinkException.

Running these on linux/arm System.loadLibrary("spsw-1.0.0") will extract the lib/linux/amd64/libspsw-1.0.0.so and try to load that one.

here my Bundle-NativeCode section. 
Bundle-NativeCode: lib/linux/armhf/libspsw-1.0.0.so; osname=Linux; pro
 cessor=arm_be; processor=arm,lib/linux/i386/libspsw-1.0.0.so; osname=
 Linux; processor=x86,lib/linux/amd64/libspsw-1.0.0.so; osname=Linux; 
 processor=x86-64,lib/windows/amd64/spsw-1.0.0.dll; osname=Windows7; o
 sname=Windows8; osname=Windows10; processor=x86-64,lib/windows/x86/sp
 sw-1.0.0.dll; osname=Windows7; osname=Windows8; osname=Windows10; pro
 cessor=x86

[launcher.properties.txt](https://github.com/bndtools/bndtools/files/1109975/launcher.properties.txt)

**Comment by bjhargrave** [comment]
If you use 

`-runprovidedcapabilities: ${native_capability}`

In your bndrun file, then the native capability for your development system will be used. If you are doing cross platform development, you will need a different bndrun file for each target system. For example, the bndrun for a Windows 7 system might have:

`-runprovidedcapabilities: ${native_capability;osname=Windows7;processor=x86-64}`

**Comment by aploese** [comment]
What is the reason to hardwire the intended "runtime" architecture in an jar?
Java can quit easily figure that out - and osgi does this...

**Comment by bjhargrave** [comment]
It is going in the launch properties resource of the exported jar. You, of course, don't need to put this in your bndrun file if you don't want it in the exported jar.

**Comment by aploese** [comment]
And how can I prevent this to happen?
I am using a eclipse workspace and project created by bnd so this is out of my reach.

**Comment by bjhargrave** [comment]
Don't have a `-runprovidedcapabilities: ${native_capability}` or `-runsystemcapabilities: ${native_capability}` in your bndrun.

**Comment by aploese** [comment]
there is no *.bndrun.

In eclipse
* I opend the bnd.bnd file
* switched to the Run tab
* pressed the Export Button

Here the content of said bnd.bnd:

Bundle-Version:					1.0.0.${tstamp}
Bundle-Description: 				\
	Test to load native libs path bug in equinox
	
-buildpath:  \
	osgi.enroute.base.api;version=1.0

Bundle-NativeCode: \
 lib/linux/arm_be/libnative-test.so; \
  osname=Linux; \
  processor=arm_be; processor=arm,\
 lib/linux/x86/libnative-test.so; \
  osname=Linux; \
  processor=x86,\
 lib/linux/x86_64/libnative-test.so; \
  osname=Linux; \
  processor=x86-64,\
 lib/windows10/x86_64/native-test.dll; \
  osname=Windows10; \
  processor=x86-64,\
 lib/windows10/x86/native-test.dll; \
  osname=Windows10; \
  processor=x86
  
-runbundles: \
	org.apache.felix.log;version='[1.0.1,1.0.2)',\
	native-service;version=snapshot,\
	org.apache.felix.configadmin;version='[1.8.8,1.8.9)',\
	org.apache.felix.scr;version='[2.0.2,2.0.3)',\
	org.eclipse.equinox.metatype;version='[1.4.100,1.4.101)',\
	org.osgi.service.metatype;version='[1.3.0,1.3.1)'
-runrequires: osgi.identity;filter:='(osgi.identity=native-service)'
