### ISSUE TITLE
MavenBndRepository breaks from version 1.0.14

### ISSUE THREAD

**Issue by dleangen** [bndtools/bndtools#1739]
Very strange, but when I arrive at a bundle version >= 1.0.14, the baseline repository exhibits very strange behaviour, and the workspace breaks.

Using a remote Nexus repository as the baseline.

For any version up to 1.0.13, the behaviour works as expected.

For any value "n" that I have tested, once n > 13, the version 1.0.n causes this weird behaviour and breaks the workspace.

**Comment by dleangen** [comment]
Using a MavneBndRepository like so:

```
-plugin.9.3.Release:  \
    aQute.bnd.repository.maven.provider.MavenBndRepository; \
    	releaseUrl			=   ${releaserepo}/; \
		name				=	Release
```

The index file looks like this:

```
org.example:org.example.application.api:1.0.n
```

Replace "n" with any number. Once the number is > 13, the repository breaks, and along with it, the workspace.

**Comment by dleangen** [comment]
Looks like this is not related to baselining. The Repository just happened to be used for baselining, but even when I turn off baselining, the problem with the repository persists.

I tried deleting the cache, removing the repo, and a few other tricks, but this strange behaviour persists.

**Comment by pkriens** [comment]
Any error messages?

**Comment by dleangen** [comment]
Strangely, none that I could see.

I noticed that the problem also occurs when the number of entries is "split" between different bundles as well.

With this "filter" file (or whatever you call it), it works (image1):

`
net.leangen.expedition.platform:org.example.application.api:1.0.0
net.leangen.expedition.platform:org.example.application.api:1.0.1
net.leangen.expedition.platform:org.example.application.api:1.0.2
net.leangen.expedition.platform:org.example.application.api:1.0.3
net.leangen.expedition.platform:org.example.application.api:1.0.4
net.leangen.expedition.platform:org.example.application.api:1.0.5
net.leangen.expedition.platform:org.example.application.api:1.0.6
net.leangen.expedition.platform:org.example.application.api:1.0.7
net.leangen.expedition.platform:org.example.application.api:1.0.8
net.leangen.expedition.platform:org.example.application.provider:1.0.1
net.leangen.expedition.platform:org.example.application.provider:1.0.2
net.leangen.expedition.platform:org.example.application.provider:1.0.3
net.leangen.expedition.platform:org.example.application.provider:1.0.4

`
<img width="242" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/9663141/27786876-dc2f589e-601d-11e7-97a0-58c0c485e677.png">

The moment I append this line to the end, the problem occurs (image2):

`
net.leangen.expedition.platform:org.example.application.provider:1.0.4
`

<img width="567" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/9663141/27786987-3fb77f4a-601e-11e7-83cd-467d52dc4e6e.png">

Notice that the provider is shown twice in the list, one "normally" and once in a way that appears to be "fully qualified" (which I don't usually see). Version 1.0.5 is in the "broken" list. It doesn't matter if the file actually exists or not in the repository, it never gets resolved.

I don't understand the behaviour, so I am having trouble explaining it!

It's the same issue once I get to version 1.0.14 when only the api was in the repository.

**Comment by dleangen** [comment]
Cannot reproduce
