### ISSUE TITLE
Integration Test: Macros disappear, when resolving run requirements

### ISSUE THREAD

**Issue by axtmann** [bndtools/bndtools#1743]
If you use the integration test template, when creating a new project, the bnd,bnd file contains all information about the test setup e.g. junit, mockito macros.

The -runbundles section looks like this:
```
# We need JUnit and Mockito to resolve the test cases at runtime. 
# Other runtime dependencies should be added as necessary
-runbundles: \
	${junit},\
	${mockito} 
```
After adding a run requirement
`
-runrequires: osgi.identity;filter:='(osgi.identity=test.api)'
`

And pressing resolve, result in the following section:
```
# We need JUnit and Mockito to resolve the test cases at runtime. 
# Other runtime dependencies should be added as necessary
-runbundles: \
	org.apache.felix.configadmin;version='[1.8.10,1.8.11)',\
	org.apache.felix.scr;version='[2.0.6,2.0.7)',\
	test.api;version=snapshot
```

But the test will not run with this. 

But it seems that the following section is the correct one, but not generated:
```
# We need JUnit and Mockito to resolve the test cases at runtime. 
# Other runtime dependencies should be added as necessary
-runbundles: \
	${junit},\
	${mockito}, \
	org.apache.felix.configadmin;version='[1.8.10,1.8.11)',\
	org.apache.felix.scr;version='[2.0.6,2.0.7)',\
	test.api;version=snapshot
```

Any time I press resolve the macro includes are overwritten.

**Comment by axtmann** [comment]
I use bndtools 
3.4.0.DEV-20170705-195430-gd293d7f

**Comment by bjhargrave** [comment]
Try using a merged property. For example:

```
-runbundles.junit: \
	${junit},\
	${mockito}
```
Then the resolve process will write a `-runbundles` to the bnd file and the values of both `-runbundles` and `-runbundles.junit` will be concatenated when the value of `-runbundles` is needed.

**Comment by axtmann** [comment]
This problem does not appear anymore.
