### ISSUE TITLE
BND 3.4.0.DEV - Eclipse Oxygen Ubuntu Performance Issues

### ISSUE THREAD

**Issue by axtmann** [bndtools/bndtools#1744]
bndtools: 3.4.0.DEV-20170705-195430-gd293d7f
Eclipse: Oxygen
OS: Ubuntu 17.04 64bit
Proc: Intel® Core™ i7-6700HQ CPU @ 2.60GHz × 8 
RAM: 32GB
I run eclipse with theses options:
UBUNTU_MENUPROXY=0 
SWT_GTK3=0 
GDK_DPI_SCALE=1.5

I currently test the new bnd tools and installed in into the brand new Eclipse Oxygen. I have experienced a lot of performances issues. The UI seems to freeze for about 20-30seconds when:
* I save *.bnd file
* I save a .java file that would not compile

The progress indicator shows nothing. But the Eclipse UI freeze detector logs something. For the two cases I attached you the logs.
I do not experience this in an ordinary Java project or within the PDE, sadly only in BND projects.

[save_bnd_file.log.txt](https://github.com/bndtools/bndtools/files/1132839/save_bnd_file.log.txt)
[saving_not_compilable_source.log.txt](https://github.com/bndtools/bndtools/files/1132840/saving_not_compilable_source.log.txt)

**Comment by gamerson** [comment]
Could you post a sample workspace that shows the problem with very long UI freezes?  Posting the repo on github would be the easiest way for us to take a look.

**Comment by axtmann** [comment]
Hi,
it seems that the problem does not occurs from start of the IDE. After a while working the freeze occurs.
As far as i have seen, the problem occures with any of my BND workspaces. Here is a sample workspace:
https://github.com/axtmann/bnd_sample_ws

**Comment by gamerson** [comment]
hey @axtmann  i've made an attempted fix here: https://github.com/bndtools/bndtools/pull/1745  

However, I need to discuss with other committers about this change as it my be missing some important cache invalidation pieces.

**Comment by gamerson** [comment]
Fixed in https://github.com/bndtools/bndtools/pull/1745
