### ISSUE TITLE
Bndtools website do not reflect the current tool release

### ISSUE THREAD

**Issue by nport** [bndtools/bndtools#1758]
On my understanding the current Bndtools version is 3.4.0.REL, but the following page seems to be not up to date: http://bndtools.org/installation.html

In particular:
* The page mention version 3.3 and clicking on the banner the 3.3.0.REL changelog is opened.
* Section "Installing development or older versions" was not updated since release 3.1.1.

Also page https://github.com/bndtools/bndtools/wiki/Changelogs does not mention 3.4.0.REL.

**Comment by nport** [comment]
Page https://github.com/bndtools/bndtools/wiki/Changelogs have to be updated too.

**Comment by bjhargrave** [comment]
Fixed.
