### ISSUE TITLE
Support importing without .classpath and .project

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1760]
I understand it is possible to import projects without needing to have .project and .classpath files. All information should come from the bnd.bnd file.

**Comment by bjhargrave** [comment]
Shouldn't we just add a gradle and/or maven task to make the necessary eclipse metadata files? Like the gradle eclipse plugin https://docs.gradle.org/4.1/userguide/eclipse_plugin.html#sec:eclipse_tasks and the maven plugin http://maven.apache.org/plugins/maven-eclipse-plugin/.

**Comment by pkriens** [comment]
Well, I would prefer both, but my preference is if it happens inside Eclipse and I understand there is an extension point for this. I never use the command line and it seems a bit odd to have to go to the command line to just make something an Eclipse project when Eclipse can do it much better and quicker?

**Comment by gamerson** [comment]
we have this support.  It was added back in 3.3 or 3.4.  You can point to a bnd workspace style set of projects and even if there are no .classpath. project files you can import them now.

**Comment by gamerson** [comment]
**File > Import > Bndtools > Existing Bnd Workspace**

**Comment by pkriens** [comment]
Wow!!!!!!! Thanks!

**Comment by gamerson** [comment]
but @bjhargrave  we could change the Bnd Workspace plugin to automatically apply the eclipse plugin and mutate the model like this:

```
eclipse {
        project {
                buildCommand 'bndtools.core.bndbuilder'
                classpath.containers << 'aQute.bnd.classpath.container'
                natures << 'bndtools.core.bndnature'
        }
}
```

It would take a bit more to setup all of the src -> bin, test -> bin_test and also things like Java levels (that is already done by the Eclipse importer)

**Comment by bjhargrave** [comment]
> but @bjhargrave we could change the Bnd Workspace plugin to automatically apply the eclipse plugin and mutate the model like this:

Yes. I would say we not apply the eclipse plugin, but if it is applied, then we configure it. Do you want to open an issue in the bnd repo for this?

**Comment by gamerson** [comment]
Done: https://github.com/bndtools/bndtools/issues/1763
