### ISSUE TITLE
Using -includeresource prevents classes from being included in the bundle

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bndtools#1762]
I have a very simple bundle with some classes. Everything was working just fine, when the requirement arose to include a file in the bundle. I put the file in directory resources/ and added 

```
-includeresource: resources
```

to `bnd.bnd`. Now I end up with *only* the resource file in my bundle (well, and `META-INF/MANIFEST`, of course). But the classes are missing. When I comment `-includeresource` out, I get the classes back in the jar, but of course, not my resource file. This can be reproduced using gradle, so it should be a bnd rather than a bndtools problem.

Using bnd 3.3.0

**Comment by bjhargrave** [comment]
This is expected. If there are no _content_ bnd instructions, then Bnd will include the entire output  (e.g. `bin` folder) in the bundle. See 

https://github.com/bndtools/bnd/blob/bdb3390ce8c49c7c244bd501a0dc543ba5adfe9c/biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java#L601-L628

But once you add a content instruction like `-includeresource`, you are then fully responsible for specifying the bundle contents.

**Comment by mnlipp** [comment]
Thanks for the fast response. The behavior may be *intended*, but it was definitely not *expected* (at least by me). This "feature" certainly deserves a more prominent mentioning than a comment in the source code. 

If the user is actually supposed to explicitly add the content, I'd also suggest to generate a warning such as "bin folder added as default content" if no content has been specified. This would prevent users from ending up with an empty jar *and* point them in the right direction.
