### ISSUE TITLE
If eclipse plugin is applied, the Bnd workspace plugin to automatically setup the required Bndtools eclipse project settings

### ISSUE THREAD

**Issue by gamerson** [bndtools/bndtools#1763]
If the developer applied the Eclipse plugin, and if they are using the Bnd workspace gradle plugin, then we can assume they also likely use (or should be using) the Bndtools eclipse plugin.  We could help this process by automatically modifying the eclipse project model to what Bndtools expects.

Something like
```
eclipse {
        project {
                buildCommand 'bndtools.core.bndbuilder'
                classpath.containers << 'aQute.bnd.classpath.container'
                natures << 'bndtools.core.bndnature'
        }
}
```

This would only be a start, as we would also want to setup the correct source/bin/test/bin_test folders along with the correct Java execution environment settings (1.7, 1.8, etc)

**Comment by bjhargrave** [comment]
Did you mean to open this in the bnd repo? I assume this is a request to change the gradle plugin for bnd workspace model?

**Comment by gamerson** [comment]
yeah i think bnd repo is the right place since that is where the code would live.
