### ISSUE TITLE
bnd(tools) pom plugin does not refresh properly

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bndtools#1772]
I just pushed a new snapshot of some bundles from a workspace. Then I changed to another workspace (in this case also another eclipse instance) and refreshed the repositories. (The bundles are made available using the BndPomRepository plugin.) However, I still had the old versions of the libraries just pushed. Removing the cache file didn't help, nor did a restart help. What eventually helped was removing the bundles from my ~/.m2-cache.

I don't know what "refresh" does, but I think it *should* check against new versions in the configured snapshot and release repositories. (Yes, also the release repository because the poms may use version ranges.)

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/pull/2114 for a solution in progress.
