### ISSUE TITLE
Component decorator appears incorrectly on 'parent' packages

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#1774]
The component decorator appears on component classes and also packages that contain component classes. This is intended behaviour.

However the decorator also appears on the "parent" package of a package that contains a component. For example if you have a component in package `org.example.impl` then the decorator will also appear on package `org.example` (NB this assumes there are some other non-component classes  in package `org.example` so that Eclipse doesn't hide it). See attached screenshot.

This is incorrect because in Java semantics `org.example` is not a parent of `org.example.impl`. Packages are not hierarchical, and the default presentation of packages in Eclipse is non-hierarchical.

<img width="276" alt="screen shot 2017-09-16 at 17 42 21" src="https://user-images.githubusercontent.com/6366/30514091-9b7d896e-9b06-11e7-97e6-fda7391b0640.png">

**Comment by wodencafe** [comment]
I'll have a look at this and see what I can do :)
