### ISSUE TITLE
Eclipse plugin/RCP development difficult without proper Target Definition

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bndtools#1780]
Developing e4 plug-ins and RCP apps is surprisingly great with Bndtools. The main missing piece imo is that a lot of discoverability in the e4 model editors depends on plug-ins being visible through the target definition. I assume the story with Eclipse 3.x plug-ins is similar.

Currently if we want workspace projects to see each other through the PDE tooling it seems we have to manually add generated/[project].jar to the target platform for every individual project (or various other hacky workarounds), which is an annoying maintenance burden. If we have external dependencies through repository types other than p2 it is even more of a pain to get them into the target definition.

The whole target definition concept seems a bit odd from the perspective of a Bnd developer rather than just resolving against the plug-ins on the project classpath, but this is the system we have to work with.

I propose contributing to the `org.eclipse.pde.ui.targetLocationProvisioners` and `org.eclipse.pde.core.targetLocations` extension points to allow adding Bnd repositories to the available target locations.

So if I work on this, would `bndtools.core` be the place for it? That seems to be where similar things are kept.

**Comment by timothyjward** [comment]
> I propose contributing to the org.eclipse.pde.ui.targetLocationProvisioners and org.eclipse.pde.core.targetLocations extension points to allow adding Bnd repositories to the available target locations.

:+1: to having better support for RCP development. I don't know enough about PDE to say for certain that this is the way to go, but it seems to be worth prototyping.

> So if I work on this, would `bndtools.core` be the place for it? That seems to be where similar things are kept.

I would suggest that this probably belongs in a new project, particularly if it adds PDE dependencies. We may even want to make it an optional feature (like the bndtools M2E support).

**Comment by eliasvasylenko** [comment]
Yes that makes sense, there were tons of new dependencies when I got started so I've taken your advice and moved into a new bndtools.pde project for now.

**Comment by eliasvasylenko** [comment]
Any thoughts or suggestions?

**Comment by timothyjward** [comment]
Thanks for your patience. There was a fair bit of work to get 3.5.0 out of the door, but now that's done it's a really good time to start working further on this. I've put some comments on the PR - I think it's mostly there, but there are a couple of issues.

**Comment by filippor** [comment]
You can look at https://github.com/filippor/bndPdeTarget
Its a pde extension that can add bnd artifact to target definition
