### ISSUE TITLE
add support for Eclipse variables (${project_loc} etc) for Runtime properties in bndrun files

### ISSUE THREAD

**Issue by CptMauli** [bndtools/bndtools#1811]
I want to be able - for instance - to quickly configure a logger during development without resorting to absolute paths

With the usual run configurations I can use e.g. ${project_loc:&lt;projectname&gt;} to refer to the current project. This is not supported by the bndrun files.

It would be nice to have the same functionality for all the "Runtime Properties"

**Comment by bjhargrave** [comment]
Eclipse variables don't exist when running from the command line (i.e. gradle). So bnd files cannot depend upon Eclipse variables. You should use a location relative to the project workspace. You can use the Bnd `${workspace}` variable which is the root of the Bnd workspace.

**Comment by CptMauli** [comment]
fair enough, but ${workspace} doesn't cut it, because if I start it from Eclipse it resolves to the root of the Eclipse installation, which is not helpful (e.g. if I need the path as an absolute path).

**Comment by bjhargrave** [comment]
'${workspace}` is the root of the Bnd workspace on the file system which is not necessarily the Eclipse workspace on the file system. The `cnf` folder is in the `${workspace}` folder.
