### ISSUE TITLE
Plugin cannot be installed in Eclipse Oxygen via Marketplace or Update site

### ISSUE THREAD

**Issue by estani** [bndtools/bndtools#1819]
Eclipse: Oxygen.1a Release (4.7.1a)
System: Ubuntu 17.10

While trying to install the plugin the following Exception is shown:
org.eclipse.equinox.p2.core.ProvisionException
Unable to read repository at https://dl.bintray.com/bndtools/bndtools/latest/content.xml.
Unable to read repository at https://dl.bintray.com/bndtools/bndtools/latest/content.xml.
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

The file (content.xml) is not there, am I missing something?

**Comment by estani** [comment]
... as usual got this sorted out with the next try exactly as I wrote down this issue...

The error was that a truststore was in used with a home-relative path `~/` which could not be sorted out. The file was not found, and `https` triggered this error. The rest was just a red hering...

**Comment by bjhargrave** [comment]
I think you have the same issue as #1813. That is, the issue is not with Bndtools code since you have not even installed it. It seems to be with the configuration of your java runtime. Are you using JDK 8 or JDK 9? I would suggest using JDK 8.

**Comment by bjhargrave** [comment]
See also http://www.oracle.com/technetwork/java/javase/9-0-4-relnotes-4021191.html#JDK-8189131 where it is stated that OpenJDK 9 on Linux (prior to 9.0.4) did not include root CAs.
