### ISSUE TITLE
bntools classpath container and repository trees refresh

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bndtools#1838]
I have a "standard" project configuration (https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#using-bnd-gradle-plugins-for-workspace-builds). When I refresh the repositories tree in the bnd perspective, the "Bnd Bundle Path" (`aQute.bnd.classpath.container`) is *not* automatically refreshed. New bundle versions found by the refresh (e.g. updated snapshots) become usable in the project only after I have closed and re-opened the project.

Is this supposed to work?

**Comment by bjhargrave** [comment]
It works when you have Build Automatically on. When the builder runs for the project, the Bndtools code to refresh the classpath container will execute. But if you have automatic builds off and Eclipse does not build your project, then the code to update the classpath container does not execute.

**Comment by mnlipp** [comment]
Okay, so it is supposed to work. I do have "Build Automatically" on, but it does not work for me. I'll try to figure out what makes my environment "special".

**Comment by mnlipp** [comment]
My (plugin's) fault. (Though... `aQute.bnd.service.Refreshable.getRoot()` really deserved some documentation.)
