### ISSUE TITLE
Bnd launch fails on first use of the day

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bndtools#1844]
I have noticed that when I sit down to my workspace in the morning to start work, trying to launch the target platform fails with the following error message:
![launcher error](https://user-images.githubusercontent.com/7224087/37006957-cfdf179a-212a-11e8-8b36-aa5bd55a6316.png)
Whether I click "Yes" or "No", Eclipse takes me to the Run Configurations dialog.

This keeps happening every time I try and launch, until I manually refresh the Bnd repository or restart Eclipse. Once reindexed and/or restarted it seems to go back to normal.

Platform is Windows 10/Eclipse Oxygen (release 2)/Bndtools HEAD.

I have observed the same behaviour on my home laptop (also Windows 10/Oxygen/Bndtools HEAD).

I also saw some error messages getting logged in the console which may have been related, but they disappeared before I thought to copy them. If they reappear tomorrow morning I'll paste them here.

**Comment by bjhargrave** [comment]
Closing. If this still occurs, please open a new issue with sufficient information to try and debug.

**Comment by kriegfrj** [comment]
This issue seemed to stop in the last couple of weeks, do maybe it got fixed. Happy for it to be closed.
