### ISSUE TITLE
Cryptic error message: Service-Component not FQN

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bndtools#1853]
I'm getting the following cryptic error message:

![service-component-not-fqn](https://user-images.githubusercontent.com/7224087/37508131-a6ad08d6-2941-11e8-8630-5f22027a7e6f.png)

> Service-Component entry '*' is not a FQN. Bnd no longer supports the deprecated Bnd DS annotations.

In context, this is not a particularly helpful error message. There are no Service-Component entries in my bnd.bnd file, or anywhere in my workspace (that I could find). I'm not sure if this is a legit error - if so, where is the root source, and if not then it must be a bug either in Bnd or Bndtools.

If it is a legit error, it would be nice to have more information about where it comes from.

The bnd source is apparently here:
https://github.com/bndtools/bnd/blob/8998ea4104da38aaaee3c1e6962610fa55cd4cf8/biz.aQute.bndlib/src/aQute/bnd/make/component/ServiceComponent.java#L123-L124

Perhaps as a minimum, this error message should also show context about which Jar file is generating this error message. It is possible that this is being caused by one of the bundles in one of the repositories that I have linked to during resolution - if that is the case, it would be better behaviour (I think) to simply skip that bundle and keep going rather than abandon the build altogether.

**Comment by bjhargrave** [comment]
Somewhere there is a `Service-Component` header with `*` in the value. Grep your source. It could be in cnf/build.bnd or cnf/ext/*.bnd.

**Comment by kriegfrj** [comment]
I did search the workspace but didn't find anything. I will try again after the weekend to be sure.

However, if I do manage to find it, it would be nice if Bnd/tools could be a little more forthcoming with information about where the offending clause is. :smile:

**Comment by bjhargrave** [comment]
> it would be nice if Bnd/tools could be a little more forthcoming with information about where the offending clause is.

Yes. But sometimes it is hard to know. At the time that check occurs, there is just a Processor with property key/value pairs. Its association with a specific source file is gone. 

Bnd can report the offending file when the error is known during parsing of the file. It is harder for semantic issues detected later in processing. But PRs to improve are welcome!

**Comment by bjhargrave** [comment]
Closing.
