### ISSUE TITLE
OutOfMemory exception when resolving bndrun file with Gradle plugin

### ISSUE THREAD

**Issue by ddoaj97** [bndtools/bndtools#1877]
We have a Gradle project containing a Bnd workspace that we build using the Bnd Gradle plugin version 3.5.0.  Some of our bndrun files wont't resolve anymore: they are stuck resolving for multiple minutes until they either throw an OutOfMemory exception or a GC Overhead Limit exceeded error. For some reason this only occurs with the Gradle plugin, the bndrun files resolve fine within Eclipse using the Bndtools plugin version 3.5.0.REL-20170929-190052-ga0d7a6b (which I suppose is backed by the same Bnd release).

Using a debugger we tried to track down the cause of the issue and we were able to pinpoint the problem to a single problematic bundle. As soon as a package of this bundle is imported by at least 2 other bundles then the Bnd Gradle plugin gets stuck in an infinite loop during the resolve process and eventually runs out of memory. The source of the infinite loop is in the org.apache.felix.resolver.ResolverImpl class. Inside the "findValidCandidates" method there is a while loop that only exits as soon as it resolves a set of bundles that satisfy all of the requirements, but we noticed that it never finds a valid solution, instead it always returns at least 1 error. When we pause the debugger to check the error message we noticed that some of the resolve errors don't make sense:

```
<<INITIAL>> version=null => Uses constraint violation. Unable to resolve resource eu.vdv.domain.customerorders [eu.vdv.domain.customerorders version=5.1.1] because it is exposed to package 'net.company.your.api_ois100' from resources eu.vdv.m3.soap [eu.vdv.m3.soap version=1.1.3] and eu.vdv.m3.soap [eu.vdv.m3.soap version=1.1.3] via two dependency chains.

Chain 1:
  eu.vdv.domain.customerorders [eu.vdv.domain.customerorders version=5.1.1]
    import: (&(osgi.wiring.package=net.company.your.api_ois100)(&(version>=1.0.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package: net.company.your.api_ois100
  eu.vdv.m3.soap [eu.vdv.m3.soap version=1.1.3]

Chain 2:
  eu.vdv.domain.customerorders [eu.vdv.domain.customerorders version=5.1.1]
    import: (&(osgi.wiring.package=eu.vdv.m3.soap)(&(version>=1.1.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package=eu.vdv.m3.soap; uses:=net.company.your.api_ois100
  eu.vdv.m3.soap [eu.vdv.m3.soap version=1.1.3]
    import: (&(osgi.wiring.package=net.company.your.api_ois100)(&(version>=1.0.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package: net.company.your.api_ois100
  eu.vdv.m3.soap [eu.vdv.m3.soap version=1.1.3]
```

The error claims the bundle is exposed to two different versions of "eu.vdv.m3.soap" but both imports are clearly the same version (1.1.3) but somehow it doesn't consider these versions to be identical.
Our "eu.vdv.m3.soap" bundle has the following versions in the release repo: 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3 and the version in the Workspace is unchanged since latest release so its version is also at 1.1.3.

After some more testing we have found that:
- The problematic bndrun files always resolve fine in Eclipse, but never in Gradle.
- The resolve works fine if we restrict the runrepos to search in the Workspace exclusively or in our release repo exclusively. As soon as the Gradle plugin tries to resolve using both the Workspace and release repo it throws the OutOfMemory exception.
- It is not a memory issue, we have tried running with 4 gigabytes of heap space and it still doesn't resolve.
- If we remove all released versions from the repo except the latest version (1.1.3) then it successfully resolves with Gradle.
- With a very simple "runrequires" list the problem never occurs. If the "eu.vdv.domain.customerorders" bundle is the only one in the list it always resolves fine. Only in very specific combinations of bundles that use the "eu.vdv.m3.soap" bundle does the problem occur.

Does anyone have an idea what is causing it? Unfortunately I cannot give a simple test case because it only occurs when resolving a rather large runrequires list.

**BndTools version**: 3.5.0.REL-20170929-190052-ga0d7a6b
**BndTools Gradle plugin version**: 3.5.0 (Git-Descriptor: 3.5.0.REL, Git-SHA: bb70d103dd9c02096f516a0581be0fe9c252d581)
**Gradle version**: 4.6
**Java version**: 1.8.0_152 (Oracle Corporation 25.152-b16)
**OS**: Windows 8/10

**Comment by bjhargrave** [comment]
I think this may be the same root cause at https://github.com/bndtools/bndtools/issues/954. The issue is that a long resolve operation logs so much that it causes OOM. The resolve operation in Bndtools uses ResolverLogger (which avoids OOM) while the Gradle resolve task does not.

**Comment by ddoaj97** [comment]
Here is the stacktrace of the OOM:
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.felix.resolver.util.CandidateSelector.copy(CandidateSelector.java:45)
        at org.apache.felix.resolver.util.OpenHashMapList.deepClone(OpenHashMapList.java:39)
        at org.apache.felix.resolver.Candidates.copy(Candidates.java:1143)
        at org.apache.felix.resolver.Candidates.permutate(Candidates.java:1196)
        at org.apache.felix.resolver.ResolverImpl$ResolveSession.permutateIfNeeded(ResolverImpl.java:134)
        at org.apache.felix.resolver.ResolverImpl.checkPackageSpaceConsistency(ResolverImpl.java:1528)
        at org.apache.felix.resolver.ResolverImpl.checkPackageSpaceConsistency(ResolverImpl.java:1558)
        at org.apache.felix.resolver.ResolverImpl.checkConsistency(ResolverImpl.java:577)
        at org.apache.felix.resolver.ResolverImpl.findValidCandidates(ResolverImpl.java:530)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:393)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:329)
        at biz.aQute.resolve.BndResolver.resolve(BndResolver.java:29)
        at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:181)
        at biz.aQute.resolve.ProjectResolver.resolve(ProjectResolver.java:104)
        at biz.aQute.resolve.Bndrun.resolve(Bndrun.java:94)
        at biz.aQute.resolve.Bndrun.resolve(Bndrun.java:87)
        at biz.aQute.resolve.Bndrun$resolve$0.call(Unknown Source)
        at aQute.bnd.gradle.BndPlugin$_apply_closure1_closure24_closure77_closure78_closure79.doCall(BndPlugin.groovy:452)
```
The stactrace looks similar to the issue you linked.

I also took a CPU sample and heap dump with VisualVM:

![bnd_memory](https://user-images.githubusercontent.com/17296796/38808936-192bf860-4182-11e8-90da-475ac38c9587.png)
![bnd_cpu_sample](https://user-images.githubusercontent.com/17296796/38808937-1946c38e-4182-11e8-8162-f02d19a5a86f.png)

As you can see all the memory is consumed by millions of instances of CandidateSelector.

**Comment by bjhargrave** [comment]
Well the only difference I see between how Bndtools calls the resolver and how gradle plugin calls the resolver is that the gradle invocation passes a logger to the felix resolver which logs to memory (a Processor). Bndtools uses a logger which writes to a temp file and thus wont exhaust memory.

**Comment by bjhargrave** [comment]
Please try the latest 4.0 SNAPSHOT from cloudbees to see if the above change helps.

**Comment by ddoaj97** [comment]
We tested the latest 4.0.0-SNAPSHOT build with our runner. Interestingly the bndrun file now succesfully resolves, but it doesn't seem to be related to the changes of the logger. We also tested the 4.0.0-SNAPSHOT from a week before and resolving works fine with that version as well. If you look at the Heap Dump screenshot I posted you will also see that the majority of the memory consumption comes from the Apache Felix Resolver and not from any classes related to the Bnd logger.

Next we tried resolving all of the bndrun files in our project, but the problem just seems to have moved: the problematic bndrunner resolves, but now there are a couple of others that have started failing with an OOM!

It still seems to me that the resolve procedure is bugged. The fact that this only occurs inside Gradle is probably due to some very minor differences that happen to trigger a bug in the Apache Felix resolver.

I searched the bnd repository to see what changes between 3.5.0 and 4.0.0-SNAPSHOT might have impacted the resolve process. Bnd has switched from using Apache Felix Resolver version 1.12 to version 1.16. There only seems to be one notable change in the Felix Resolver that might be relevant. Since 1.14 they fixed issue [FELIX-5601](https://issues.apache.org/jira/browse/FELIX-5601) where the resolver didn't always find a valid solution. Although this fixes some problems it also introduced a regression: The Apache Karaf project had to back down to version 1.12 because they started getting the same OOM (see [FELIX-5663](https://issues.apache.org/jira/browse/FELIX-5663)). On the Apache Karaf mailing list someone else has complained about the same problem (http://karaf.922171.n3.nabble.com/Karaf-stuck-at-startup-in-org-apache-felix-resolver-ResolverImpl-resolve-td4050508.html).

The Felix issue is already open for about a year without a fix. I assume it's not an easy fix because like we experienced, the OOM error only happens in very specific circumstances.

I suppose you can close this issue considering that the bug isn't in the Bnd project itself and will have to be fixed in the Apache Felix Resolver. We currently work around it by removing unused older versions of bundles from the cnf folder.

**Comment by bjhargrave** [comment]
Makes sense. Thanks for the info.
