### ISSUE TITLE
LocalIndexedRepo outside `cnf` leads to wrong paths in Eclipse's 'Bnd Bundle Path'

### ISSUE THREAD

**Issue by jest** [bndtools/bndtools#1890]
When using bundles from `LocalIndexedRepo` located outside the `cnf` project, Bndtools cannot correctly reference such bundles on Eclipse build path.

Bndtools 4.0 on Oxygen.3a.

Minimal broken example, based on standard Bndtools workspace/project templates, is on https://github.com/jest/test-bndtools-release-repo-not-on-buildpath. History commits show working and not working cases.

All cases build correctly using Gradle.

In short, my `cnf/build.bnd` is:

```
-plugin.4.Release: \
	aQute.bnd.deployer.repository.LocalIndexedRepo; \
		name = Release; \
		pretty = true; \
		local = ${workspace}/dist/bundles

-releaserepo: Release
-baselinerepo: Release
```

the project's `bnd.bnd` is

```
-buildpath: some.api;version=@1.1
```

The bundle can be correctly resolved in Repositories view:

![image](https://user-images.githubusercontent.com/161816/40542226-92772c42-601f-11e8-8b0d-f9e4791daa28.png)

but compilation fails:

![image](https://user-images.githubusercontent.com/161816/40542263-c68e2792-601f-11e8-9b9d-b9b89277b10b.png)

because the full path to the bundle is broken (is missing the `${workspace}` prefix):

![image](https://user-images.githubusercontent.com/161816/40542337-1b099310-6020-11e8-97b3-7832f7d7cb4e.png)

**Comment by bjhargrave** [comment]
Does `local = ${fileuri;${workspace}/dist/bundles}` work better?

**Comment by jest** [comment]
No, it does not, then the repository becomes empty. I guess it's sbecause  `IndexedFileRepo` uses `new File(String pathname)` and giving it the result of `${fileuri;...}` (i.e. `file:/...`) won't make it use `new File(URI uri)`. And such pathname doesn't exist.

**Comment by bjhargrave** [comment]
The problem is that `dist` is not an Eclipse project. When I import it into the Eclipse workspace, then everything works fine. Bndtools knows that the `dist` folder is within the Bnd workspace and expects it to also be in the Eclipse workspace. So when Bndtools converts the file system path to an Eclipse IResource, it expects that to be a resource in the Eclipse workspace. Since `dist` was not an Eclipse project, this did not work as expected and the "workspace" location was elided.

**Comment by jest** [comment]
I don't understand... Did you close it as "won't fix"?

**Comment by bjhargrave** [comment]
I closed it because it was a user error. You need to make sure `dist` is a project in Eclipse.
