### ISSUE TITLE
[Bndtools 4.0.0.REL] Require-Capability: osgi.extender change the minVersion

### ISSUE THREAD

**Issue by guidfort** [bndtools/bndtools#1894]
I build a lot of bundles with the bndtools, on two bundles the minVersion from osgi.extender change from 1.3.0 to 1.4.0. 

Here part of the manifest.mf 

bndtools 3.5.0
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.component)(version>=1.3.0)(!(version>=2.0.0)))"

bndtools 4.0.0
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.component)(version>=1.4.0)(!(version>=2.0.0)))"

With version 1.4.0 I have problem in my runtime environment. Both bundles I build now with version 3.5.0.

What is the reason for the version change.

**Comment by timothyjward** [comment]
> What is the reason for the version change.

Are you using the OSGi R7 annotations for Declarative Services? 

These annotations (as produced by the OSGi Alliance) are now meta-annotated with an `@Requirement` for the DS 1.4 extender. This was done to prevent tools like bnd from having to use heuristics to guess the correct version of DS to require. The `@Requirement` meta-annotation is a new feature of R7 and is supported in bnd 4.0.0, but not in 3.5.0 (which is too old).

This is probably why you are seeing this behaviour.

**Comment by timothyjward** [comment]
> @requirment I not use in my sourcecode.

You don't need to use it directly in your source code, it is present on the R7 `@Component` annotation. If you have the OSGi R7 compendium, or the DS 1.4 annotations, on your build path then you will pick up the requirement.

Are you using the OSGi R7 annotations for Declarative Services?

**Comment by guidfort** [comment]
Unaware. With [R7](https://blog.osgi.org/2018/03/osgi-r7-highlights-declarative-services.html) I check the sourcecode.

**Comment by guidfort** [comment]
I have found the problem. In two sources there are two OCD definitions with @interface DocAppConfig {
}

And this defintion was empty. I put inside a dummy and then the build was  ok.
@interface DocAppConfig {
  String __dummy();
}

**Comment by timothyjward** [comment]
Ok, so empty (marker) component property types are only supported from DS 1.4. This detection was added into bnd 4.0, which erroneously allowed them in earlier versions.
