### ISSUE TITLE
Eclipse Java Editor cannot not see class inheritance from jdo-enhanced classes in Bndtool project

### ISSUE THREAD

**Issue by tee4cute** [bndtools/bndtools#1895]
First of all, this issue relates to **Eclipse Java Editor**, **Datanucleus** and **Bndtool**. I'm not sure that where the cause of this issue originated from. I've tried to contact _Datanucleus_ team and they suggested that it might relate to Eclipse's build mechanism (not DN's problem). So, I think this may include _Eclipse_ itself or the _Bndtool_ plugin.

### **Java Version**

```
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

### **Bndtool Version**

**Bndtools 4.0.0 REL** (Installed from _Eclipse Market Place_ updated to latest version released on the market place)

<img width="519" alt="bndtool version" src="https://user-images.githubusercontent.com/4979546/41500446-82733e1e-71bb-11e8-9220-45a2b4a32ff8.png">

### **Eclipse Version**

Using **Eclipse Mars.2**, but, also tested on **Eclipse Oxygen (latest)**, not working also.

### **Reproducing Steps**

Simplified version of project setup/dependency:

**Bundle "security.api"**

```
// JDO Persistent Class
public class User {
    // ... some code ommitted ....
    public String getUserId();    
    // ... some code ommitted ....
}
```

**Bundle "app.api"**

```
// JDO Persistent Class
public class UserSubClass extends User {

}

// App Logic Facade (OSGi Service Intf)
public interface MyAppFacade {
    // ... some code ommitted ....
    public UserSubClass createUserSubClass(UserSubClass account);
    // ... some code ommitted ....
}
```

**Bundle "app.impl"**

```
// Facade/OSGi Service Impl
public class MyAppFacadeImpl implements MyAppFacade {
    // ... some code ommitted ....

    public UserSubClass createUserSubClass(UserSubClass account) {

        // Eclipse java editor will report: 
        // "The method getUserId() is undefined for the type ...."
        account.getUserId(); 

    }

    // ... some code ommitted ....
}
```

**The _Eclipse Java Editor_ will report:**

> The method getUserId() is undefined for the type UserSubClass

**As you can see in this image:**

![805rj](https://user-images.githubusercontent.com/4979546/41500506-d4ccd854-71bc-11e8-9e8b-6f2ce861d5a7.png)

The variable `account` in the image above is an instance of class `UserSubClass` in which that it extends `User`. So, I'm expecting that we could call method `getUserId()` without any error reported from the editor.

The more weird thing is ... it seems that the _java compiler_ (javac) can see `getUserId()` method inherited from class `User`, nor, it is **NOT reported as an error in _Eclipse Project Explorer_**, so,  I can compile & build the bundle jar file normally!

This problem happens only if the `Bnd Build Path` points to released bundle jar in `Repository Cache (~/.m2/*)`, which is a **JDO already-enhanced version**.

To say more clearly, if the `Bnd Build Path` is pointing to depending bnd project directly (putting `;version=latest` after the depending bundle symbolic name, for example, `security.api;version=latest` & `app.api;version=latest`), this problem will go away.

At the beginning of the project, I'm not facing this situation because all of `Bnd Build Path`s are pointed to the bnd project directly. But, at this time, the project is a lot more expanded and developed, we currently have 50+ bundles. So, we decided to release all stable bundles into the repository and let everyone import from it. This helps us reduce a lot of compilation time when you restart Eclipse (you don't need to wait for datanucleus enhancer to enhance all of your classes from low-level stable bundles up to the top all over again).

**My workarounds (none of these is working):**

- Try to attach source code to the bundle jar in `.classpath` file.
- Try to distribute source code along with the bundle jar in `OSGI-OPT/src` folder.
- Try to upgrade _Eclipse (Oxygen)_ and _Datanucleus (v5)_ to the newest one.
- Try to clean & build projects entirely (like creating a new workspace and setup the env from scratch).

The reason I tried to attach source along with the bundle jar is that I'm speculating that _Eclipse Java Editor_ may resolve class inheritance from source code instead of looking into compiled `.class` files, but, It's still not working.

I also have a look into decompiled version of released jdo-enhanced bundle jar, but, notice nothing wrong.

**Decompiled version of class `User`:**

![nb0tc](https://user-images.githubusercontent.com/4979546/41500676-72cca432-71c0-11e8-9366-b5c2e1727863.png)

You can see that it ACTUALLY CONTAINS `getUserId()` method. And, it is a JDO-Enhanced version because the method content is delegating method call to `dnGetuserId(this)`.

**Decompiled version of class `UserSubClass`:**

![yladn](https://user-images.githubusercontent.com/4979546/41500684-9ee68420-71c0-11e8-8057-21b5f7efb9c2.png)

You can see that it ACTUALLY EXTENDS class `User`. And, it is a JDO-Enhanced version because the interface `Detachable` and `Persistable` is automatically injected by the enhancer from `@PersistenceCapable` annotation.

PS. I don't think that it is the problem of _JDO Enhancer_ nor _Java Compiler_ (javac) since, as I mentioned earlier, I can compile & build the bundle jar file normally!

### **The only weird thing is:**

**WHY ECLIPSE JAVA EDITOR COULD NOT SEE METHODS INHERITED FROM THE JDO ENHANCED SUPER CLASS?**

_Note: The original post is located on [stackoverflow](https://stackoverflow.com/questions/50849378/datanucleus-build-time-enhancement-break-class-inheritance-in-eclipse-java-edito)._

**Comment by tee4cute** [comment]
Hi, @bjhargrave. Thanks for your quick reply.

I tried to setup a simple demonstration project on GitHub as you suggested (for 3 hours). But, I could not reproduce the issue. I think there might be some points --the true cause of the issue-- that I'm missing. During trying to reproduce the issue, I also noticed that it only happens on some source files (`.java` files) within the same bnd project (the other files also contain the same `getUserId()` method call). So, I decided to record the VDO screen to demonstrate the issue instead in case of it may give you some hints that you can shed light on me for the next step to do.

https://drive.google.com/file/d/1tBo_kZIm1b75vArlm3rQUxqUQ4upLkD5/view?usp=sharing

For the real project, I could reproduce this issue every time I cleanly checkout from my company's repository on any computer. Hence, it might not be an issue like "not refreshing cached jar files", etc. Sorry for that I cannot provide you a reducing code at this time because I cannot give you an access to my company's repo.

**Comment by bjhargrave** [comment]
Your video would seem to indicate some bug in the Eclipse JDT incremental compiler. Since the code compiles until you comment out a line, this means that Bndtools configuration of the project's classpath must be ok. I suggest you try and file a bug against Eclipse JDT.

**Comment by tee4cute** [comment]
Thanks @bjhargrave. I'll post the update on this issue if I get any responses from Eclipse JDT team.
