### ISSUE TITLE
Problem with testpath resolution in Bndtools Alpha 

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bndtools#1906]
I gave the Bndtools Alpha version a try and encountered problems with testpaths since the bundles specified in testpath could not be used for resolution. All the bundles in the workspance showed errors since all the imports in test classes were missing. I switched back to the release version and everything started working again.

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bndtools/wiki/Changes-in-4.1.0#backwards-compatibility.

You need to mark you test source folders as **Contains test sources** so they have visibility to the `-testpath` entries.

**Comment by bjhargrave** [comment]
I just released a fix to Bndtools to only mark `-testpath` entries as **Visible only for test source** when at least one source folder in the project is marked as **Contains test sources**.

So this is more backwards compatible. Until a user marks a source folder as **Contains test sources**, `-testpath` entries will remain visible for all source folders.
