### ISSUE TITLE
Runtime Classpath is transitive

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1922]
I ran into a problem in bnd that the JUnit runner is calculating the class path transitively. Looking at the code, BJ found BndContainerRuntimeClasspathEntryResolver. This class was added two years ago by @gamerson and is clearly transitive.

Having a transitive classpath for JUnit is convenient (as always) but it also means you get a lot of unwanted dependencies since it looks like we do not distinguish between test and build paths?

So do we really want transitive dependencies? The 'native' launcher from bnd does not have transitive dependencies.

**Comment by bjhargrave** [comment]
Launching for running JUnit tests should use a non-transitive classpath. It should be `-testpath` followed by `-buildpath` (this is what the Bnd Gradle Plugin does). The Bnd Bundle Path classpath container in Bndtools does not do transitive dependencies, so JUnit launching must not either. Otherwise, you are unable to properly control the classpath for JUnit test execution in a project.

**Comment by pkriens** [comment]
Any progress on this, it really sucks ... I doing some work on the JUnitFramework and any transitive project that has a framework on its -buildpath throws me off :-(

**Comment by bjhargrave** [comment]
Yes, the issue is for Bnd workspace builds. For Bnd workspace builds, the junit tests must use a non-transitive classpath.

**Comment by pkriens** [comment]
Ok, but such a pretty fundamental change will need some discussion. It is currently a terrible sucky model if you happen to use different versions of the same artifacts. Something quite common in our world, if only to test ...

I think we need to revert this to go back to the old behavior.

**Comment by rotty3000** [comment]
I don't think we can do that without breaking enRoute which is m2e based.

**Comment by pkriens** [comment]
Well, now my stuff is broken ... don't we have a rule to not change things that break others?

**Comment by pkriens** [comment]
I am also not clear why a the JUnit class path for Bndtools can be used for m2e? Don't they have their own support for Junit?

**Comment by bjhargrave** [comment]
We have to do something. The current situation in untenable. The code can tell of a Bnd workspace build is in effect by the presence of the bnd classpath container in the project's classpath and then either do transitive dependencies (for m2e) or non-transitive dependencies (for Bnd workspace).

**Comment by rotty3000** [comment]
so I was just looking at this and I think we can safely disable it just from the `_plugin.xml` of bndtools.core. I think I was wrong that this would affect m2e, but I can dig into that to make sure. In the meantime we can disable it.
