### ISSUE TITLE
report unused buildpath and testpath entries

### ISSUE THREAD

**Issue by jpchristen** [bndtools/bndtools#1923]
It would be really helpful to see which entries are really used as it would be way easier to identify entries you forgot to remove earlier.

**Comment by bjhargrave** [comment]
Try `-pedantic: true` to get information regarding this.

**Comment by jpchristen** [comment]
I added `-pedantic: true` to the build.bnd file, but the only information I got out of this are warnings concerning name duplicates: "Duplicate name osgi.service used in header: ...". There is no information, error or warning concerning unused entries, am I doing something wrong here?

**Comment by pkriens** [comment]
you are sure you have unused entries?

**Comment by jpchristen** [comment]
I added a bundle to the buildpath of another one that was not in there while not changing any code. Therefore my addition should be definitely unused, shouldn't it be?

**Comment by pkriens** [comment]
Well, I guess this is why it was not documented. The code is calculating something but requires testing. The following code is relevant:

https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L1851
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java#L665-L666
So if you want to make a PR

**Comment by pkriens** [comment]
I actually got them in the gradle build:

     warning: Imports that lack version ranges: [javax.xml.namespace, javax.xml.parsers, javax.xml.xpath, junit.framework, org.apache.tools.ant, org.apache.tools.ant.types, org.easymock, org.jmock.core, org.w3c.dom, org.xml.sax, org.xml.sax.helpers]
     warning: Unreferenced class path entries [hamcrest-all-1.3]
