### ISSUE TITLE
${if} macro not working correctly in some condition

### ISSUE THREAD

**Issue by sandyambule** [bndtools/bndtools#1924]
For example,
i want to add optional imports in bundles for certain packages based on some condition,
my macro definition is as below,
```
aop-imports: ${if;${isProviderBundle}; \
        org.apache.xerces.jaxp.validation;resolution:=optional \   
}
```

i above case `";resolution:=optional"` treating as second part of `${if}` macro.
there should be some way to add `";"` character

Expected Output is:
 `  org.apache.xerces.jaxp.validation;resolution:=optional`

but getting this,
`org.apache.xerces.jaxp.validation`

**Comment by bjhargrave** [comment]
If you need to include a semicolon in a string, you need to escape it with `\` (In a bnd file, you will need to do double `\` since the properties file parsing will consume one of the backslashes). Otherwise the parser thinks the `resolution:=optional` is the else clause of the if.

So:

```
aop-imports: ${if;${isProviderBundle}; \
        org.apache.xerces.jaxp.validation\\;resolution:=optional \   
}
```
