### ISSUE TITLE
OSGiRepository does not seem to refresh when "Refresh Repositories" or "Refresh Repositories Tree" is pushed

### ISSUE THREAD

**Issue by jellenelis** [bndtools/bndtools#1930]
I recently upgraded to bndtools 4.0.0 and in that effort had to change FixedIndexRepository with OSGiRepository. With this setup refreshing repositories doesn't seem to work anymore, I have to wait for the poll time to see new bundles appear, which means either setting a foolishly small poll time or waiting. When I look at the code for OSGiRepository on https://github.com/bndtools/bnd/blob/4.0.0.REL/biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java#L271 I would expect getIndex(true) would have to be invoked instead of getIndex(false) to actually refresh the index.

Java version: 1.8.0_181
OS: Ubuntu 18.04
Bndtools version: 4.0.0 retrieved through Eclipse Marketplace

**Comment by pkriens** [comment]
Can you provide a PR and a test case?

**Comment by jellenelis** [comment]
I can provide a pull request, but I have no idea how to test this in 
code. Could you provide me with some pointers on how that could be done?

**Comment by pkriens** [comment]
Look at `aQute.bnd.repository.osgi.OSGiRepositoryTest` in `biz.aQute.repository` project (`test` folder`. The `testRepo()` test is testing refresh.

**Comment by jellenelis** [comment]
If I understand correctly `testPollingWithFile` tests whether or not the repo refreshes based on the test interval, `testBndRepo` tests whether getIndex(true) starts a task. Is this correct [not familiar with the bndtools codebase (yet), thanks for any support]?

I can implement a new test case that tests that refreshing actually refreshes the repository, that must be doable.

**Comment by pkriens** [comment]
It is a long time ago ... just play with the code and see what happens :-)

**Comment by jellenelis** [comment]
OK, will do, will take a while though.

**Comment by pkriens** [comment]
Oh come on, you got the whole evening! :-)

**Comment by jellenelis** [comment]
I wrote a test case for what I think might be the problem, i.e. the index not being updated on refresh. You can find it at [https://github.com/jellenelis/bnd/commit/04d14e4f7b0bde6efc92759519e2aa9886a09078](https://github.com/jellenelis/bnd/commit/04d14e4f7b0bde6efc92759519e2aa9886a09078). It basically just updates the index (as seen in one of the other tests and checks whether or not the cache of the OSGiIndex actually changes. With the original code, it fails, using `true` for `refresh` actually makes the test case pass. 

This seems nice, but I saw that there are `RepositoryListenerPlugin`s that would like to be notified whenever a repository is refreshed. I would think they would need to be notified when the user refreshes the repositories as well, or is this not necessary? I did not find a straightforward way to be able to notify them. Depending on your feedback, I might consider adding support for that as well.

**Comment by pkriens** [comment]
You can look on `MavenBndRepository.refresh()` how the notifying of the repository listeners goes

I think you should get the Promise from the OSGiIndex that getIndex created and then on the callback when the promise is satisfied you notify the listeners.
