### ISSUE TITLE
m2e and bndtools do not create same output due to incorrect version number

### ISSUE THREAD

**Issue by hwieder** [bndtools/bndtools#340]
Hi!

We are working with m2e plugin (and maven-bundle-plugin) and bndtools together at our company. The following bug exists: The on-the fly build of bndtools does not create the same output as the maven build, because bndtools is not able to recognize the correct version from the POM. In opposite to the description of neil bartlett the include of the pom.xml does not work (or the evaluation of the property ${pom.version} fails).

This must be solved!!

**Comment by bjhargrave** [comment]
Old issue. Bndtools now has m2e support.
