### ISSUE TITLE
[windows platform][Indigo]About building bndtools behind proxy server and launching

### ISSUE THREAD

**Issue by tangyong** [bndtools/bndtools#384]
Did anybody build bndtools behind proxy server  on windows platform successfully?

When I build bndtools behind proxy server on windows platform , I got the following error:

E:\bndtools\master\bndtools.build>ant build p2
Buildfile: build.xml

init:
[bndprepare] 1 Errors
[bndprepare]  junit.osgi;version=3.8 Not found in [bnd-cache, aQute.lib.deploy
.obr.OBR@18b81e3, aQute.lib.deployer.obr.OBR@1fc6e42, Eclipse-3.5.2]
[bndprepare] Errors during Eclipse Path inspection
[bndprepare]    at aQute.bnd.ant.PrepareTask.execute(PrepareTask.java:40)
[bndprepare]    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.
va:288)
[bndprepare]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[bndprepare]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcc
sorImpl.java:39)
[bndprepare]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingM
hodAccessorImpl.java:25)
[bndprepare]    at java.lang.reflect.Method.invoke(Method.java:597)
[bndprepare]    at org.apache.tools.ant.dispatch.DispatchUtils.execute(Dispatc
tils.java:106)
[bndprepare]    at org.apache.tools.ant.Task.perform(Task.java:348)
[bndprepare]    at org.apache.tools.ant.Target.execute(Target.java:357)
[bndprepare]    at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bndprepare]    at org.apache.tools.ant.Project.executeSortedTargets(Project.j
a:1337)
[bndprepare]    at org.apache.tools.ant.Project.executeTarget(Project.java:130

[bndprepare]    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(
faultExecutor.java:41)
[bndprepare]    at org.apache.tools.ant.Project.executeTargets(Project.java:11
)
[bndprepare]    at org.apache.tools.ant.Main.runBuild(Main.java:758)
[bndprepare]    at org.apache.tools.ant.Main.startAnt(Main.java:217)
[bndprepare]    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
[bndprepare]    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104

BUILD FAILED
Errors during Eclipse Path inspection

Is there any configuration to build bndtools for the case?

**Comment by bjhargrave** [comment]
I don't believe this is an issue anymore with the support for proxies in the http code used by the repos in the build.
