### ISSUE TITLE
NPE from repo when location URL is invalid

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#455]
An NPE was thrown when the URL entered was `file:${workspace}/cnf/repo` and the workspace resolved to `D:\Workspace`. This was on Windows XP... cannot reproduce on Mac.

**Comment by bjhargrave** [comment]
> java.lang.NullPointerException
> at org.bndtools.builder.validate.ProjectPathsValidator.validate(ProjectPathsValidator.java:66)

The fix fixes the above NPE.

FileRepo location does not support URLs of any form. The must be file paths. So I don't know why that is related to an NPE, but given the new incremental builder and classpath container, I could not reproduce an NPE by setting the FileRepo location to a URL.

> java.lang.NullPointerException
> at org.osgi.service.indexer.impl.SCRAnalyzer.analyzeResource(SCRAnalyzer.java:69)

This second NPE is a bnd issue which I will investigate separately.
