### ISSUE TITLE
Fix the transitive dependencies in this bnd issue

### ISSUE THREAD

**Issue by m4rr5** [bndtools/bndtools#461]
For the next version of Bndtools, make sure we the fix https://github.com/bndtools/bnd/issues/207 so the command line and Eclipse builds work the same way. I also discussed this previously on the mailing list, see:

https://groups.google.com/forum/?fromgroups#!topic/bndtools-users/vYpe3NA_eW8

Note: updated this issue after consensus was that this is an issue in Bndtools, not bnd.

**Comment by derheld42** [comment]
Closing this out since #1003 most likely resolves the issue. Please reopen if the new rules do not resolve the issues discussed. If the new rules work, they will become the new default eclipse access rules.To try the new rules, add this to cnf/build.bnd:

eclipse.newaccessrules: true
