### ISSUE TITLE
Inconsistent eclipse access rules when using sub-bundles

### ISSUE THREAD

**Issue by mgrig** [bndtools/bndtools#475]
Adding to Bnd Build Path 2 sub-bundles from the same project leads to inconsistent access rules for these sub-bundles.

bndtools.master:68c655.
Steps to reproduce:
- create 2 projects in eclipse ProjA and ProjB
- add 2 packages to ProjA: package1 and package2 (with a dummy class in each of them)
- create 2 subbundles in ProjA: subbundle1 exports only package1 and subbundle2 exports only package2
- add both subbundle1 and subbundle2 to the buildpath of ProjB
- inspect the access rules of the Bnd Build Path of ProjB

Problems:
- (minor) on the Bnd Bundle Path, the name of ProjA is shown twice --> not clear which subbundle is imported
- (MAJOR) the access rules are inconsistent: both packages are visible in both imports, and one of them has a redundant Forbidden rule.

Expected:
2 libraries (even with the same name) with access rules according to the corresponding sub-bundle.

**Comment by derheld42** [comment]
This should be retested. I don't see this issue in my environment any longer.

**Comment by derheld42** [comment]
this also may be fixed by #999

**Comment by derheld42** [comment]
We are testing a new set of eclipse access rules that resolve some of the transtiive dependency rule problems we're seen. We're letting the rules bake before we make them the default. the above line uses them. See #1003 for more details.

Assuming the new rules go in, this issue should be able to be closed out.
