### ISSUE TITLE
Access restriction due to required project

### ISSUE THREAD

**Issue by sichvoge** [bndtools/bndtools#520]
See also #420. 

Since the issue mentioned above is very crucial for a big project I have. I want to mentioned it again, but with a little example.

I have 3 projects named:  `auth`, `core`, `service`

Project `core` has following content:

```
package core.exceptions;

public class BaseException extends Exception { }
```

```
package core.reporter;

public class Reporter {}
```

There are two sub-bundles: 

* core.exceptions which exports the `core.exceptions` package

```
Export-Package: core.exceptions;version=1.0.0
```

* core.reporter which exports the `core.reporter` package

```
Export-Package: core.reporter;version=1.0.0
```

There is nothing special in bnd.bnd.

```
-sub: *.bnd
```

Project `service` has following content:

```
package service.model;

import core.reporter.Reporter;

public interface Response {
	Reporter getReport();
}
```

On my build path I have added the `core.reporter` sub-bundle and I'm exporting the `service.model` package normally in the bnd.bnd file (so no sub-bundles).

```
-buildpath: core.reporter;version=latest
Export-Package: service.model;version=1.0.0
```

Project `auth` has following content:

```
package auth.api;

import service.model.Response;

public interface LoginResponse extends Response {

}
```

```
package auth.exceptions;

import core.exceptions.BaseException;

public abstract class BaseAuthenticationException extends BaseException {

}
```

There is one sub-bundle `api`

```
Export-Package: auth.api;version=1.0.0,\
	auth.exceptions;version=1.0.0
```

And the bnd.bnd

```
-buildpath: service;version=latest,\
	core.utils;version=latest
-sub: *.bnd
```

Enough from the project structure.

With the settings above I'm getting this errors:

```
Access restriction: The type BaseException is not accessible due to restriction on required project core	BaseAuthenticationException.java	/auth/src/auth/exceptions	line 3	Java Problem
```

```
Access restriction: The type BaseException is not accessible due to restriction on required project core	BaseAuthenticationException.java	/auth/src/auth/exceptions	line 19	Java Problem
```

If I reorder the bundles on buildpath `auth/bnd.bnd` that `core.utils` is before `service` then the errors disappear:

```
-buildpath: core.utils;version=latest,\
	service;version=latest
-sub: *.bnd
```

If I change the class `auth.api.LoginResponse` to:

```
package auth.api;

import service.model.Response;
import core.reporter.Reporter;

public classLoginResponse implements Response {
	@Override
	public Reporter getReport() {
		// TODO Auto-generated method stub
		return null;
	}       
}
```

then the trick with changing the order in the buildpath is not working.

Someone an idea to solve it? Or do I miss something?

**Comment by derheld42** [comment]
to cnf/build.bnd, I added:
eclipse.newaccessrules: true

and it resolved correctly. We are testing a new set of eclipse access rules that resolve some of the transitive dependency rules. We're letting the rules bake before we make them the default. the above line uses them. See #1003 for more details.

Assuming the new rules go in, this issue should be able to be closed out.
