### ISSUE TITLE
Release workspace bundles should have exclude settings

### ISSUE THREAD

**Issue by paulbakker** [bndtools/bndtools#528]
The release workspace bundles feature is awesome, but can become hard to use when there are a lot of projects. In our workflow we only release bundles if we are going to deploy them to a server. Some bundles, like test projects will never be released (because they will never be deployed). 

It would be nice if those projects can be filtered from the release dialog.

**Comment by psoreide** [comment]
This can be done using -releaserepo: <blank> in bnd.bnd
