### ISSUE TITLE
Incorrect Activator entry in Bnd file does not show up in Problems tab

### ISSUE THREAD

**Issue by abroekhuis** [bndtools/bndtools#625]
When a bnd file has an incorrent entry for the Activator the bnd editor shows a error mark. But this error is not shown in the problems tab.

Also, when refactoring a package name, the Activator package isn't updated (see #624). In this case, the bnd editor shows a small red circle after the Activator text field, but not the Error in the header of the editor.

**Comment by seanbright** [comment]
Not able to reproduce in 3.3.0.DEV
