### ISSUE TITLE
BNDtools eclipse plugin vs ant

### ISSUE THREAD

**Issue by Japio007** [bndtools/bndtools#728]
There is a possibility that a project compiles in eclipse and doesn't compile in Ant.
Example Project A depends on B B uses on C in the Api. Eclipse will be happy in project A with just B as C coms with it. But the ant build will fail as the classes from C are not on the build path.
The eclipse plugin resolves other projects in the workspace and adds them to the Bnd Bundle Path, but eclipse then also includes the classpath of that project.
A solution would be to not use the project but the generated jar files of the corresponding project.

**Comment by derheld42** [comment]
#1003 synced up how bndtools buildpath works with how bnd buildpath works.

If all continues to go well, the new bndtools eclipse access rules will be the new default rules in the next release of bndtools. To try the new access rules in eclipse, add this to cnf/build.bnd:
eclipse.newaccessrules: true

Please reopen if these new rules do not support your use case.
