### ISSUE TITLE
Provide preference for new project wizard default template

### ISSUE THREAD

**Issue by BryanHunt** [bndtools/bndtools#729]
I would like the ability to specify a preference for the default project template selected by the New Bnd OSGi Project wizard.  The only template that I want to use is Empty Project because for my use-case:

* I use Equinox 3.9
* I use DS annotations vs the Bnd annotations
* I use JUnit 4.11 vs 3.8

**Comment by pkriens** [comment]
We are moving to a model where you specify templates in the workspace somehow. So we move this to abeyance.

**Comment by njbartlett** [comment]
The new template model has been implemented in 3.1.
