### ISSUE TITLE
Running bnd junit tests doesn't add it to the Run History

### ISSUE THREAD

**Issue by bosschaert** [bndtools/bndtools#836]
If I run a BND JUnit run kicked off from a Project or package or class context menu it does not add this run to my Run History, which is a pity because once it's in the Run History you can run it again with a simple keystroke.

When running is from the bnd.bnd context menu it *does* add it to the history, but it should add it regardless of where it's kicked off from.

**Comment by gamerson** [comment]
I've been hitting Ctrl+F11 lately hoping that JUnit tests would be re-run :)  I'll take this one.
