### ISSUE TITLE
Better JAR File Viewer for component description  xml file

### ISSUE THREAD

**Issue by tangyong** [bndtools/bndtools#864]
Currently, in JAR File Viewer ,  it is hard to read the contents from component description  xml file because of the display format. 

The following is the screen image from my env.

![JAR File Viewer for component description  xml file ](https://cloud.githubusercontent.com/assets/187414/3568439/986828ec-0b30-11e4-961d-52d89a9f48ac.png)

My env:
1 Win7
2 eclipse kepler
3 bndtools 2.4.0.M1

**Comment by seanbright** [comment]
I can confirm that this has been resolved for some time if someone would like to close.
