### ISSUE TITLE
Feature request: seamless project import into eclipse

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bndtools#916]
It would be nice if Bndtools registered an import feature with eclipse, so that developers could check out from source control and start working straight away without having to first commit .project and .classpath files.

**Comment by pkriens** [comment]
Neil, would this be something for you?

**Comment by njbartlett** [comment]
Not sure I understand what is being asked for. It sounds like the existing UI provided by the eGit project.

**Comment by gamerson** [comment]
Hey guys I think Elias is asking for supporting this use-case:

- developers creates brand-new bndtools style workspace (clone from
osgi/workspace, etc)
- developers creates a few bundle projects manually in the directory (maybe
copy/paste from somewhere?)
- now developer wants to open this bndtools workspace including all the
projects but no .classpath or .project files have ever been created.

So I believe Elias is asking for a import wizard that has the "smarts" to
add .project/.classpath files accordingly to those existing bundle projects
and then open those projects in eclipse.

On Tue, Mar 15, 2016 at 8:51 PM, Neil Bartlett <notifications@github.com>
wrote:

> Not sure I understand what is being asked for. It sounds like the existing
> UI provided by the eGit project.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bndtools/issues/916#issuecomment-197106843>
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by njbartlett** [comment]
I'm going to close this because I don't think it's a common enough use-case... why not just create the projects in Bndtools?

I will consider a PR if somebody cares enough about this feature to implement it.

**Comment by lostiniceland** [comment]
I am working on a PR for this (started on this several month ago but did not have the time to finish it). Simple import is working but UI and complex setups needs further improvement.
