### ISSUE TITLE
Hidden TableViewer entries on Yosemite 

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bndtools#930]
Several places where we use JFace TableViewers, the first entry in the list appears to be hidden. I believe it's a Mac OS Yosemite problem because I don't recall the issue before upgrading.

Examples I've found so far:
1. Drag a package without packageinfo/package-info.java from Package Explorer to the Export Packages panel. The "Missing Package Info" dialog appears, but the first and only entry in the list is hidden.
2. Drag a bundle from Mac Finder into a local repo in the Repositories view, the import dialog is shown. Again the first (and perhaps only) bundle in the list is not shown.

Note that the contents are in fact known... if you OK the dialog then everything continues as normal. You just can't see the row.

Screenshots attached.
![screen shot 2014-10-27 at 15 56 45](https://cloud.githubusercontent.com/assets/6366/4794016/0cae2b48-5df2-11e4-954f-42e1fa43936d.png)
![screen shot 2014-10-27 at 15 56 29](https://cloud.githubusercontent.com/assets/6366/4794021/10e0d8e6-5df2-11e4-934c-5eaf72015b3f.png)

**Comment by GrantPax** [comment]
Workaround: resize the window. The repaint is correct.

**Comment by njbartlett** [comment]
It looks like this was fixed in SWT by Eclipse Mars, so I'm happy to leave this bug closed. I don't want to add workarounds for a specific Eclipse/MacOS combo in every class where we use TableViewers.

**Comment by GrantPax** [comment]
Sorry. I misspoke. I should have said something less formal like "user workaround". I did not mean to imply that something ought to be changed here.
