### ISSUE TITLE
JPM Repo: Issues when working offline

### ISSUE THREAD

**Issue by redrezo** [bndtools/bndtools#932]
the jpm repo seems need an always working internet connection. If you are traveling and loose your  connection this leads to build errors.
I just tried to reproduce it by just switching off my wlan, but building worked, so i think this is either triggered by repo lookups or some kind of timed task.

I'm using   Bndtools	2.4.0.M2-20140926-111158-ga91d084

there are a lot of 'different length, will refetch' messages and some UnknownHostException

i think the length check and fetch routine should never disable/invalidate the local cached artefacts if the internet connection is not working

here are the errors from my error log (there is no stacktrace available)

```
bndtools.core
Error
Mon Oct 27 20:43:35 CET 2014
found file but of different length /home/ccaks/git/chest/bundles/cnf/cache/jpm/shas/022069627D5F5EE1C3A6B7B9E29EEF7BCFB2CF24/org.eclipse.emf.common-2.10.0.v20140514-1158.jar, will refetch

bndtools.core
Error
Mon Oct 27 20:43:55 CET 2014
failed to download java.net.UnknownHostException: repo1.maven.org: /home/ccaks/git/chest/bundles/cnf/cache/jpm/shas/022069627D5F5EE1C3A6B7B9E29EEF7BCFB2CF24/org.eclipse.emf.common-2.10.0.v20140514-1158.jar
```

Edit: Just ran into the issue again on RC1
got antoher error though:
```
eclipse.buildId=4.4.1.M20140925-0400
java.version=1.8.0_20
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_AT
Command-line arguments:  -os linux -ws gtk -arch x86_64

bndtools.core
Error
Tue Oct 28 20:52:04 CET 2014
failed to download java.net.SocketTimeoutException: Read timed out: /home/ccaks/git/chest/bundles/cnf/cache/jpm/shas/022069627D5F5EE1C3A6B7B9E29EEF7BCFB2CF24/org.eclipse.emf.common-2.10.0.v20140514-1158.jar
```
again no stacktrace available

but i can say it happend while i made changes to the source and the resolver tried to update my running osgi platform

**Comment by pkriens** [comment]
part of it is the problem that shit happens :-( Not much I can do about that. However, I added an offline mode (select the repository and call up a menu) and added a crawler that will eagerly fetch all dependencies.
