### ISSUE TITLE
Redundant run bundles added after run requirements resolution

### ISSUE THREAD

**Issue by jiri-vinarek** [bndtools/bndtools#934]
After clicking on "Resolve" in the bndrun configuration some run bundles are added multiple times with different versions. 

I've created the project showing this problem at https://github.com/jiri-vinarek/bnd-resolve-problem. The problematic package is ```org.apache.felix.http.jetty``` which is after resolution added twice. The second added bundle seems to be redundant as the "Reasons" list in the "Resolution Results" dialog contains only single item ```REQUIRED BY <<INITIAL>> 0.0.0 [filter:=(osgi.identity=org.apache.felix.http.jetty)]```. This item represents the run requirement added by user if I understand correctly.

The list of resolved run bundles depends on the order of run requirements. With following bndrun configuration the jetty bundle is added twice:

```
-runfw: org.eclipse.osgi;version='[3.10.1.v20140909-1633,3.10.1.v20140909-1633]'
-runee: JavaSE-1.7
-runsystemcapabilities: ${native_capability}

-resolve.effective: active


-runrequires:  \
	osgi.identity;filter:='(osgi.identity=resolve-problem)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.http.jetty)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.http.whiteboard)',\
	osgi.identity;filter:='(osgi.identity=org.eclipse.osgi)'
-runbundles:  \
	org.apache.felix.configadmin;version='[1.8.0,1.8.1)',\
	org.apache.felix.http.jetty;version='[2.2.0,2.2.1)',\
	org.apache.felix.http.jetty;version='[2.2.2,2.2.3)',\
	org.apache.felix.http.whiteboard;version='[2.2.2,2.2.3)',\
	org.apache.felix.scr;version='[1.6.2,1.6.3)',\
	resolve-problem;version=latest
```

And with this one only once:

```
-runfw: org.eclipse.osgi;version='[3.10.1.v20140909-1633,3.10.1.v20140909-1633]'
-runee: JavaSE-1.7
-runsystemcapabilities: ${native_capability}

-resolve.effective: active


-runrequires:  \
	osgi.identity;filter:='(osgi.identity=resolve-problem)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.http.whiteboard)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.http.jetty)',\
	osgi.identity;filter:='(osgi.identity=org.eclipse.osgi)'
-runbundles:  \
	org.apache.felix.configadmin;version='[1.8.0,1.8.1)',\
	org.apache.felix.http.jetty;version='[2.2.2,2.2.3)',\
	org.apache.felix.http.whiteboard;version='[2.2.2,2.2.3)',\
	org.apache.felix.scr;version='[1.6.2,1.6.3)',\
	resolve-problem;version=latest
```

The bundle should be added only once as its presence causes errors during server startup.

Initial discussion about the problem:
https://groups.google.com/d/topic/bndtools-users/o-Fi-O8xpZ0/discussion
Tested with bndtools 2.4.0.RC1-20141029-055557-gecca0bf and Eclipse Luna SR1.

**Comment by pkriens** [comment]
We assume this is fixed ... could you verify and reopen or file a new bug if it isnt?
