### ISSUE TITLE
Deadlock on closing Eclipse

### ISSUE THREAD

**Issue by peterkir** [bndtools/bndtools#944]
Win7, Eclipse 4.3.2, Bndtools 2.4.0.M1-20140808-092705-gbebfa62

When trying to close the Eclipse it hangs.
JMC is giving a deadlock detection for the following 2 threads with stacktraces.

Stack Trace
Worker-2150 [25495] (BLOCKED)
   aQute.bnd.build.Project.getVersions line: 2676 
   aQute.bnd.build.WorkspaceRepository.versions line: 131 
   aQute.bnd.build.Project.getBundle line: 978 
   aQute.bnd.build.Project.getBundles line: 505 
   aQute.bnd.build.Project.parseBuildpath line: 417 
   aQute.bnd.build.Project.prepare line: 273 
   aQute.bnd.build.Project.getBuildpath line: 619 
   org.bndtools.builder.classpath.BndContainerInitializer.calculateProjectClasspath line: 190 
   org.bndtools.builder.classpath.BndContainerInitializer.resetClasspaths line: 111 
   org.bndtools.builder.classpath.BndContainerInitializer.resetClasspaths line: 104 
   org.bndtools.builder.NewBuilder.build line: 173 
   org.eclipse.core.internal.events.BuildManager$2.run line: 733 
   org.eclipse.core.runtime.SafeRunner.run line: 42 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 206 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 246 
   org.eclipse.core.internal.events.BuildManager$1.run line: 299 
   org.eclipse.core.runtime.SafeRunner.run line: 42 
   org.eclipse.core.internal.events.BuildManager.basicBuild line: 302 
   org.eclipse.core.internal.events.BuildManager.basicBuildLoop line: 358 
   org.eclipse.core.internal.events.BuildManager.build line: 381 
   org.eclipse.core.internal.events.AutoBuildJob.doBuild line: 143 
   org.eclipse.core.internal.events.AutoBuildJob.run line: 241 
   org.eclipse.core.internal.jobs.Worker.run line: 53 

   
Stack Trace
Worker-2139 [25405] (BLOCKED)
   aQute.bnd.build.Project.getBuilder line: 132 
   aQute.bnd.build.Project.getSubBuilders line: 2110 
   aQute.bnd.build.Project.getVersions line: 2678 
   aQute.bnd.build.WorkspaceRepository.versions line: 131 
   aQute.bnd.build.Project.getBundle line: 978 
   aQute.bnd.build.Project.getBundles line: 505 
   aQute.bnd.build.Project.parseBuildpath line: 417 
   aQute.bnd.build.Project.prepare line: 273 
   aQute.bnd.build.Project.getBuildpath line: 619 
   org.bndtools.builder.classpath.BndContainerInitializer.calculateProjectClasspath line: 190 
   org.bndtools.builder.classpath.BndContainerInitializer.resetClasspaths line: 111 
   org.bndtools.builder.classpath.BndContainerInitializer.resetClasspaths line: 104 
   org.bndtools.builder.jobs.newproject.AdjustClasspathsForNewProjectJob.runInWorkspace line: 53 
   org.eclipse.core.internal.resources.InternalWorkspaceJob.run line: 38 
   org.eclipse.core.internal.jobs.Worker.run line: 53

**Comment by bjhargrave** [comment]
Need to ensure multiple threads are not active in bnd when setting classpath container.
