### ISSUE TITLE
Fresh import of bndtools sources gives a lot of errors and creates files

### ISSUE THREAD

**Issue by kullmanp** [bndtools/bndtools#945]
I was following the steps in http://bndtools.org/development.html. After importing the master branch of bndtools I end up with a workspace with 28 errors. Egit wants to commit 120 files (deleted .settings and created .settings with some prefs files). The command line git doesn't see any changes. 

It doesn't matter whether I import just the projects in the root or whether I import the projects in subfolders (28 errors).

The errors are:
14 times: "The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. "
14 times: "The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files AmdatuRestTemplate.java" or similar.

**Comment by strangeskies-travis** [comment]
For anyone like me landing here after googling the `Classes found in the wrong directory` error, it is simple to resolve by navigating to `resources/enroute/osgi.enroute.template/...` under the bndtools.core project and making sure none of any `bin` or `bin_test` contain any jars. Not sure why it happens in the first place though.

**Comment by eliasvasylenko** [comment]
For anyone like me landing here after googling the Classes found in the wrong directory error, it is simple to resolve by navigating to resources/enroute/osgi.enroute.template/... under the bndtools.core project and making sure none of any bin or bin_test contain any jars. Not sure why it happens in the first place though.
