### ISSUE TITLE
Cleanup the workspace template

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#952]
The workspace template seems to include a buildrepo directory with lots of bundles that are out of date wrt the bundle hub now. It also seems to be confusing to have the same bundles in buildrepo and in the bundle hub repo.

1) We should include an absolute minimal setup in the build in template
2) Recommend to use repository based workspaces like enRoute

**Comment by GrantPax** [comment]
Is the [workspace repository](https://github.com/osgi/workspace) the workaround for this issue?

**Comment by bjhargrave** [comment]
> Is the workspace repository the workaround for this issue?

This is an example of (2) above.

**Comment by GrantPax** [comment]
Ah. Thank you.

**Comment by njbartlett** [comment]
I tidied this up significantly in 625aa4a61304088ed51991e66492bed07af5403a.

I have renamed the "Build" repo to "Non OSGi", and reduced its contents to just JUnit and Hamcrest. The osgi.core jars can be found in the Hub or JPM4J, and I don't think anybody was using the ee.minimum/foundation jars.
