### ISSUE TITLE
Move to use JDK 8 as the build JDK

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bndtools#959]
We currently build bndtools with JDK 7. See the .travis.yml file for example. When building with JDK 8, there are some warnings and one compiler error. These need to be fixed so was can change .travis.yml and cloudbees to build bndtools with JDK 8.

**Comment by The-Alchemist** [comment]
For the curious, this is only error when building against Java 8:

```
/home/travis/build/The-Alchemist/bndtools/bndtools.core/src/bndtools/refactor/PkgRenameParticipant.java:55: error: cannot access IJavaElementMapper
        if (((RenamePackageProcessor) this.getProcessor()).getRenameSubpackages())
                                                          ^
  class file for org.eclipse.jdt.core.refactoring.IJavaElementMapper not found
```

**Comment by dhumeniuk** [comment]
I thought the JDK was supposed to support building for older versions. I see the build.bnd has:

javac.source:               1.6
javac.target:               1.6

I'm curious why this doesn't work.

**Comment by bjhargrave** [comment]
> I'm curious why this doesn't work.

Me too. Which is why we have this issue :-)

I am concerned there may be some type accessibility issue in the [older version of Eclipse (3.7.2)](https://github.com/bndtools/bndtools/blob/master/cnf/ext/repositories.bnd#L5) we target for bndtools. Moving to a more recent version of Eclipse might be the solution.

**Comment by bjhargrave** [comment]
I fixed the compilation errors with Java 8. However with java 8 the `classycle` task fails. @njbartlett, what is the purpose of this task? Can we remove it from the build? You can use `gradle -x classycle` to build without using the classycle task.

**Comment by bjhargrave** [comment]
I think classycle is broken on Java 8 class files just like bnd was by the addition of compile-time constants entries in the constant pool. See <http://blog.bjhargrave.com/2014/04/java-8-bnd-and-references-to-compile.html>. I sent an email to the classycle developer to inquire about a possible fix for classycle. If we cannot get a fix, we wont be able to use classycle when we move to build with JDK 8.
