### ISSUE TITLE
Indexes of indexed repos are changed on every Eclipse startup

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#966]
This is mighty annoying since now I have changes every time I start Eclipse on a workspace I did not change the repos of.

This can be fixed by removing the 'increment' attribute from the 'repository' xml tag.
That attribute is superfluous anyway.

(changes to indexed repos can be detected through their sha files)

**Comment by pkriens** [comment]
I've changed the increment attribute to depend on the file dates of the underlying files. If these dates have not changed (nor has any of the other things in there changed) then the file that is written is identical so GIT will not whine.
