### ISSUE TITLE
Resolver includes  org.apache.felix.gogo.runtime more than once

### ISSUE THREAD

**Issue by novos40** [bndtools/bndtools#971]
Git-Descriptor: 2.3.0.REL
Git-SHA: 9630178a91143e4c00d435190f282869bc0422fb

Hi,

I am not sure if this is a bug or a feature request. 
The problem is that resolver may include multiple versions of a bundle which **must not be included more than once** like, for example, org.apache.felix.gogo.runtime.
The problem is easily reproduced with the following:
```
-runfw: org.apache.felix.framework;version='4.2.1'
-runee: JavaSE-1.7

-runbundles:  \
	org.apache.felix.gogo.command;version='[0.14.0,0.14.1)',\
	org.apache.felix.gogo.runtime;version='[0.10.0,0.10.1)',\
	org.apache.felix.gogo.runtime;version='[0.12.1,0.12.2)',\
	org.apache.felix.gogo.shell;version='[0.10.0,0.10.1)',\
	org.apache.felix.log;version='[1.0.1,1.0.2)'

-runrequires:  \
	osgi.identity;filter:='(osgi.identity=org.apache.felix.log)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.shell)',\
	osgi.identity;filter:='(osgi.identity=org.apache.felix.gogo.command)'

-resolve.effective: active
-runsystempackages: org.w3c.dom.traversal
```
As you can see, **org.apache.felix.gogo.runtime** was included **twice** which renders the whole runtime useless as it cannot run properly unless one of the runtimes is **manually removed each time after resolution**.
I think the problem traces back to the gogo.shell bundle which has, I guess, a very old definition:
```
Import-Package: org.apache.felix.service.command;status=provisional;version="0.10"
```
which leads to inclusion of runtime v0.10.0 while command bundle brings v0.12.0

In case of any other bundle this would probably go unnoticed, but one cannot have two runtimes running at the same time.

  The bottom line is that we need a more fine-grain control over which versions will get included in case when there is more than one available. (The problem actually manifested itself only after new version of runtime was added to github repository.) I understand all the reasoning behind semantic versioning with its bias to use lowest versions possible, but unfortunately it does not take into account **other reasons** why one would prefer to use higher versions of the bundles (bug fixes being one of them, in real life not everyone follows proper versioning scheme yet). 

I can also see that resolver often brings bundles which are not really needed (for example org.apache.felix.scr 1.6.2 pulls osgi.residental 4.3.0, I guess, because of metatype package even it's not used anywhere at runtime and everything works just fine without it when manually removed). One can get a lot of garbage this way. It might become a real problem if you need to keep your deployment small to run on embedded systems, for example.

There is nothing wrong with the default resolver behavior, but there must be a way to override it in corner cases like this.

Thanks

**Comment by timothyjward** [comment]
The underlying issue was actually in bnd, not bndtools. I have put a fix into bnd master under issue bndtools/bnd#778 this will be available in bndtools master builds shortly.

**Comment by novos40** [comment]
Thanks for fixing. I'll be looking for upgrade to the fixed version.

However, I would still ask you to consider introducing result filtering and negative requirements support as your current language design is incomplete (non-symmetrical) and it's just a matter of time before something else related to this will pop up. Such is the nature of the beast :-) and laws of technical evolution.

**Comment by derheld42** [comment]
There is the -runblacklist setting that can be used to filter out bundles that won't make it into being considered for resolution.

**Comment by fhuberts** [comment]
I agree with novos40, negative reqs should be added, that is much more expressive and logical.
There is a distinct disconnect between adding reqs in run reqs in then disallowing some bundles in -runblacklist.

Symmetry FTW

**Comment by timothyjward** [comment]
@novos40:
> However, I would still ask you to consider introducing result filtering and negative requirements support as your current language design is incomplete (non-symmetrical) and it's just a matter of time before something else related to this will pop up.

@fhuberts:
> I agree with novos40, negative reqs should be added, that is much more expressive and logical.


The current run requirements use the OSGi requirements model, as defined by the OSGi core spec. This means that there's no bnd-specific language to learn, and that it's as easy as possible to map repository queries and resolution. Importantly, run requirements can request any capability from the repositories, not just bundles. There's no concept of a "negative filter" in the OSGi requirements model, instead you exclude things based on their attributes in the standard way.

e.g. the following run requirement filter would find something exporting com.acme.mypackage with special=true, but exclude anything that had boring=true.

    (&(osgi.wiring.package=com.acme.mypackage)(special=true)(!(boring=true)))

More usefully you can do things like this to pull in any DS [1.3,2) implementation:

    (&(osgi.extender=osgi.component)(version>=1.3)(!(version>=2)))

I would require a lot of convincing before changing this model of declaring requirements. It's by far the most natural fit with OSGi, and anything we invent adds another barrier to entry.

As @derheld42 points out, when it comes to excluding things the run blacklist works in a very similar way to the run requirements.. The run blacklist uses a set of generic requirements to find capabilities in the repositories. All resources which host those capabilities are prevented from being part of the resolution result. 

For example to exclude all resources that provide a particular service:

    -runblacklist: osgi.service;filter:="(objectClass=com.acme.FooService)"

If you really need more customisation then this is achieved by registering a ResolverHook in the service registry, just like you would for customising resolution anywhere else in OSGi. The resolver hook can make detailed decisions on a case-by-case basis to prevent undesirable bundles being pulled in.

One further point. Normally the best way to prevent bundles being pulled in is not to have them in your repository. It usually makes sense to have small, focussed repositories that contain only the things you build against or run with.
