### ISSUE TITLE
First bundle not shown when adding new one to repository

### ISSUE THREAD

**Issue by dhumeniuk** [bndtools/bndtools#989]
If you try to drag and drop a bundle into a repository, the bundle will not be listed in the dialog before adding:

![image](https://cloud.githubusercontent.com/assets/456666/5588025/29f44906-90cb-11e4-8623-fcf0ee1e1b79.png)

The bundle will still be added when you click Finish. If multiple bundles are added, the first will not be shown, but the others will.

**Comment by GrantPax** [comment]
Workaround: resize the window. The repaint is correct.
