### ISSUE TITLE
Resolution errors when using CLI arguments infra of bnd launcher

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#993]
Easily reproduced in one of my repos:
https://github.com/fhuberts/musicTreePrograms, commit ```1d7d05e2590528d6b60e6623b9a45886cadbc0be```

Try to resolve ```flac2mp3/flac2mp3.bndrun``` and get this error
```
Unable to resolve <<INITIAL>> version=null:
   missing requirement Require[osgi.identity]{}{filter=(osgi.identity=nl.pelagic.musicTree.flac2mp3.cli)} [caused by:
   Unable to resolve nl.pelagic.musicTree.flac2mp3.cli version=1.0.3.201501081830:
   missing requirement Require[osgi.service]{}{filter=(objectClass=java.lang.Object), effective=active}]
```

No clue how this should be fixed but it's rather serious for me

**Comment by pkriens** [comment]
Bindex analyzes the XML and creates a requirement for each reference. So to solve this problem, create a capability. This is a active time requirement so it will not have any influence on the framework.

You can also add this to the -runcapabalities

**Comment by fhuberts** [comment]
Do you have an example?
Didn't work much work caps yet

**Comment by pkriens** [comment]
Please elaborate what you've tried, you're a bit terse ...

**Comment by fhuberts** [comment]
How does the capability look and where do I have to add it?
I suppose I could add it as a kind of self-capability on the component that uses it?

The code to which this applies:
```
  /**
   * The bnd launcher provides access to the command line arguments via the
   * Launcher object. This object is also registered under Object.
   *
   * @param done unused
   * @param parameters the launcher parameters, which includes the command line
   *          arguments
   */
  @Reference
  void setDone(@SuppressWarnings("unused") Object done, Map<String, Object> parameters) {
    args = (String[]) parameters.get(LAUNCHER_ARGUMENTS);
  }
```

**Comment by pkriens** [comment]
For an enRoute workspace, look at https://github.com/osgi/workspace/blob/master/cnf/ext/enroute-distro.bnd . The end of this file augments the capabilities & requirements of a few repository entries.

    org.knopflerfish.bundle.useradmin: \
       cap=osgi.service;objectClass=org.osgi.service.useradmin.UserAdmin;effective:=active

Additionally, you should be able to use -runcapabilities in your bndrun file:

    -runcapabilities: osgi.service;objectClass=org.osgi.service.useradmin.UserAdmin;effective:=active
