### ISSUE TITLE
Wrong resolution: too many bundles included AND duplicate (different version) bundles

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#994]
Easily reproduced in one of my repos:
https://github.com/fhuberts/musicTreePrograms, commit ```1d7d05e2590528d6b60e6623b9a45886cadbc0be```

In ```nl.pelagic.musicTree.flac2mp3.cli/src/nl/pelagic/musicTree/flac2mp3/cli/Main.java``` comment out or remove the ```@Reference``` on line 159 (because of bug #993)

Now try to resolve ```flac2mp3/flac2mp3-debug.bndrun``` and get 
```
diff --git a/flac2mp3/flac2mp3-debug.bndrun b/flac2mp3/flac2mp3-debug.bndrun
index 6603c4a..49b335d 100644
--- a/flac2mp3/flac2mp3-debug.bndrun
+++ b/flac2mp3/flac2mp3-debug.bndrun
@@ -5,14 +5,26 @@
 	Local,\
 	Bndtools Hub
 
--runbundles: aQute.xray.plugin;version='[1.0.3,1.0.4)',\
-	org.jaudiotagger;version='[2.2.0,2.2.1)',\
-	javax.servlet;version='[2.5.0,2.5.1)',\
+-runbundles: \
+	aQute.xray.plugin;version='[1.7.0,1.7.1)',\
 	nl.pelagic.audio.conversion.flac2mp3;version=latest,\
 	nl.pelagic.audio.conversion.flac2mp3.api;version=latest,\
 	nl.pelagic.audio.musicTree.configuration.api;version=latest,\
 	nl.pelagic.audio.musicTree.syncer;version=latest,\
 	nl.pelagic.audio.musicTree.syncer.api;version=latest,\
+	nl.pelagic.audio.tag.checker;version=latest,\
+	nl.pelagic.audio.tag.checker.api;version=latest,\
+	nl.pelagic.audio.tag.checker.basic;version='[1.0.0,1.0.1)',\
+	nl.pelagic.audio.tag.checker.basic;version=latest,\
+	nl.pelagic.audio.tag.checker.converter.flac;version='[1.0.0,1.0.1)',\
+	nl.pelagic.audio.tag.checker.converter.flac;version=latest,\
+	nl.pelagic.audio.tag.checker.converter.mp3;version='[1.0.0,1.0.1)',\
+	nl.pelagic.audio.tag.checker.converter.mp3;version=latest,\
+	nl.pelagic.audio.tag.checker.filename;version=latest,\
+	nl.pelagic.audio.tag.checker.id3v1;version='[1.0.0,1.0.1)',\
+	nl.pelagic.audio.tag.checker.id3v1;version=latest,\
+	nl.pelagic.audio.tag.checker.unchar;version='[1.0.0,1.0.1)',\
+	nl.pelagic.audio.tag.checker.unchar;version=latest,\
 	nl.pelagic.jaudiotagger.util;version=latest,\
 	nl.pelagic.musicTree.flac2mp3.cli;version=latest,\
 	nl.pelagic.shell.script.listener;version=latest,\
@@ -20,20 +32,22 @@
 	nl.pelagic.shutdownhook;version=latest,\
 	nl.pelagic.shutdownhook.api;version=latest,\
 	nl.pelagic.util;version=latest,\
-	org.apache.felix.configadmin;version='[1.4.0,1.4.1)',\
-	org.apache.felix.gogo.command;version='[0.12.0,0.12.1)',\
+	org.apache.felix.configadmin;version='[1.8.0,1.8.1)',\
+	org.apache.felix.gogo.command;version='[0.14.0,0.14.1)',\
 	org.apache.felix.gogo.runtime;version='[0.10.0,0.10.1)',\
+	org.apache.felix.gogo.runtime;version='[0.12.1,0.12.2)',\
 	org.apache.felix.gogo.shell;version='[0.10.0,0.10.1)',\
-	org.apache.felix.http.jetty;version='[2.2.0,2.2.1)',\
-	org.apache.felix.log;version='[1.0.1,1.0.2)',\
-	org.apache.felix.metatype;version='[1.0.4,1.0.5)',\
+	org.apache.felix.http.jetty;version='[2.2.2,2.2.3)',\
+	org.apache.felix.metatype;version='[1.0.10,1.0.11)',\
 	org.apache.felix.scr;version='[1.6.2,1.6.3)',\
+	org.apache.felix.scr;version='[1.8.2,1.8.3)',\
 	org.apache.felix.shell.remote;version='[1.1.2,1.1.3)',\
 	org.apache.felix.webconsole;version='[3.1.8,3.1.9)',\
-	org.kohsuke.args4j;version='[2.0.26,2.0.27)',\
-	osgi.cmpn;version='[4.3.0,4.3.1)',\
+	org.apache.felix.webconsole;version='[4.2.2,4.2.3)',\
+	org.jaudiotagger;version='[2.2.0,2.2.1)',\
+	org.kohsuke.args4j;version='[2.0.31,2.0.32)',\
 	osgi.enterprise;version='[4.2.0,4.2.1)',\
-	osgi.enterprise;version='[5.0.0,5.0.1)'
+	osgi.residential;version='[4.3.0,4.3.1)'
 -runee: JavaSE-1.7
 -runfw: org.apache.felix.framework;version='[4,5)'
 -runrequires: osgi.identity;filter:='(osgi.identity=nl.pelagic.musicTree.flac2mp3.cli)',\
```
(analogous for ```flac2mp3/flac2mp3.bndrun```)

I see 2 major problems here:

1- The are multiple versions of the same bundle (all that are in the repo); like gogo runtime and all nl.pelagic.audio.tag.checker bundles (multiple versions in the release repo)
2- All of the ```nl.pelagic.audio.tag.checker``` bundles should not be there. These are dragged in because they implement a consumer interface of nl.pelagic.audio.tag.checker.api, which implements a consumer interface of nl.pelagic.shutdownhook.api. IMHO that should not be done if they're not in the run requirements.

**Comment by fhuberts** [comment]
>  IMHO that should not be done if they're not in the run requirements.

At least not until the resolve process is interactive

**Comment by timothyjward** [comment]
The duplication of bundles in resolution output is a known issue, and is being handled under #971 - Thanks for the extra information, I'll use it as additional test input. The fix and any progress will be tracked under the first reported issue.

**Comment by fhuberts** [comment]
Ok, so you fixed the duplicate gogo runtime.
Does that fix also address the multiple DS service component bundles issue?

If not, then please reopen

**Comment by timothyjward** [comment]
As far as I've been able to test the fix means that you should no longer see multiple copies of org.apache.felix.scr, or multiple versions of the checker bundles. 

If the checker requirement is optional then I would not expect to see the checker bundles, if it is mandatory and multiple then the above behaviour will persist (i.e. you will resolve in all of the possibilities). This is the intended behaviour of the resolve operation. 

If you want to filter out these matches then you will need to add a ResolverHook. See [GenericResolveContext](https://github.com/bndtools/bnd/blob/005f89cbe784dd8fcf93a7a07c4e0876189fa060/biz.aQute.resolve/src/biz/aQute/resolve/GenericResolveContext.java) for what the resolver hook does.
