### ISSUE TITLE
Resolution error when using framework [5,6) and -runsystempackages

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#995]
Easily reproduced in one of my repos:
https://github.com/fhuberts/musicTreePrograms, commit ```1d7d05e2590528d6b60e6623b9a45886cadbc0be```

In ```audiotagchecker/audiotagchecker.bndrun``` set
```-runfw``` to ```-runfw: org.apache.felix.framework;version='[5,6)'````

Try to resolve ```audiotagchecker/audiotagchecker.bndrun``` and get this error
```
Unable to resolve <<INITIAL>> version=null:
   missing requirement Require[osgi.identity]{}{filter=(osgi.identity=nl.pelagic.audio.tag.checker.cli)} [caused by:
   Unable to resolve nl.pelagic.audio.tag.checker.cli version=1.0.1.201501081958:
   missing requirement Require[osgi.wiring.package]{}{filter=(&(osgi.wiring.package=nl.pelagic.audio.tag.checker.api)(version>=1.0.0)(!(version>=2.0.0)))} [caused by:
   Unable to resolve nl.pelagic.audio.tag.checker.api version=1.0.1.201501081957:
   missing requirement Require[osgi.wiring.package]{}{filter=(&(osgi.wiring.package=org.jaudiotagger.tag)(version>=2.2.0)(!(version>=3.0.0)))} [caused by:
   Unable to resolve org.jaudiotagger version=2.2.0.1156-5a3e62a:
   missing requirement Require[osgi.wiring.package]{}{filter=(osgi.wiring.package=sun.misc)}]]]
```

That package is provided through ```-runsystempackages: sun.misc,sun.nio.ch```

When using ```-runfw``` to ```-runfw: org.apache.felix.framework;version='[4,5)'```` it does resolve, strange enough.

Something analogous goes for the ```flac2mp/flac2mp3.bndrun``` file

**Comment by pkriens** [comment]
There is no felix [5,6] so this will not resolve anyway?

The resolver is a backtracking model so unfortunately you an get weird errors.

**Comment by fhuberts** [comment]
yeah, jumped the gun here.
forgot to close it
